// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mocks/repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	support "github.com/codecoffy/nitip-core/internal/domain/support"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AutoCloseResolved mocks base method.
func (m *MockRepository) AutoCloseResolved(ctx context.Context, days int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AutoCloseResolved", ctx, days)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AutoCloseResolved indicates an expected call of AutoCloseResolved.
func (mr *MockRepositoryMockRecorder) AutoCloseResolved(ctx, days any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AutoCloseResolved", reflect.TypeOf((*MockRepository)(nil).AutoCloseResolved), ctx, days)
}

// ClaimTicketAtomic mocks base method.
func (m *MockRepository) ClaimTicketAtomic(ctx context.Context, ticketID, csID uuid.UUID) (*support.Ticket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimTicketAtomic", ctx, ticketID, csID)
	ret0, _ := ret[0].(*support.Ticket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimTicketAtomic indicates an expected call of ClaimTicketAtomic.
func (mr *MockRepositoryMockRecorder) ClaimTicketAtomic(ctx, ticketID, csID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimTicketAtomic", reflect.TypeOf((*MockRepository)(nil).ClaimTicketAtomic), ctx, ticketID, csID)
}

// CountActiveByCS mocks base method.
func (m *MockRepository) CountActiveByCS(ctx context.Context, csID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActiveByCS", ctx, csID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActiveByCS indicates an expected call of CountActiveByCS.
func (mr *MockRepositoryMockRecorder) CountActiveByCS(ctx, csID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActiveByCS", reflect.TypeOf((*MockRepository)(nil).CountActiveByCS), ctx, csID)
}

// CreateFAQ mocks base method.
func (m *MockRepository) CreateFAQ(ctx context.Context, faq *support.FAQ) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFAQ", ctx, faq)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateFAQ indicates an expected call of CreateFAQ.
func (mr *MockRepositoryMockRecorder) CreateFAQ(ctx, faq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFAQ", reflect.TypeOf((*MockRepository)(nil).CreateFAQ), ctx, faq)
}

// CreateMessage mocks base method.
func (m *MockRepository) CreateMessage(ctx context.Context, msg *support.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMessage", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMessage indicates an expected call of CreateMessage.
func (mr *MockRepositoryMockRecorder) CreateMessage(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMessage", reflect.TypeOf((*MockRepository)(nil).CreateMessage), ctx, msg)
}

// CreateTicket mocks base method.
func (m *MockRepository) CreateTicket(ctx context.Context, ticket *support.Ticket) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTicket", ctx, ticket)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTicket indicates an expected call of CreateTicket.
func (mr *MockRepositoryMockRecorder) CreateTicket(ctx, ticket any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTicket", reflect.TypeOf((*MockRepository)(nil).CreateTicket), ctx, ticket)
}

// DeleteFAQ mocks base method.
func (m *MockRepository) DeleteFAQ(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFAQ", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFAQ indicates an expected call of DeleteFAQ.
func (mr *MockRepositoryMockRecorder) DeleteFAQ(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFAQ", reflect.TypeOf((*MockRepository)(nil).DeleteFAQ), ctx, id)
}

// FindAllFAQ mocks base method.
func (m *MockRepository) FindAllFAQ(ctx context.Context, activeOnly bool) ([]support.FAQ, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllFAQ", ctx, activeOnly)
	ret0, _ := ret[0].([]support.FAQ)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllFAQ indicates an expected call of FindAllFAQ.
func (mr *MockRepositoryMockRecorder) FindAllFAQ(ctx, activeOnly any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllFAQ", reflect.TypeOf((*MockRepository)(nil).FindAllFAQ), ctx, activeOnly)
}

// FindAllTickets mocks base method.
func (m *MockRepository) FindAllTickets(ctx context.Context, status, category, search string, assignedCSID *uuid.UUID, limit, offset int) ([]support.Ticket, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllTickets", ctx, status, category, search, assignedCSID, limit, offset)
	ret0, _ := ret[0].([]support.Ticket)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAllTickets indicates an expected call of FindAllTickets.
func (mr *MockRepositoryMockRecorder) FindAllTickets(ctx, status, category, search, assignedCSID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllTickets", reflect.TypeOf((*MockRepository)(nil).FindAllTickets), ctx, status, category, search, assignedCSID, limit, offset)
}

// FindFAQByID mocks base method.
func (m *MockRepository) FindFAQByID(ctx context.Context, id uuid.UUID) (*support.FAQ, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindFAQByID", ctx, id)
	ret0, _ := ret[0].(*support.FAQ)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindFAQByID indicates an expected call of FindFAQByID.
func (mr *MockRepositoryMockRecorder) FindFAQByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindFAQByID", reflect.TypeOf((*MockRepository)(nil).FindFAQByID), ctx, id)
}

// FindMessagesByTicketID mocks base method.
func (m *MockRepository) FindMessagesByTicketID(ctx context.Context, ticketID uuid.UUID, afterID *uuid.UUID, afterTime *string, limit int, includeInternal bool) ([]support.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMessagesByTicketID", ctx, ticketID, afterID, afterTime, limit, includeInternal)
	ret0, _ := ret[0].([]support.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMessagesByTicketID indicates an expected call of FindMessagesByTicketID.
func (mr *MockRepositoryMockRecorder) FindMessagesByTicketID(ctx, ticketID, afterID, afterTime, limit, includeInternal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMessagesByTicketID", reflect.TypeOf((*MockRepository)(nil).FindMessagesByTicketID), ctx, ticketID, afterID, afterTime, limit, includeInternal)
}

// FindQueueTickets mocks base method.
func (m *MockRepository) FindQueueTickets(ctx context.Context, limit, offset int) ([]support.Ticket, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindQueueTickets", ctx, limit, offset)
	ret0, _ := ret[0].([]support.Ticket)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindQueueTickets indicates an expected call of FindQueueTickets.
func (mr *MockRepositoryMockRecorder) FindQueueTickets(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindQueueTickets", reflect.TypeOf((*MockRepository)(nil).FindQueueTickets), ctx, limit, offset)
}

// FindTicketByID mocks base method.
func (m *MockRepository) FindTicketByID(ctx context.Context, id uuid.UUID) (*support.Ticket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTicketByID", ctx, id)
	ret0, _ := ret[0].(*support.Ticket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTicketByID indicates an expected call of FindTicketByID.
func (mr *MockRepositoryMockRecorder) FindTicketByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTicketByID", reflect.TypeOf((*MockRepository)(nil).FindTicketByID), ctx, id)
}

// FindTicketByIDForUpdate mocks base method.
func (m *MockRepository) FindTicketByIDForUpdate(ctx context.Context, id uuid.UUID) (*support.Ticket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTicketByIDForUpdate", ctx, id)
	ret0, _ := ret[0].(*support.Ticket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTicketByIDForUpdate indicates an expected call of FindTicketByIDForUpdate.
func (mr *MockRepositoryMockRecorder) FindTicketByIDForUpdate(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTicketByIDForUpdate", reflect.TypeOf((*MockRepository)(nil).FindTicketByIDForUpdate), ctx, id)
}

// FindTicketsByUser mocks base method.
func (m *MockRepository) FindTicketsByUser(ctx context.Context, userID uuid.UUID, limit, offset int) ([]support.Ticket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTicketsByUser", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]support.Ticket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTicketsByUser indicates an expected call of FindTicketsByUser.
func (mr *MockRepositoryMockRecorder) FindTicketsByUser(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTicketsByUser", reflect.TypeOf((*MockRepository)(nil).FindTicketsByUser), ctx, userID, limit, offset)
}

// GetStats mocks base method.
func (m *MockRepository) GetStats(ctx context.Context) (map[string]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx)
	ret0, _ := ret[0].(map[string]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockRepositoryMockRecorder) GetStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockRepository)(nil).GetStats), ctx)
}

// SearchFAQ mocks base method.
func (m *MockRepository) SearchFAQ(ctx context.Context, query, category string, limit int) ([]support.FAQ, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchFAQ", ctx, query, category, limit)
	ret0, _ := ret[0].([]support.FAQ)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchFAQ indicates an expected call of SearchFAQ.
func (mr *MockRepositoryMockRecorder) SearchFAQ(ctx, query, category, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchFAQ", reflect.TypeOf((*MockRepository)(nil).SearchFAQ), ctx, query, category, limit)
}

// UpdateFAQ mocks base method.
func (m *MockRepository) UpdateFAQ(ctx context.Context, faq *support.FAQ) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFAQ", ctx, faq)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFAQ indicates an expected call of UpdateFAQ.
func (mr *MockRepositoryMockRecorder) UpdateFAQ(ctx, faq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFAQ", reflect.TypeOf((*MockRepository)(nil).UpdateFAQ), ctx, faq)
}

// UpdateTicket mocks base method.
func (m *MockRepository) UpdateTicket(ctx context.Context, ticket *support.Ticket) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTicket", ctx, ticket)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTicket indicates an expected call of UpdateTicket.
func (mr *MockRepositoryMockRecorder) UpdateTicket(ctx, ticket any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTicket", reflect.TypeOf((*MockRepository)(nil).UpdateTicket), ctx, ticket)
}
