// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	support "github.com/codecoffy/nitip-core/internal/domain/support"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// ClaimTicket mocks base method.
func (m *MockService) ClaimTicket(ctx context.Context, ticketID, csID uuid.UUID) (*support.Ticket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimTicket", ctx, ticketID, csID)
	ret0, _ := ret[0].(*support.Ticket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimTicket indicates an expected call of ClaimTicket.
func (mr *MockServiceMockRecorder) ClaimTicket(ctx, ticketID, csID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimTicket", reflect.TypeOf((*MockService)(nil).ClaimTicket), ctx, ticketID, csID)
}

// CloseTicket mocks base method.
func (m *MockService) CloseTicket(ctx context.Context, ticketID, userID uuid.UUID, isCS bool) (*support.Ticket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseTicket", ctx, ticketID, userID, isCS)
	ret0, _ := ret[0].(*support.Ticket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CloseTicket indicates an expected call of CloseTicket.
func (mr *MockServiceMockRecorder) CloseTicket(ctx, ticketID, userID, isCS any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseTicket", reflect.TypeOf((*MockService)(nil).CloseTicket), ctx, ticketID, userID, isCS)
}

// CreateFAQ mocks base method.
func (m *MockService) CreateFAQ(ctx context.Context, req support.CreateFAQRequest) (*support.FAQ, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFAQ", ctx, req)
	ret0, _ := ret[0].(*support.FAQ)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFAQ indicates an expected call of CreateFAQ.
func (mr *MockServiceMockRecorder) CreateFAQ(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFAQ", reflect.TypeOf((*MockService)(nil).CreateFAQ), ctx, req)
}

// CreateTicket mocks base method.
func (m *MockService) CreateTicket(ctx context.Context, userID uuid.UUID, req support.CreateTicketRequest) (*support.Ticket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTicket", ctx, userID, req)
	ret0, _ := ret[0].(*support.Ticket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTicket indicates an expected call of CreateTicket.
func (mr *MockServiceMockRecorder) CreateTicket(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTicket", reflect.TypeOf((*MockService)(nil).CreateTicket), ctx, userID, req)
}

// DeleteFAQ mocks base method.
func (m *MockService) DeleteFAQ(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFAQ", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFAQ indicates an expected call of DeleteFAQ.
func (mr *MockServiceMockRecorder) DeleteFAQ(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFAQ", reflect.TypeOf((*MockService)(nil).DeleteFAQ), ctx, id)
}

// GetActiveTicketByCS mocks base method.
func (m *MockService) GetActiveTicketByCS(ctx context.Context, csID uuid.UUID) (*support.Ticket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveTicketByCS", ctx, csID)
	ret0, _ := ret[0].(*support.Ticket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveTicketByCS indicates an expected call of GetActiveTicketByCS.
func (mr *MockServiceMockRecorder) GetActiveTicketByCS(ctx, csID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveTicketByCS", reflect.TypeOf((*MockService)(nil).GetActiveTicketByCS), ctx, csID)
}

// GetMessages mocks base method.
func (m *MockService) GetMessages(ctx context.Context, ticketID, requesterID uuid.UUID, isCSOrAdmin bool, afterID *uuid.UUID, afterTime *string, limit int) ([]support.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessages", ctx, ticketID, requesterID, isCSOrAdmin, afterID, afterTime, limit)
	ret0, _ := ret[0].([]support.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessages indicates an expected call of GetMessages.
func (mr *MockServiceMockRecorder) GetMessages(ctx, ticketID, requesterID, isCSOrAdmin, afterID, afterTime, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessages", reflect.TypeOf((*MockService)(nil).GetMessages), ctx, ticketID, requesterID, isCSOrAdmin, afterID, afterTime, limit)
}

// GetStats mocks base method.
func (m *MockService) GetStats(ctx context.Context) (map[string]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx)
	ret0, _ := ret[0].(map[string]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockServiceMockRecorder) GetStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockService)(nil).GetStats), ctx)
}

// GetTicketByID mocks base method.
func (m *MockService) GetTicketByID(ctx context.Context, ticketID, requesterID uuid.UUID, isCSOrAdmin bool) (*support.Ticket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTicketByID", ctx, ticketID, requesterID, isCSOrAdmin)
	ret0, _ := ret[0].(*support.Ticket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTicketByID indicates an expected call of GetTicketByID.
func (mr *MockServiceMockRecorder) GetTicketByID(ctx, ticketID, requesterID, isCSOrAdmin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTicketByID", reflect.TypeOf((*MockService)(nil).GetTicketByID), ctx, ticketID, requesterID, isCSOrAdmin)
}

// ListAllTickets mocks base method.
func (m *MockService) ListAllTickets(ctx context.Context, status, category, search string, assignedCSID *uuid.UUID, limit, offset int) ([]support.Ticket, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllTickets", ctx, status, category, search, assignedCSID, limit, offset)
	ret0, _ := ret[0].([]support.Ticket)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAllTickets indicates an expected call of ListAllTickets.
func (mr *MockServiceMockRecorder) ListAllTickets(ctx, status, category, search, assignedCSID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllTickets", reflect.TypeOf((*MockService)(nil).ListAllTickets), ctx, status, category, search, assignedCSID, limit, offset)
}

// ListFAQ mocks base method.
func (m *MockService) ListFAQ(ctx context.Context, activeOnly bool) ([]support.FAQ, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFAQ", ctx, activeOnly)
	ret0, _ := ret[0].([]support.FAQ)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFAQ indicates an expected call of ListFAQ.
func (mr *MockServiceMockRecorder) ListFAQ(ctx, activeOnly any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFAQ", reflect.TypeOf((*MockService)(nil).ListFAQ), ctx, activeOnly)
}

// ListMyTickets mocks base method.
func (m *MockService) ListMyTickets(ctx context.Context, userID uuid.UUID, limit, offset int) ([]support.Ticket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMyTickets", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]support.Ticket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMyTickets indicates an expected call of ListMyTickets.
func (mr *MockServiceMockRecorder) ListMyTickets(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMyTickets", reflect.TypeOf((*MockService)(nil).ListMyTickets), ctx, userID, limit, offset)
}

// ListQueueTickets mocks base method.
func (m *MockService) ListQueueTickets(ctx context.Context, limit, offset int) ([]support.Ticket, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListQueueTickets", ctx, limit, offset)
	ret0, _ := ret[0].([]support.Ticket)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListQueueTickets indicates an expected call of ListQueueTickets.
func (mr *MockServiceMockRecorder) ListQueueTickets(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListQueueTickets", reflect.TypeOf((*MockService)(nil).ListQueueTickets), ctx, limit, offset)
}

// ReleaseTicket mocks base method.
func (m *MockService) ReleaseTicket(ctx context.Context, ticketID, csID uuid.UUID) (*support.Ticket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseTicket", ctx, ticketID, csID)
	ret0, _ := ret[0].(*support.Ticket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReleaseTicket indicates an expected call of ReleaseTicket.
func (mr *MockServiceMockRecorder) ReleaseTicket(ctx, ticketID, csID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseTicket", reflect.TypeOf((*MockService)(nil).ReleaseTicket), ctx, ticketID, csID)
}

// ReopenTicket mocks base method.
func (m *MockService) ReopenTicket(ctx context.Context, ticketID, userID uuid.UUID) (*support.Ticket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReopenTicket", ctx, ticketID, userID)
	ret0, _ := ret[0].(*support.Ticket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReopenTicket indicates an expected call of ReopenTicket.
func (mr *MockServiceMockRecorder) ReopenTicket(ctx, ticketID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReopenTicket", reflect.TypeOf((*MockService)(nil).ReopenTicket), ctx, ticketID, userID)
}

// ResolveTicket mocks base method.
func (m *MockService) ResolveTicket(ctx context.Context, ticketID, csID uuid.UUID) (*support.Ticket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveTicket", ctx, ticketID, csID)
	ret0, _ := ret[0].(*support.Ticket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveTicket indicates an expected call of ResolveTicket.
func (mr *MockServiceMockRecorder) ResolveTicket(ctx, ticketID, csID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveTicket", reflect.TypeOf((*MockService)(nil).ResolveTicket), ctx, ticketID, csID)
}

// SearchFAQ mocks base method.
func (m *MockService) SearchFAQ(ctx context.Context, query, category string, limit int) ([]support.FAQ, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchFAQ", ctx, query, category, limit)
	ret0, _ := ret[0].([]support.FAQ)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchFAQ indicates an expected call of SearchFAQ.
func (mr *MockServiceMockRecorder) SearchFAQ(ctx, query, category, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchFAQ", reflect.TypeOf((*MockService)(nil).SearchFAQ), ctx, query, category, limit)
}

// SendMessage mocks base method.
func (m *MockService) SendMessage(ctx context.Context, ticketID, senderID uuid.UUID, senderRole, message string, isInternal bool) (*support.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, ticketID, senderID, senderRole, message, isInternal)
	ret0, _ := ret[0].(*support.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockServiceMockRecorder) SendMessage(ctx, ticketID, senderID, senderRole, message, isInternal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockService)(nil).SendMessage), ctx, ticketID, senderID, senderRole, message, isInternal)
}

// StartAutoCloseWorker mocks base method.
func (m *MockService) StartAutoCloseWorker(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartAutoCloseWorker", ctx)
}

// StartAutoCloseWorker indicates an expected call of StartAutoCloseWorker.
func (mr *MockServiceMockRecorder) StartAutoCloseWorker(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartAutoCloseWorker", reflect.TypeOf((*MockService)(nil).StartAutoCloseWorker), ctx)
}

// UpdateFAQ mocks base method.
func (m *MockService) UpdateFAQ(ctx context.Context, id uuid.UUID, req support.UpdateFAQRequest) (*support.FAQ, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFAQ", ctx, id, req)
	ret0, _ := ret[0].(*support.FAQ)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateFAQ indicates an expected call of UpdateFAQ.
func (mr *MockServiceMockRecorder) UpdateFAQ(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFAQ", reflect.TypeOf((*MockService)(nil).UpdateFAQ), ctx, id, req)
}

// MockConfigService is a mock of ConfigService interface.
type MockConfigService struct {
	ctrl     *gomock.Controller
	recorder *MockConfigServiceMockRecorder
	isgomock struct{}
}

// MockConfigServiceMockRecorder is the mock recorder for MockConfigService.
type MockConfigServiceMockRecorder struct {
	mock *MockConfigService
}

// NewMockConfigService creates a new mock instance.
func NewMockConfigService(ctrl *gomock.Controller) *MockConfigService {
	mock := &MockConfigService{ctrl: ctrl}
	mock.recorder = &MockConfigServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigService) EXPECT() *MockConfigServiceMockRecorder {
	return m.recorder
}

// GetValue mocks base method.
func (m *MockConfigService) GetValue(ctx context.Context, key, defaultValue string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValue", ctx, key, defaultValue)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetValue indicates an expected call of GetValue.
func (mr *MockConfigServiceMockRecorder) GetValue(ctx, key, defaultValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValue", reflect.TypeOf((*MockConfigService)(nil).GetValue), ctx, key, defaultValue)
}
