// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	banner "github.com/codecoffy/nitip-core/internal/domain/banner"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreateBanner mocks base method.
func (m *MockService) CreateBanner(ctx context.Context, title, imageURL string, redirectURL *string, isActive bool) (*banner.Banner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBanner", ctx, title, imageURL, redirectURL, isActive)
	ret0, _ := ret[0].(*banner.Banner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBanner indicates an expected call of CreateBanner.
func (mr *MockServiceMockRecorder) CreateBanner(ctx, title, imageURL, redirectURL, isActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBanner", reflect.TypeOf((*MockService)(nil).CreateBanner), ctx, title, imageURL, redirectURL, isActive)
}

// DeleteBanner mocks base method.
func (m *MockService) DeleteBanner(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBanner", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBanner indicates an expected call of DeleteBanner.
func (mr *MockServiceMockRecorder) DeleteBanner(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBanner", reflect.TypeOf((*MockService)(nil).DeleteBanner), ctx, id)
}

// GetActiveBanners mocks base method.
func (m *MockService) GetActiveBanners(ctx context.Context) ([]banner.Banner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveBanners", ctx)
	ret0, _ := ret[0].([]banner.Banner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveBanners indicates an expected call of GetActiveBanners.
func (mr *MockServiceMockRecorder) GetActiveBanners(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveBanners", reflect.TypeOf((*MockService)(nil).GetActiveBanners), ctx)
}

// GetAllBanners mocks base method.
func (m *MockService) GetAllBanners(ctx context.Context) ([]banner.Banner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllBanners", ctx)
	ret0, _ := ret[0].([]banner.Banner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllBanners indicates an expected call of GetAllBanners.
func (mr *MockServiceMockRecorder) GetAllBanners(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllBanners", reflect.TypeOf((*MockService)(nil).GetAllBanners), ctx)
}

// GetBannerByID mocks base method.
func (m *MockService) GetBannerByID(ctx context.Context, id uuid.UUID) (*banner.Banner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBannerByID", ctx, id)
	ret0, _ := ret[0].(*banner.Banner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBannerByID indicates an expected call of GetBannerByID.
func (mr *MockServiceMockRecorder) GetBannerByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBannerByID", reflect.TypeOf((*MockService)(nil).GetBannerByID), ctx, id)
}

// UpdateBanner mocks base method.
func (m *MockService) UpdateBanner(ctx context.Context, id uuid.UUID, title, imageURL string, redirectURL *string, isActive bool) (*banner.Banner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBanner", ctx, id, title, imageURL, redirectURL, isActive)
	ret0, _ := ret[0].(*banner.Banner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBanner indicates an expected call of UpdateBanner.
func (mr *MockServiceMockRecorder) UpdateBanner(ctx, id, title, imageURL, redirectURL, isActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBanner", reflect.TypeOf((*MockService)(nil).UpdateBanner), ctx, id, title, imageURL, redirectURL, isActive)
}

// UploadImage mocks base method.
func (m *MockService) UploadImage(ctx context.Context, filename string, content io.Reader, size int64, contentType string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadImage", ctx, filename, content, size, contentType)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadImage indicates an expected call of UploadImage.
func (mr *MockServiceMockRecorder) UploadImage(ctx, filename, content, size, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadImage", reflect.TypeOf((*MockService)(nil).UploadImage), ctx, filename, content, size, contentType)
}
