// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mocks/repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	order "github.com/codecoffy/nitip-core/internal/domain/order"
	uuid "github.com/google/uuid"
	bun "github.com/uptrace/bun"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CancelAtomic mocks base method.
func (m *MockRepository) CancelAtomic(ctx context.Context, db bun.IDB, id uuid.UUID, reason string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelAtomic", ctx, db, id, reason)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelAtomic indicates an expected call of CancelAtomic.
func (mr *MockRepositoryMockRecorder) CancelAtomic(ctx, db, id, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelAtomic", reflect.TypeOf((*MockRepository)(nil).CancelAtomic), ctx, db, id, reason)
}

// CompleteAtomic mocks base method.
func (m *MockRepository) CompleteAtomic(ctx context.Context, db bun.IDB, id, runnerID uuid.UUID, deliveryImg string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteAtomic", ctx, db, id, runnerID, deliveryImg)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompleteAtomic indicates an expected call of CompleteAtomic.
func (mr *MockRepositoryMockRecorder) CompleteAtomic(ctx, db, id, runnerID, deliveryImg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteAtomic", reflect.TypeOf((*MockRepository)(nil).CompleteAtomic), ctx, db, id, runnerID, deliveryImg)
}

// CountTodayAcceptances mocks base method.
func (m *MockRepository) CountTodayAcceptances(ctx context.Context, runnerID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTodayAcceptances", ctx, runnerID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTodayAcceptances indicates an expected call of CountTodayAcceptances.
func (mr *MockRepositoryMockRecorder) CountTodayAcceptances(ctx, runnerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTodayAcceptances", reflect.TypeOf((*MockRepository)(nil).CountTodayAcceptances), ctx, runnerID)
}

// CountTodayOrders mocks base method.
func (m *MockRepository) CountTodayOrders(ctx context.Context, userID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTodayOrders", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTodayOrders indicates an expected call of CountTodayOrders.
func (mr *MockRepositoryMockRecorder) CountTodayOrders(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTodayOrders", reflect.TypeOf((*MockRepository)(nil).CountTodayOrders), ctx, userID)
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, db bun.IDB, arg2 *order.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, db, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, db, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, db, arg2)
}

// Delete mocks base method.
func (m *MockRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), ctx, id)
}

// ExpireOldOrders mocks base method.
func (m *MockRepository) ExpireOldOrders(ctx context.Context, cutoff time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpireOldOrders", ctx, cutoff)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExpireOldOrders indicates an expected call of ExpireOldOrders.
func (mr *MockRepositoryMockRecorder) ExpireOldOrders(ctx, cutoff any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpireOldOrders", reflect.TypeOf((*MockRepository)(nil).ExpireOldOrders), ctx, cutoff)
}

// FindAll mocks base method.
func (m *MockRepository) FindAll(ctx context.Context, offset, limit int) ([]order.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, offset, limit)
	ret0, _ := ret[0].([]order.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockRepositoryMockRecorder) FindAll(ctx, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockRepository)(nil).FindAll), ctx, offset, limit)
}

// FindAllWithFilters mocks base method.
func (m *MockRepository) FindAllWithFilters(ctx context.Context, status string, offset, limit int) ([]order.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllWithFilters", ctx, status, offset, limit)
	ret0, _ := ret[0].([]order.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllWithFilters indicates an expected call of FindAllWithFilters.
func (mr *MockRepositoryMockRecorder) FindAllWithFilters(ctx, status, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllWithFilters", reflect.TypeOf((*MockRepository)(nil).FindAllWithFilters), ctx, status, offset, limit)
}

// FindAvailable mocks base method.
func (m *MockRepository) FindAvailable(ctx context.Context, params order.FindAvailableParams) ([]order.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAvailable", ctx, params)
	ret0, _ := ret[0].([]order.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAvailable indicates an expected call of FindAvailable.
func (mr *MockRepositoryMockRecorder) FindAvailable(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAvailable", reflect.TypeOf((*MockRepository)(nil).FindAvailable), ctx, params)
}

// FindByID mocks base method.
func (m *MockRepository) FindByID(ctx context.Context, id uuid.UUID) (*order.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*order.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRepository)(nil).FindByID), ctx, id)
}

// FindByIDForUpdate mocks base method.
func (m *MockRepository) FindByIDForUpdate(ctx context.Context, db bun.IDB, id uuid.UUID) (*order.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIDForUpdate", ctx, db, id)
	ret0, _ := ret[0].(*order.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIDForUpdate indicates an expected call of FindByIDForUpdate.
func (mr *MockRepositoryMockRecorder) FindByIDForUpdate(ctx, db, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIDForUpdate", reflect.TypeOf((*MockRepository)(nil).FindByIDForUpdate), ctx, db, id)
}

// FindByRequesterID mocks base method.
func (m *MockRepository) FindByRequesterID(ctx context.Context, requesterID uuid.UUID) ([]order.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByRequesterID", ctx, requesterID)
	ret0, _ := ret[0].([]order.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByRequesterID indicates an expected call of FindByRequesterID.
func (mr *MockRepositoryMockRecorder) FindByRequesterID(ctx, requesterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByRequesterID", reflect.TypeOf((*MockRepository)(nil).FindByRequesterID), ctx, requesterID)
}

// FindByRunnerID mocks base method.
func (m *MockRepository) FindByRunnerID(ctx context.Context, runnerID uuid.UUID) ([]order.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByRunnerID", ctx, runnerID)
	ret0, _ := ret[0].([]order.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByRunnerID indicates an expected call of FindByRunnerID.
func (mr *MockRepositoryMockRecorder) FindByRunnerID(ctx, runnerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByRunnerID", reflect.TypeOf((*MockRepository)(nil).FindByRunnerID), ctx, runnerID)
}

// FindByUserID mocks base method.
func (m *MockRepository) FindByUserID(ctx context.Context, userID uuid.UUID, limit, offset int, startDate, endDate string) ([]order.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", ctx, userID, limit, offset, startDate, endDate)
	ret0, _ := ret[0].([]order.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockRepositoryMockRecorder) FindByUserID(ctx, userID, limit, offset, startDate, endDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockRepository)(nil).FindByUserID), ctx, userID, limit, offset, startDate, endDate)
}

// Update mocks base method.
func (m *MockRepository) Update(ctx context.Context, db bun.IDB, arg2 *order.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, db, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder) Update(ctx, db, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), ctx, db, arg2)
}

// UpdateStatus mocks base method.
func (m *MockRepository) UpdateStatus(ctx context.Context, id uuid.UUID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockRepositoryMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockRepository)(nil).UpdateStatus), ctx, id, status)
}

// UpdateWithStatusCheck mocks base method.
func (m *MockRepository) UpdateWithStatusCheck(ctx context.Context, db bun.IDB, arg2 *order.Order, expectedStatus string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWithStatusCheck", ctx, db, arg2, expectedStatus)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWithStatusCheck indicates an expected call of UpdateWithStatusCheck.
func (mr *MockRepositoryMockRecorder) UpdateWithStatusCheck(ctx, db, arg2, expectedStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWithStatusCheck", reflect.TypeOf((*MockRepository)(nil).UpdateWithStatusCheck), ctx, db, arg2, expectedStatus)
}
