// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	order "github.com/codecoffy/nitip-core/internal/domain/order"
	user "github.com/codecoffy/nitip-core/internal/domain/user"
	notification "github.com/codecoffy/nitip-core/internal/notification"
	uuid "github.com/google/uuid"
	bun "github.com/uptrace/bun"
	gomock "go.uber.org/mock/gomock"
)

// MockMatcher is a mock of Matcher interface.
type MockMatcher struct {
	ctrl     *gomock.Controller
	recorder *MockMatcherMockRecorder
	isgomock struct{}
}

// MockMatcherMockRecorder is the mock recorder for MockMatcher.
type MockMatcherMockRecorder struct {
	mock *MockMatcher
}

// NewMockMatcher creates a new mock instance.
func NewMockMatcher(ctrl *gomock.Controller) *MockMatcher {
	mock := &MockMatcher{ctrl: ctrl}
	mock.recorder = &MockMatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatcher) EXPECT() *MockMatcherMockRecorder {
	return m.recorder
}

// DispatchOrder mocks base method.
func (m *MockMatcher) DispatchOrder(ctx context.Context, orderID string, runners []user.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DispatchOrder", ctx, orderID, runners)
	ret0, _ := ret[0].(error)
	return ret0
}

// DispatchOrder indicates an expected call of DispatchOrder.
func (mr *MockMatcherMockRecorder) DispatchOrder(ctx, orderID, runners any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DispatchOrder", reflect.TypeOf((*MockMatcher)(nil).DispatchOrder), ctx, orderID, runners)
}

// EnqueueMatching mocks base method.
func (m *MockMatcher) EnqueueMatching(orderID uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "EnqueueMatching", orderID)
}

// EnqueueMatching indicates an expected call of EnqueueMatching.
func (mr *MockMatcherMockRecorder) EnqueueMatching(orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueMatching", reflect.TypeOf((*MockMatcher)(nil).EnqueueMatching), orderID)
}

// EscalateMatching mocks base method.
func (m *MockMatcher) EscalateMatching(ctx context.Context, orderID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EscalateMatching", ctx, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// EscalateMatching indicates an expected call of EscalateMatching.
func (mr *MockMatcherMockRecorder) EscalateMatching(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EscalateMatching", reflect.TypeOf((*MockMatcher)(nil).EscalateMatching), ctx, orderID)
}

// FindNearestRunners mocks base method.
func (m *MockMatcher) FindNearestRunners(ctx context.Context, lat, lng, radiusKm float64) ([]user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindNearestRunners", ctx, lat, lng, radiusKm)
	ret0, _ := ret[0].([]user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindNearestRunners indicates an expected call of FindNearestRunners.
func (mr *MockMatcherMockRecorder) FindNearestRunners(ctx, lat, lng, radiusKm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindNearestRunners", reflect.TypeOf((*MockMatcher)(nil).FindNearestRunners), ctx, lat, lng, radiusKm)
}

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AcceptOrder mocks base method.
func (m *MockService) AcceptOrder(ctx context.Context, orderID, runnerID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptOrder", ctx, orderID, runnerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AcceptOrder indicates an expected call of AcceptOrder.
func (mr *MockServiceMockRecorder) AcceptOrder(ctx, orderID, runnerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptOrder", reflect.TypeOf((*MockService)(nil).AcceptOrder), ctx, orderID, runnerID)
}

// ApprovePriceAdjustment mocks base method.
func (m *MockService) ApprovePriceAdjustment(ctx context.Context, orderID, requesterID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApprovePriceAdjustment", ctx, orderID, requesterID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApprovePriceAdjustment indicates an expected call of ApprovePriceAdjustment.
func (mr *MockServiceMockRecorder) ApprovePriceAdjustment(ctx, orderID, requesterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApprovePriceAdjustment", reflect.TypeOf((*MockService)(nil).ApprovePriceAdjustment), ctx, orderID, requesterID)
}

// CancelOrder mocks base method.
func (m *MockService) CancelOrder(ctx context.Context, orderID, userID uuid.UUID, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelOrder", ctx, orderID, userID, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelOrder indicates an expected call of CancelOrder.
func (mr *MockServiceMockRecorder) CancelOrder(ctx, orderID, userID, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelOrder", reflect.TypeOf((*MockService)(nil).CancelOrder), ctx, orderID, userID, reason)
}

// CheckProximity mocks base method.
func (m *MockService) CheckProximity(ctx context.Context, lat, lng float64, merchantID *uuid.UUID, serviceCategory string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckProximity", ctx, lat, lng, merchantID, serviceCategory)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckProximity indicates an expected call of CheckProximity.
func (mr *MockServiceMockRecorder) CheckProximity(ctx, lat, lng, merchantID, serviceCategory any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckProximity", reflect.TypeOf((*MockService)(nil).CheckProximity), ctx, lat, lng, merchantID, serviceCategory)
}

// CompleteOrder mocks base method.
func (m *MockService) CompleteOrder(ctx context.Context, orderID, runnerID uuid.UUID, code string, deliveryReader io.Reader, deliveryFilename string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteOrder", ctx, orderID, runnerID, code, deliveryReader, deliveryFilename)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteOrder indicates an expected call of CompleteOrder.
func (mr *MockServiceMockRecorder) CompleteOrder(ctx, orderID, runnerID, code, deliveryReader, deliveryFilename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteOrder", reflect.TypeOf((*MockService)(nil).CompleteOrder), ctx, orderID, runnerID, code, deliveryReader, deliveryFilename)
}

// Create mocks base method.
func (m *MockService) Create(ctx context.Context, requesterID uuid.UUID, req order.CreateOrderRequest) (*order.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, requesterID, req)
	ret0, _ := ret[0].(*order.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockServiceMockRecorder) Create(ctx, requesterID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockService)(nil).Create), ctx, requesterID, req)
}

// DisputeOrder mocks base method.
func (m *MockService) DisputeOrder(ctx context.Context, orderID, requesterID uuid.UUID, reason, proofURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisputeOrder", ctx, orderID, requesterID, reason, proofURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisputeOrder indicates an expected call of DisputeOrder.
func (mr *MockServiceMockRecorder) DisputeOrder(ctx, orderID, requesterID, reason, proofURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisputeOrder", reflect.TypeOf((*MockService)(nil).DisputeOrder), ctx, orderID, requesterID, reason, proofURL)
}

// EstimateFee mocks base method.
func (m *MockService) EstimateFee(ctx context.Context, req order.EstimateFeeRequest) (*order.EstimateFeeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EstimateFee", ctx, req)
	ret0, _ := ret[0].(*order.EstimateFeeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EstimateFee indicates an expected call of EstimateFee.
func (mr *MockServiceMockRecorder) EstimateFee(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstimateFee", reflect.TypeOf((*MockService)(nil).EstimateFee), ctx, req)
}

// ForceCancelOrder mocks base method.
func (m *MockService) ForceCancelOrder(ctx context.Context, orderID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForceCancelOrder", ctx, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ForceCancelOrder indicates an expected call of ForceCancelOrder.
func (mr *MockServiceMockRecorder) ForceCancelOrder(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForceCancelOrder", reflect.TypeOf((*MockService)(nil).ForceCancelOrder), ctx, orderID)
}

// GetAllWithFilters mocks base method.
func (m *MockService) GetAllWithFilters(ctx context.Context, status string, offset, limit int) ([]order.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllWithFilters", ctx, status, offset, limit)
	ret0, _ := ret[0].([]order.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllWithFilters indicates an expected call of GetAllWithFilters.
func (mr *MockServiceMockRecorder) GetAllWithFilters(ctx, status, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllWithFilters", reflect.TypeOf((*MockService)(nil).GetAllWithFilters), ctx, status, offset, limit)
}

// GetAvailableOrders mocks base method.
func (m *MockService) GetAvailableOrders(ctx context.Context, runnerID uuid.UUID) ([]order.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableOrders", ctx, runnerID)
	ret0, _ := ret[0].([]order.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableOrders indicates an expected call of GetAvailableOrders.
func (mr *MockServiceMockRecorder) GetAvailableOrders(ctx, runnerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableOrders", reflect.TypeOf((*MockService)(nil).GetAvailableOrders), ctx, runnerID)
}

// GetByID mocks base method.
func (m *MockService) GetByID(ctx context.Context, id, requestingUserID uuid.UUID, role string) (*order.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id, requestingUserID, role)
	ret0, _ := ret[0].(*order.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockServiceMockRecorder) GetByID(ctx, id, requestingUserID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockService)(nil).GetByID), ctx, id, requestingUserID, role)
}

// GetByRequester mocks base method.
func (m *MockService) GetByRequester(ctx context.Context, requesterID uuid.UUID) ([]order.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByRequester", ctx, requesterID)
	ret0, _ := ret[0].([]order.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByRequester indicates an expected call of GetByRequester.
func (mr *MockServiceMockRecorder) GetByRequester(ctx, requesterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByRequester", reflect.TypeOf((*MockService)(nil).GetByRequester), ctx, requesterID)
}

// GetByRunner mocks base method.
func (m *MockService) GetByRunner(ctx context.Context, runnerID uuid.UUID) ([]order.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByRunner", ctx, runnerID)
	ret0, _ := ret[0].([]order.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByRunner indicates an expected call of GetByRunner.
func (mr *MockServiceMockRecorder) GetByRunner(ctx, runnerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByRunner", reflect.TypeOf((*MockService)(nil).GetByRunner), ctx, runnerID)
}

// GetByUser mocks base method.
func (m *MockService) GetByUser(ctx context.Context, userID uuid.UUID, limit, offset int, startDate, endDate string) ([]order.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUser", ctx, userID, limit, offset, startDate, endDate)
	ret0, _ := ret[0].([]order.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUser indicates an expected call of GetByUser.
func (mr *MockServiceMockRecorder) GetByUser(ctx, userID, limit, offset, startDate, endDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUser", reflect.TypeOf((*MockService)(nil).GetByUser), ctx, userID, limit, offset, startDate, endDate)
}

// GetMerchantOrders mocks base method.
func (m *MockService) GetMerchantOrders(ctx context.Context, ownerID uuid.UUID) ([]order.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMerchantOrders", ctx, ownerID)
	ret0, _ := ret[0].([]order.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMerchantOrders indicates an expected call of GetMerchantOrders.
func (mr *MockServiceMockRecorder) GetMerchantOrders(ctx, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMerchantOrders", reflect.TypeOf((*MockService)(nil).GetMerchantOrders), ctx, ownerID)
}

// GetTrackingState mocks base method.
func (m *MockService) GetTrackingState(ctx context.Context, orderID uuid.UUID) (*order.TrackingState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrackingState", ctx, orderID)
	ret0, _ := ret[0].(*order.TrackingState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrackingState indicates an expected call of GetTrackingState.
func (mr *MockServiceMockRecorder) GetTrackingState(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrackingState", reflect.TypeOf((*MockService)(nil).GetTrackingState), ctx, orderID)
}

// MerchantAcceptOrder mocks base method.
func (m *MockService) MerchantAcceptOrder(ctx context.Context, orderID, ownerID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MerchantAcceptOrder", ctx, orderID, ownerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MerchantAcceptOrder indicates an expected call of MerchantAcceptOrder.
func (mr *MockServiceMockRecorder) MerchantAcceptOrder(ctx, orderID, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MerchantAcceptOrder", reflect.TypeOf((*MockService)(nil).MerchantAcceptOrder), ctx, orderID, ownerID)
}

// MerchantReadyOrder mocks base method.
func (m *MockService) MerchantReadyOrder(ctx context.Context, orderID, ownerID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MerchantReadyOrder", ctx, orderID, ownerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MerchantReadyOrder indicates an expected call of MerchantReadyOrder.
func (mr *MockServiceMockRecorder) MerchantReadyOrder(ctx, orderID, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MerchantReadyOrder", reflect.TypeOf((*MockService)(nil).MerchantReadyOrder), ctx, orderID, ownerID)
}

// PickupOrder mocks base method.
func (m *MockService) PickupOrder(ctx context.Context, orderID, runnerID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PickupOrder", ctx, orderID, runnerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// PickupOrder indicates an expected call of PickupOrder.
func (mr *MockServiceMockRecorder) PickupOrder(ctx, orderID, runnerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PickupOrder", reflect.TypeOf((*MockService)(nil).PickupOrder), ctx, orderID, runnerID)
}

// ReassignOrder mocks base method.
func (m *MockService) ReassignOrder(ctx context.Context, orderID, runnerID uuid.UUID, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReassignOrder", ctx, orderID, runnerID, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReassignOrder indicates an expected call of ReassignOrder.
func (mr *MockServiceMockRecorder) ReassignOrder(ctx, orderID, runnerID, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReassignOrder", reflect.TypeOf((*MockService)(nil).ReassignOrder), ctx, orderID, runnerID, reason)
}

// RefreshQRIS mocks base method.
func (m *MockService) RefreshQRIS(ctx context.Context, orderID, requesterID uuid.UUID) (*order.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshQRIS", ctx, orderID, requesterID)
	ret0, _ := ret[0].(*order.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshQRIS indicates an expected call of RefreshQRIS.
func (mr *MockServiceMockRecorder) RefreshQRIS(ctx, orderID, requesterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshQRIS", reflect.TypeOf((*MockService)(nil).RefreshQRIS), ctx, orderID, requesterID)
}

// RejectPriceAdjustment mocks base method.
func (m *MockService) RejectPriceAdjustment(ctx context.Context, orderID, requesterID uuid.UUID, cancelOrder bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RejectPriceAdjustment", ctx, orderID, requesterID, cancelOrder)
	ret0, _ := ret[0].(error)
	return ret0
}

// RejectPriceAdjustment indicates an expected call of RejectPriceAdjustment.
func (mr *MockServiceMockRecorder) RejectPriceAdjustment(ctx, orderID, requesterID, cancelOrder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RejectPriceAdjustment", reflect.TypeOf((*MockService)(nil).RejectPriceAdjustment), ctx, orderID, requesterID, cancelOrder)
}

// RequestPriceAdjustment mocks base method.
func (m *MockService) RequestPriceAdjustment(ctx context.Context, orderID, runnerID uuid.UUID, adjustedCost float64, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestPriceAdjustment", ctx, orderID, runnerID, adjustedCost, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequestPriceAdjustment indicates an expected call of RequestPriceAdjustment.
func (mr *MockServiceMockRecorder) RequestPriceAdjustment(ctx, orderID, runnerID, adjustedCost, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestPriceAdjustment", reflect.TypeOf((*MockService)(nil).RequestPriceAdjustment), ctx, orderID, runnerID, adjustedCost, reason)
}

// ResolveDispute mocks base method.
func (m *MockService) ResolveDispute(ctx context.Context, orderID uuid.UUID, side string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveDispute", ctx, orderID, side)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResolveDispute indicates an expected call of ResolveDispute.
func (mr *MockServiceMockRecorder) ResolveDispute(ctx, orderID, side any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveDispute", reflect.TypeOf((*MockService)(nil).ResolveDispute), ctx, orderID, side)
}

// RunnerCancelForReassign mocks base method.
func (m *MockService) RunnerCancelForReassign(ctx context.Context, orderID, runnerID uuid.UUID, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunnerCancelForReassign", ctx, orderID, runnerID, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunnerCancelForReassign indicates an expected call of RunnerCancelForReassign.
func (mr *MockServiceMockRecorder) RunnerCancelForReassign(ctx, orderID, runnerID, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunnerCancelForReassign", reflect.TypeOf((*MockService)(nil).RunnerCancelForReassign), ctx, orderID, runnerID, reason)
}

// SetFCMDispatcher mocks base method.
func (m *MockService) SetFCMDispatcher(d order.FCMDispatcher) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetFCMDispatcher", d)
}

// SetFCMDispatcher indicates an expected call of SetFCMDispatcher.
func (mr *MockServiceMockRecorder) SetFCMDispatcher(d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFCMDispatcher", reflect.TypeOf((*MockService)(nil).SetFCMDispatcher), d)
}

// SetPoolBroadcaster mocks base method.
func (m *MockService) SetPoolBroadcaster(b order.PoolBroadcaster) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetPoolBroadcaster", b)
}

// SetPoolBroadcaster indicates an expected call of SetPoolBroadcaster.
func (mr *MockServiceMockRecorder) SetPoolBroadcaster(b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPoolBroadcaster", reflect.TypeOf((*MockService)(nil).SetPoolBroadcaster), b)
}

// SetPromotionService mocks base method.
func (m *MockService) SetPromotionService(ps order.PromotionService) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetPromotionService", ps)
}

// SetPromotionService indicates an expected call of SetPromotionService.
func (mr *MockServiceMockRecorder) SetPromotionService(ps any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPromotionService", reflect.TypeOf((*MockService)(nil).SetPromotionService), ps)
}

// StartBackgroundCleanup mocks base method.
func (m *MockService) StartBackgroundCleanup(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartBackgroundCleanup", ctx)
}

// StartBackgroundCleanup indicates an expected call of StartBackgroundCleanup.
func (mr *MockServiceMockRecorder) StartBackgroundCleanup(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartBackgroundCleanup", reflect.TypeOf((*MockService)(nil).StartBackgroundCleanup), ctx)
}

// StartPaymentWorkerPool mocks base method.
func (m *MockService) StartPaymentWorkerPool(ctx context.Context, numWorkers int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartPaymentWorkerPool", ctx, numWorkers)
}

// StartPaymentWorkerPool indicates an expected call of StartPaymentWorkerPool.
func (mr *MockServiceMockRecorder) StartPaymentWorkerPool(ctx, numWorkers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartPaymentWorkerPool", reflect.TypeOf((*MockService)(nil).StartPaymentWorkerPool), ctx, numWorkers)
}

// SubmitPurchaseReceipt mocks base method.
func (m *MockService) SubmitPurchaseReceipt(ctx context.Context, orderID, runnerID uuid.UUID, receiptReader io.Reader, receiptFilename string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitPurchaseReceipt", ctx, orderID, runnerID, receiptReader, receiptFilename)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubmitPurchaseReceipt indicates an expected call of SubmitPurchaseReceipt.
func (mr *MockServiceMockRecorder) SubmitPurchaseReceipt(ctx, orderID, runnerID, receiptReader, receiptFilename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitPurchaseReceipt", reflect.TypeOf((*MockService)(nil).SubmitPurchaseReceipt), ctx, orderID, runnerID, receiptReader, receiptFilename)
}

// UpdatePaymentStatus mocks base method.
func (m *MockService) UpdatePaymentStatus(ctx context.Context, orderID uuid.UUID, paymentStatus string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePaymentStatus", ctx, orderID, paymentStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePaymentStatus indicates an expected call of UpdatePaymentStatus.
func (mr *MockServiceMockRecorder) UpdatePaymentStatus(ctx, orderID, paymentStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePaymentStatus", reflect.TypeOf((*MockService)(nil).UpdatePaymentStatus), ctx, orderID, paymentStatus)
}

// MockPoolBroadcaster is a mock of PoolBroadcaster interface.
type MockPoolBroadcaster struct {
	ctrl     *gomock.Controller
	recorder *MockPoolBroadcasterMockRecorder
	isgomock struct{}
}

// MockPoolBroadcasterMockRecorder is the mock recorder for MockPoolBroadcaster.
type MockPoolBroadcasterMockRecorder struct {
	mock *MockPoolBroadcaster
}

// NewMockPoolBroadcaster creates a new mock instance.
func NewMockPoolBroadcaster(ctrl *gomock.Controller) *MockPoolBroadcaster {
	mock := &MockPoolBroadcaster{ctrl: ctrl}
	mock.recorder = &MockPoolBroadcasterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPoolBroadcaster) EXPECT() *MockPoolBroadcasterMockRecorder {
	return m.recorder
}

// BroadcastCancelled mocks base method.
func (m *MockPoolBroadcaster) BroadcastCancelled(orderID, reason string, pickupLat, pickupLng float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BroadcastCancelled", orderID, reason, pickupLat, pickupLng)
}

// BroadcastCancelled indicates an expected call of BroadcastCancelled.
func (mr *MockPoolBroadcasterMockRecorder) BroadcastCancelled(orderID, reason, pickupLat, pickupLng any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastCancelled", reflect.TypeOf((*MockPoolBroadcaster)(nil).BroadcastCancelled), orderID, reason, pickupLat, pickupLng)
}

// BroadcastClaimed mocks base method.
func (m *MockPoolBroadcaster) BroadcastClaimed(orderID, runnerID string, pickupLat, pickupLng float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BroadcastClaimed", orderID, runnerID, pickupLat, pickupLng)
}

// BroadcastClaimed indicates an expected call of BroadcastClaimed.
func (mr *MockPoolBroadcasterMockRecorder) BroadcastClaimed(orderID, runnerID, pickupLat, pickupLng any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastClaimed", reflect.TypeOf((*MockPoolBroadcaster)(nil).BroadcastClaimed), orderID, runnerID, pickupLat, pickupLng)
}

// BroadcastMerchantEvent mocks base method.
func (m *MockPoolBroadcaster) BroadcastMerchantEvent(merchantID, eventType string, arg2 *order.Order) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BroadcastMerchantEvent", merchantID, eventType, arg2)
}

// BroadcastMerchantEvent indicates an expected call of BroadcastMerchantEvent.
func (mr *MockPoolBroadcasterMockRecorder) BroadcastMerchantEvent(merchantID, eventType, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastMerchantEvent", reflect.TypeOf((*MockPoolBroadcaster)(nil).BroadcastMerchantEvent), merchantID, eventType, arg2)
}

// BroadcastNewOrder mocks base method.
func (m *MockPoolBroadcaster) BroadcastNewOrder(arg0 *order.Order) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BroadcastNewOrder", arg0)
}

// BroadcastNewOrder indicates an expected call of BroadcastNewOrder.
func (mr *MockPoolBroadcasterMockRecorder) BroadcastNewOrder(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastNewOrder", reflect.TypeOf((*MockPoolBroadcaster)(nil).BroadcastNewOrder), arg0)
}

// BroadcastOrderStatus mocks base method.
func (m *MockPoolBroadcaster) BroadcastOrderStatus(orderID, status, eventType string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BroadcastOrderStatus", orderID, status, eventType)
}

// BroadcastOrderStatus indicates an expected call of BroadcastOrderStatus.
func (mr *MockPoolBroadcasterMockRecorder) BroadcastOrderStatus(orderID, status, eventType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastOrderStatus", reflect.TypeOf((*MockPoolBroadcaster)(nil).BroadcastOrderStatus), orderID, status, eventType)
}

// MockFCMDispatcher is a mock of FCMDispatcher interface.
type MockFCMDispatcher struct {
	ctrl     *gomock.Controller
	recorder *MockFCMDispatcherMockRecorder
	isgomock struct{}
}

// MockFCMDispatcherMockRecorder is the mock recorder for MockFCMDispatcher.
type MockFCMDispatcherMockRecorder struct {
	mock *MockFCMDispatcher
}

// NewMockFCMDispatcher creates a new mock instance.
func NewMockFCMDispatcher(ctrl *gomock.Controller) *MockFCMDispatcher {
	mock := &MockFCMDispatcher{ctrl: ctrl}
	mock.recorder = &MockFCMDispatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFCMDispatcher) EXPECT() *MockFCMDispatcherMockRecorder {
	return m.recorder
}

// Enqueue mocks base method.
func (m *MockFCMDispatcher) Enqueue(ctx context.Context, job notification.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enqueue", ctx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockFCMDispatcherMockRecorder) Enqueue(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockFCMDispatcher)(nil).Enqueue), ctx, job)
}

// MockPromotionService is a mock of PromotionService interface.
type MockPromotionService struct {
	ctrl     *gomock.Controller
	recorder *MockPromotionServiceMockRecorder
	isgomock struct{}
}

// MockPromotionServiceMockRecorder is the mock recorder for MockPromotionService.
type MockPromotionServiceMockRecorder struct {
	mock *MockPromotionService
}

// NewMockPromotionService creates a new mock instance.
func NewMockPromotionService(ctrl *gomock.Controller) *MockPromotionService {
	mock := &MockPromotionService{ctrl: ctrl}
	mock.recorder = &MockPromotionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPromotionService) EXPECT() *MockPromotionServiceMockRecorder {
	return m.recorder
}

// ApplyUsage mocks base method.
func (m *MockPromotionService) ApplyUsage(ctx context.Context, tx bun.IDB, promoID, orderID, userID uuid.UUID, merchantID *uuid.UUID, discountAmount, originalAmount float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyUsage", ctx, tx, promoID, orderID, userID, merchantID, discountAmount, originalAmount)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyUsage indicates an expected call of ApplyUsage.
func (mr *MockPromotionServiceMockRecorder) ApplyUsage(ctx, tx, promoID, orderID, userID, merchantID, discountAmount, originalAmount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyUsage", reflect.TypeOf((*MockPromotionService)(nil).ApplyUsage), ctx, tx, promoID, orderID, userID, merchantID, discountAmount, originalAmount)
}

// ReleaseUsage mocks base method.
func (m *MockPromotionService) ReleaseUsage(ctx context.Context, tx bun.IDB, orderID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseUsage", ctx, tx, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseUsage indicates an expected call of ReleaseUsage.
func (mr *MockPromotionServiceMockRecorder) ReleaseUsage(ctx, tx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseUsage", reflect.TypeOf((*MockPromotionService)(nil).ReleaseUsage), ctx, tx, orderID)
}

// ValidateAndReserveForOrder mocks base method.
func (m *MockPromotionService) ValidateAndReserveForOrder(ctx context.Context, tx bun.IDB, code string, merchantID *uuid.UUID, userID uuid.UUID, itemTotal, deliveryTotal, total float64) (any, float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAndReserveForOrder", ctx, tx, code, merchantID, userID, itemTotal, deliveryTotal, total)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(float64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ValidateAndReserveForOrder indicates an expected call of ValidateAndReserveForOrder.
func (mr *MockPromotionServiceMockRecorder) ValidateAndReserveForOrder(ctx, tx, code, merchantID, userID, itemTotal, deliveryTotal, total any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAndReserveForOrder", reflect.TypeOf((*MockPromotionService)(nil).ValidateAndReserveForOrder), ctx, tx, code, merchantID, userID, itemTotal, deliveryTotal, total)
}
