// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mocks/repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	promotion "github.com/codecoffy/nitip-core/internal/domain/promotion"
	uuid "github.com/google/uuid"
	bun "github.com/uptrace/bun"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CountUserCompletedOrders mocks base method.
func (m *MockRepository) CountUserCompletedOrders(ctx context.Context, userID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUserCompletedOrders", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUserCompletedOrders indicates an expected call of CountUserCompletedOrders.
func (mr *MockRepositoryMockRecorder) CountUserCompletedOrders(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUserCompletedOrders", reflect.TypeOf((*MockRepository)(nil).CountUserCompletedOrders), ctx, userID)
}

// CountUserUsage mocks base method.
func (m *MockRepository) CountUserUsage(ctx context.Context, promotionID, userID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUserUsage", ctx, promotionID, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUserUsage indicates an expected call of CountUserUsage.
func (mr *MockRepositoryMockRecorder) CountUserUsage(ctx, promotionID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUserUsage", reflect.TypeOf((*MockRepository)(nil).CountUserUsage), ctx, promotionID, userID)
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, db bun.IDB, p *promotion.Promotion) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, db, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, db, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, db, p)
}

// Delete mocks base method.
func (m *MockRepository) Delete(ctx context.Context, db bun.IDB, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, db, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder) Delete(ctx, db, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), ctx, db, id)
}

// DeleteUsageByOrderID mocks base method.
func (m *MockRepository) DeleteUsageByOrderID(ctx context.Context, tx bun.IDB, orderID uuid.UUID) (*promotion.PromotionUsage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUsageByOrderID", ctx, tx, orderID)
	ret0, _ := ret[0].(*promotion.PromotionUsage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteUsageByOrderID indicates an expected call of DeleteUsageByOrderID.
func (mr *MockRepositoryMockRecorder) DeleteUsageByOrderID(ctx, tx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUsageByOrderID", reflect.TypeOf((*MockRepository)(nil).DeleteUsageByOrderID), ctx, tx, orderID)
}

// FindActiveByMerchant mocks base method.
func (m *MockRepository) FindActiveByMerchant(ctx context.Context, merchantID *uuid.UUID) ([]promotion.Promotion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActiveByMerchant", ctx, merchantID)
	ret0, _ := ret[0].([]promotion.Promotion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActiveByMerchant indicates an expected call of FindActiveByMerchant.
func (mr *MockRepositoryMockRecorder) FindActiveByMerchant(ctx, merchantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActiveByMerchant", reflect.TypeOf((*MockRepository)(nil).FindActiveByMerchant), ctx, merchantID)
}

// FindAutoActiveForMerchantForUpdate mocks base method.
func (m *MockRepository) FindAutoActiveForMerchantForUpdate(ctx context.Context, tx bun.IDB, merchantID *uuid.UUID) (*promotion.Promotion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAutoActiveForMerchantForUpdate", ctx, tx, merchantID)
	ret0, _ := ret[0].(*promotion.Promotion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAutoActiveForMerchantForUpdate indicates an expected call of FindAutoActiveForMerchantForUpdate.
func (mr *MockRepositoryMockRecorder) FindAutoActiveForMerchantForUpdate(ctx, tx, merchantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAutoActiveForMerchantForUpdate", reflect.TypeOf((*MockRepository)(nil).FindAutoActiveForMerchantForUpdate), ctx, tx, merchantID)
}

// FindByCodeForUpdate mocks base method.
func (m *MockRepository) FindByCodeForUpdate(ctx context.Context, tx bun.IDB, code string) (*promotion.Promotion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCodeForUpdate", ctx, tx, code)
	ret0, _ := ret[0].(*promotion.Promotion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCodeForUpdate indicates an expected call of FindByCodeForUpdate.
func (mr *MockRepositoryMockRecorder) FindByCodeForUpdate(ctx, tx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCodeForUpdate", reflect.TypeOf((*MockRepository)(nil).FindByCodeForUpdate), ctx, tx, code)
}

// FindByCodeInsensitive mocks base method.
func (m *MockRepository) FindByCodeInsensitive(ctx context.Context, code string) (*promotion.Promotion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCodeInsensitive", ctx, code)
	ret0, _ := ret[0].(*promotion.Promotion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCodeInsensitive indicates an expected call of FindByCodeInsensitive.
func (mr *MockRepositoryMockRecorder) FindByCodeInsensitive(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCodeInsensitive", reflect.TypeOf((*MockRepository)(nil).FindByCodeInsensitive), ctx, code)
}

// FindByID mocks base method.
func (m *MockRepository) FindByID(ctx context.Context, id uuid.UUID) (*promotion.Promotion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*promotion.Promotion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRepository)(nil).FindByID), ctx, id)
}

// FindByIDForUpdate mocks base method.
func (m *MockRepository) FindByIDForUpdate(ctx context.Context, tx bun.IDB, id uuid.UUID) (*promotion.Promotion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIDForUpdate", ctx, tx, id)
	ret0, _ := ret[0].(*promotion.Promotion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIDForUpdate indicates an expected call of FindByIDForUpdate.
func (mr *MockRepositoryMockRecorder) FindByIDForUpdate(ctx, tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIDForUpdate", reflect.TypeOf((*MockRepository)(nil).FindByIDForUpdate), ctx, tx, id)
}

// FindUsageByOrderID mocks base method.
func (m *MockRepository) FindUsageByOrderID(ctx context.Context, orderID uuid.UUID) (*promotion.PromotionUsage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUsageByOrderID", ctx, orderID)
	ret0, _ := ret[0].(*promotion.PromotionUsage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUsageByOrderID indicates an expected call of FindUsageByOrderID.
func (mr *MockRepositoryMockRecorder) FindUsageByOrderID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUsageByOrderID", reflect.TypeOf((*MockRepository)(nil).FindUsageByOrderID), ctx, orderID)
}

// GetAvgOrderValue mocks base method.
func (m *MockRepository) GetAvgOrderValue(ctx context.Context, merchantID *uuid.UUID) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvgOrderValue", ctx, merchantID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvgOrderValue indicates an expected call of GetAvgOrderValue.
func (mr *MockRepositoryMockRecorder) GetAvgOrderValue(ctx, merchantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvgOrderValue", reflect.TypeOf((*MockRepository)(nil).GetAvgOrderValue), ctx, merchantID)
}

// GetSettlement mocks base method.
func (m *MockRepository) GetSettlement(ctx context.Context, merchantID *uuid.UUID, from, to *time.Time) ([]promotion.SettlementItem, float64, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSettlement", ctx, merchantID, from, to)
	ret0, _ := ret[0].([]promotion.SettlementItem)
	ret1, _ := ret[1].(float64)
	ret2, _ := ret[2].(int)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetSettlement indicates an expected call of GetSettlement.
func (mr *MockRepositoryMockRecorder) GetSettlement(ctx, merchantID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSettlement", reflect.TypeOf((*MockRepository)(nil).GetSettlement), ctx, merchantID, from, to)
}

// InsertUsage mocks base method.
func (m *MockRepository) InsertUsage(ctx context.Context, tx bun.IDB, u *promotion.PromotionUsage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertUsage", ctx, tx, u)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertUsage indicates an expected call of InsertUsage.
func (mr *MockRepositoryMockRecorder) InsertUsage(ctx, tx, u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertUsage", reflect.TypeOf((*MockRepository)(nil).InsertUsage), ctx, tx, u)
}

// List mocks base method.
func (m *MockRepository) List(ctx context.Context, merchantID *uuid.UUID, isActive *bool, search string, firstPurchaseOnly *bool, offset, limit int) ([]promotion.Promotion, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, merchantID, isActive, search, firstPurchaseOnly, offset, limit)
	ret0, _ := ret[0].([]promotion.Promotion)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockRepositoryMockRecorder) List(ctx, merchantID, isActive, search, firstPurchaseOnly, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepository)(nil).List), ctx, merchantID, isActive, search, firstPurchaseOnly, offset, limit)
}

// ListUsages mocks base method.
func (m *MockRepository) ListUsages(ctx context.Context, promotionID uuid.UUID, offset, limit int) ([]promotion.PromotionUsage, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsages", ctx, promotionID, offset, limit)
	ret0, _ := ret[0].([]promotion.PromotionUsage)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListUsages indicates an expected call of ListUsages.
func (mr *MockRepositoryMockRecorder) ListUsages(ctx, promotionID, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsages", reflect.TypeOf((*MockRepository)(nil).ListUsages), ctx, promotionID, offset, limit)
}

// Update mocks base method.
func (m *MockRepository) Update(ctx context.Context, db bun.IDB, p *promotion.Promotion) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, db, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder) Update(ctx, db, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), ctx, db, p)
}

// UpdateMerchantNameBatch mocks base method.
func (m *MockRepository) UpdateMerchantNameBatch(ctx context.Context, promotions []promotion.Promotion) ([]promotion.Promotion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMerchantNameBatch", ctx, promotions)
	ret0, _ := ret[0].([]promotion.Promotion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMerchantNameBatch indicates an expected call of UpdateMerchantNameBatch.
func (mr *MockRepositoryMockRecorder) UpdateMerchantNameBatch(ctx, promotions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMerchantNameBatch", reflect.TypeOf((*MockRepository)(nil).UpdateMerchantNameBatch), ctx, promotions)
}
