// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	promotion "github.com/codecoffy/nitip-core/internal/domain/promotion"
	uuid "github.com/google/uuid"
	bun "github.com/uptrace/bun"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// ApplyUsage mocks base method.
func (m *MockService) ApplyUsage(ctx context.Context, tx bun.IDB, promoID, orderID, userID uuid.UUID, merchantID *uuid.UUID, discountAmount, originalAmount float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyUsage", ctx, tx, promoID, orderID, userID, merchantID, discountAmount, originalAmount)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyUsage indicates an expected call of ApplyUsage.
func (mr *MockServiceMockRecorder) ApplyUsage(ctx, tx, promoID, orderID, userID, merchantID, discountAmount, originalAmount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyUsage", reflect.TypeOf((*MockService)(nil).ApplyUsage), ctx, tx, promoID, orderID, userID, merchantID, discountAmount, originalAmount)
}

// CalculatePreview mocks base method.
func (m *MockService) CalculatePreview(ctx context.Context, req promotion.CalculatePreviewRequest) (*promotion.CalculatePreviewResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculatePreview", ctx, req)
	ret0, _ := ret[0].(*promotion.CalculatePreviewResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CalculatePreview indicates an expected call of CalculatePreview.
func (mr *MockServiceMockRecorder) CalculatePreview(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculatePreview", reflect.TypeOf((*MockService)(nil).CalculatePreview), ctx, req)
}

// CreatePromotion mocks base method.
func (m *MockService) CreatePromotion(ctx context.Context, adminID uuid.UUID, req promotion.CreatePromotionRequest, ip, ua string) (*promotion.Promotion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePromotion", ctx, adminID, req, ip, ua)
	ret0, _ := ret[0].(*promotion.Promotion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePromotion indicates an expected call of CreatePromotion.
func (mr *MockServiceMockRecorder) CreatePromotion(ctx, adminID, req, ip, ua any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePromotion", reflect.TypeOf((*MockService)(nil).CreatePromotion), ctx, adminID, req, ip, ua)
}

// DeletePromotion mocks base method.
func (m *MockService) DeletePromotion(ctx context.Context, adminID, id uuid.UUID, req promotion.DeletePromotionRequest, ip, ua string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePromotion", ctx, adminID, id, req, ip, ua)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePromotion indicates an expected call of DeletePromotion.
func (mr *MockServiceMockRecorder) DeletePromotion(ctx, adminID, id, req, ip, ua any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePromotion", reflect.TypeOf((*MockService)(nil).DeletePromotion), ctx, adminID, id, req, ip, ua)
}

// GetActiveForMerchant mocks base method.
func (m *MockService) GetActiveForMerchant(ctx context.Context, merchantID *uuid.UUID) ([]promotion.Promotion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveForMerchant", ctx, merchantID)
	ret0, _ := ret[0].([]promotion.Promotion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveForMerchant indicates an expected call of GetActiveForMerchant.
func (mr *MockServiceMockRecorder) GetActiveForMerchant(ctx, merchantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveForMerchant", reflect.TypeOf((*MockService)(nil).GetActiveForMerchant), ctx, merchantID)
}

// GetByID mocks base method.
func (m *MockService) GetByID(ctx context.Context, id uuid.UUID) (*promotion.Promotion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*promotion.Promotion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockServiceMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockService)(nil).GetByID), ctx, id)
}

// GetSettlement mocks base method.
func (m *MockService) GetSettlement(ctx context.Context, merchantID *uuid.UUID, from, to *time.Time) (*promotion.SettlementResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSettlement", ctx, merchantID, from, to)
	ret0, _ := ret[0].(*promotion.SettlementResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSettlement indicates an expected call of GetSettlement.
func (mr *MockServiceMockRecorder) GetSettlement(ctx, merchantID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSettlement", reflect.TypeOf((*MockService)(nil).GetSettlement), ctx, merchantID, from, to)
}

// List mocks base method.
func (m *MockService) List(ctx context.Context, merchantID *uuid.UUID, isActive *bool, search string, firstPurchaseOnly *bool, offset, limit int) ([]promotion.Promotion, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, merchantID, isActive, search, firstPurchaseOnly, offset, limit)
	ret0, _ := ret[0].([]promotion.Promotion)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockServiceMockRecorder) List(ctx, merchantID, isActive, search, firstPurchaseOnly, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockService)(nil).List), ctx, merchantID, isActive, search, firstPurchaseOnly, offset, limit)
}

// ListUsages mocks base method.
func (m *MockService) ListUsages(ctx context.Context, promotionID uuid.UUID, offset, limit int) ([]promotion.PromotionUsage, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsages", ctx, promotionID, offset, limit)
	ret0, _ := ret[0].([]promotion.PromotionUsage)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListUsages indicates an expected call of ListUsages.
func (mr *MockServiceMockRecorder) ListUsages(ctx, promotionID, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsages", reflect.TypeOf((*MockService)(nil).ListUsages), ctx, promotionID, offset, limit)
}

// ReleaseUsage mocks base method.
func (m *MockService) ReleaseUsage(ctx context.Context, tx bun.IDB, orderID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseUsage", ctx, tx, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseUsage indicates an expected call of ReleaseUsage.
func (mr *MockServiceMockRecorder) ReleaseUsage(ctx, tx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseUsage", reflect.TypeOf((*MockService)(nil).ReleaseUsage), ctx, tx, orderID)
}

// UpdatePromotion mocks base method.
func (m *MockService) UpdatePromotion(ctx context.Context, adminID, id uuid.UUID, req promotion.UpdatePromotionRequest, ip, ua string) (*promotion.Promotion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePromotion", ctx, adminID, id, req, ip, ua)
	ret0, _ := ret[0].(*promotion.Promotion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePromotion indicates an expected call of UpdatePromotion.
func (mr *MockServiceMockRecorder) UpdatePromotion(ctx, adminID, id, req, ip, ua any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePromotion", reflect.TypeOf((*MockService)(nil).UpdatePromotion), ctx, adminID, id, req, ip, ua)
}

// ValidateAndReserveForOrder mocks base method.
func (m *MockService) ValidateAndReserveForOrder(ctx context.Context, tx bun.IDB, code string, merchantID *uuid.UUID, userID uuid.UUID, itemTotal, deliveryTotal, total float64) (any, float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAndReserveForOrder", ctx, tx, code, merchantID, userID, itemTotal, deliveryTotal, total)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(float64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ValidateAndReserveForOrder indicates an expected call of ValidateAndReserveForOrder.
func (mr *MockServiceMockRecorder) ValidateAndReserveForOrder(ctx, tx, code, merchantID, userID, itemTotal, deliveryTotal, total any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAndReserveForOrder", reflect.TypeOf((*MockService)(nil).ValidateAndReserveForOrder), ctx, tx, code, merchantID, userID, itemTotal, deliveryTotal, total)
}

// ValidateForCheckout mocks base method.
func (m *MockService) ValidateForCheckout(ctx context.Context, req promotion.ValidatePromotionRequest, userID *uuid.UUID) (*promotion.ValidatePromotionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateForCheckout", ctx, req, userID)
	ret0, _ := ret[0].(*promotion.ValidatePromotionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateForCheckout indicates an expected call of ValidateForCheckout.
func (mr *MockServiceMockRecorder) ValidateForCheckout(ctx, req, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateForCheckout", reflect.TypeOf((*MockService)(nil).ValidateForCheckout), ctx, req, userID)
}
