// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	chat "github.com/codecoffy/nitip-core/internal/domain/chat"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetHistory mocks base method.
func (m *MockService) GetHistory(ctx context.Context, orderID, userID uuid.UUID, limit int) ([]chat.ChatMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistory", ctx, orderID, userID, limit)
	ret0, _ := ret[0].([]chat.ChatMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistory indicates an expected call of GetHistory.
func (mr *MockServiceMockRecorder) GetHistory(ctx, orderID, userID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistory", reflect.TypeOf((*MockService)(nil).GetHistory), ctx, orderID, userID, limit)
}

// RegisterClient mocks base method.
func (m *MockService) RegisterClient(orderID string, client *chat.Client) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterClient", orderID, client)
}

// RegisterClient indicates an expected call of RegisterClient.
func (mr *MockServiceMockRecorder) RegisterClient(orderID, client any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterClient", reflect.TypeOf((*MockService)(nil).RegisterClient), orderID, client)
}

// SendMessage mocks base method.
func (m *MockService) SendMessage(ctx context.Context, orderID, senderID uuid.UUID, content, msgType string) (*chat.ChatMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, orderID, senderID, content, msgType)
	ret0, _ := ret[0].(*chat.ChatMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockServiceMockRecorder) SendMessage(ctx, orderID, senderID, content, msgType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockService)(nil).SendMessage), ctx, orderID, senderID, content, msgType)
}

// UnregisterClient mocks base method.
func (m *MockService) UnregisterClient(orderID string, userID uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UnregisterClient", orderID, userID)
}

// UnregisterClient indicates an expected call of UnregisterClient.
func (mr *MockServiceMockRecorder) UnregisterClient(orderID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnregisterClient", reflect.TypeOf((*MockService)(nil).UnregisterClient), orderID, userID)
}

// UploadImage mocks base method.
func (m *MockService) UploadImage(ctx context.Context, orderID, userID uuid.UUID, filename string, content io.Reader) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadImage", ctx, orderID, userID, filename, content)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadImage indicates an expected call of UploadImage.
func (mr *MockServiceMockRecorder) UploadImage(ctx, orderID, userID, filename, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadImage", reflect.TypeOf((*MockService)(nil).UploadImage), ctx, orderID, userID, filename, content)
}
