// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	systemconfig "github.com/codecoffy/nitip-core/internal/domain/config"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// GetAll provides a mock function with given fields: ctx
func (_m *Service) GetAll(ctx context.Context) ([]systemconfig.Config, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []systemconfig.Config
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]systemconfig.Config, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []systemconfig.Config); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]systemconfig.Config)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetValue provides a mock function with given fields: ctx, key, defaultValue
func (_m *Service) GetValue(ctx context.Context, key string, defaultValue string) string {
	ret := _m.Called(ctx, key, defaultValue)

	if len(ret) == 0 {
		panic("no return value specified for GetValue")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, key, defaultValue)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// SetValue provides a mock function with given fields: ctx, key, value, description
func (_m *Service) SetValue(ctx context.Context, key string, value string, description string) error {
	ret := _m.Called(ctx, key, value, description)

	if len(ret) == 0 {
		panic("no return value specified for SetValue")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, key, value, description)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
