// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	store "github.com/codecoffy/nitip-core/internal/domain/store"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreateStore mocks base method.
func (m *MockService) CreateStore(ctx context.Context, req store.CreateStoreRequest) (*store.Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStore", ctx, req)
	ret0, _ := ret[0].(*store.Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStore indicates an expected call of CreateStore.
func (mr *MockServiceMockRecorder) CreateStore(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStore", reflect.TypeOf((*MockService)(nil).CreateStore), ctx, req)
}

// CreateStoresBatch mocks base method.
func (m *MockService) CreateStoresBatch(ctx context.Context, reqs []store.CreateStoreRequest) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStoresBatch", ctx, reqs)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStoresBatch indicates an expected call of CreateStoresBatch.
func (mr *MockServiceMockRecorder) CreateStoresBatch(ctx, reqs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStoresBatch", reflect.TypeOf((*MockService)(nil).CreateStoresBatch), ctx, reqs)
}

// DeleteStore mocks base method.
func (m *MockService) DeleteStore(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStore", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStore indicates an expected call of DeleteStore.
func (mr *MockServiceMockRecorder) DeleteStore(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStore", reflect.TypeOf((*MockService)(nil).DeleteStore), ctx, id)
}

// GetActiveStores mocks base method.
func (m *MockService) GetActiveStores(ctx context.Context) ([]store.Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveStores", ctx)
	ret0, _ := ret[0].([]store.Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveStores indicates an expected call of GetActiveStores.
func (mr *MockServiceMockRecorder) GetActiveStores(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveStores", reflect.TypeOf((*MockService)(nil).GetActiveStores), ctx)
}

// GetAllStores mocks base method.
func (m *MockService) GetAllStores(ctx context.Context) ([]store.Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllStores", ctx)
	ret0, _ := ret[0].([]store.Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllStores indicates an expected call of GetAllStores.
func (mr *MockServiceMockRecorder) GetAllStores(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllStores", reflect.TypeOf((*MockService)(nil).GetAllStores), ctx)
}

// GetNearbyStores mocks base method.
func (m *MockService) GetNearbyStores(ctx context.Context, lat, lng, radiusKm float64, limit int) ([]store.Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNearbyStores", ctx, lat, lng, radiusKm, limit)
	ret0, _ := ret[0].([]store.Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNearbyStores indicates an expected call of GetNearbyStores.
func (mr *MockServiceMockRecorder) GetNearbyStores(ctx, lat, lng, radiusKm, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNearbyStores", reflect.TypeOf((*MockService)(nil).GetNearbyStores), ctx, lat, lng, radiusKm, limit)
}

// UpdateStore mocks base method.
func (m *MockService) UpdateStore(ctx context.Context, id uuid.UUID, req store.UpdateStoreRequest) (*store.Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStore", ctx, id, req)
	ret0, _ := ret[0].(*store.Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStore indicates an expected call of UpdateStore.
func (mr *MockServiceMockRecorder) UpdateStore(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStore", reflect.TypeOf((*MockService)(nil).UpdateStore), ctx, id, req)
}
