// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	kyc "github.com/codecoffy/nitip-core/internal/domain/kyc"
	notification "github.com/codecoffy/nitip-core/internal/notification"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetStatus mocks base method.
func (m *MockService) GetStatus(ctx context.Context, userID uuid.UUID) (*kyc.KycSubmission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus", ctx, userID)
	ret0, _ := ret[0].(*kyc.KycSubmission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockServiceMockRecorder) GetStatus(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockService)(nil).GetStatus), ctx, userID)
}

// ListPending mocks base method.
func (m *MockService) ListPending(ctx context.Context, offset, limit int) ([]kyc.KycSubmission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPending", ctx, offset, limit)
	ret0, _ := ret[0].([]kyc.KycSubmission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPending indicates an expected call of ListPending.
func (mr *MockServiceMockRecorder) ListPending(ctx, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPending", reflect.TypeOf((*MockService)(nil).ListPending), ctx, offset, limit)
}

// Review mocks base method.
func (m *MockService) Review(ctx context.Context, kycID, actorID uuid.UUID, approved bool, note string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Review", ctx, kycID, actorID, approved, note)
	ret0, _ := ret[0].(error)
	return ret0
}

// Review indicates an expected call of Review.
func (mr *MockServiceMockRecorder) Review(ctx, kycID, actorID, approved, note any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Review", reflect.TypeOf((*MockService)(nil).Review), ctx, kycID, actorID, approved, note)
}

// Submit mocks base method.
func (m *MockService) Submit(ctx context.Context, userID uuid.UUID, req kyc.SubmitKycRequest) (*kyc.KycSubmission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Submit", ctx, userID, req)
	ret0, _ := ret[0].(*kyc.KycSubmission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Submit indicates an expected call of Submit.
func (mr *MockServiceMockRecorder) Submit(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Submit", reflect.TypeOf((*MockService)(nil).Submit), ctx, userID, req)
}

// MockdispatcherIface is a mock of dispatcherIface interface.
type MockdispatcherIface struct {
	ctrl     *gomock.Controller
	recorder *MockdispatcherIfaceMockRecorder
	isgomock struct{}
}

// MockdispatcherIfaceMockRecorder is the mock recorder for MockdispatcherIface.
type MockdispatcherIfaceMockRecorder struct {
	mock *MockdispatcherIface
}

// NewMockdispatcherIface creates a new mock instance.
func NewMockdispatcherIface(ctrl *gomock.Controller) *MockdispatcherIface {
	mock := &MockdispatcherIface{ctrl: ctrl}
	mock.recorder = &MockdispatcherIfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdispatcherIface) EXPECT() *MockdispatcherIfaceMockRecorder {
	return m.recorder
}

// Enqueue mocks base method.
func (m *MockdispatcherIface) Enqueue(ctx context.Context, job notification.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enqueue", ctx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockdispatcherIfaceMockRecorder) Enqueue(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockdispatcherIface)(nil).Enqueue), ctx, job)
}
