// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	bun "github.com/uptrace/bun"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"

	wallet "github.com/codecoffy/nitip-core/internal/domain/wallet"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CreateTransaction provides a mock function with given fields: ctx, db, wtx
func (_m *Repository) CreateTransaction(ctx context.Context, db bun.IDB, wtx *wallet.WalletTransaction) error {
	ret := _m.Called(ctx, db, wtx)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, *wallet.WalletTransaction) error); ok {
		r0 = rf(ctx, db, wtx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateWallet provides a mock function with given fields: ctx, db, _a2
func (_m *Repository) CreateWallet(ctx context.Context, db bun.IDB, _a2 *wallet.Wallet) error {
	ret := _m.Called(ctx, db, _a2)

	if len(ret) == 0 {
		panic("no return value specified for CreateWallet")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, *wallet.Wallet) error); ok {
		r0 = rf(ctx, db, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetActiveWithdrawalChannels provides a mock function with given fields: ctx, db
func (_m *Repository) GetActiveWithdrawalChannels(ctx context.Context, db bun.IDB) ([]wallet.WithdrawalChannel, error) {
	ret := _m.Called(ctx, db)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveWithdrawalChannels")
	}

	var r0 []wallet.WithdrawalChannel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB) ([]wallet.WithdrawalChannel, error)); ok {
		return rf(ctx, db)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB) []wallet.WithdrawalChannel); ok {
		r0 = rf(ctx, db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]wallet.WithdrawalChannel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bun.IDB) error); ok {
		r1 = rf(ctx, db)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrCreateWallet provides a mock function with given fields: ctx, db, userID
func (_m *Repository) GetOrCreateWallet(ctx context.Context, db bun.IDB, userID uuid.UUID) (*wallet.Wallet, error) {
	ret := _m.Called(ctx, db, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreateWallet")
	}

	var r0 *wallet.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, uuid.UUID) (*wallet.Wallet, error)); ok {
		return rf(ctx, db, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, uuid.UUID) *wallet.Wallet); ok {
		r0 = rf(ctx, db, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*wallet.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bun.IDB, uuid.UUID) error); ok {
		r1 = rf(ctx, db, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPendingWithdrawals provides a mock function with given fields: ctx, db, limit, offset
func (_m *Repository) GetPendingWithdrawals(ctx context.Context, db bun.IDB, limit int, offset int) ([]wallet.WalletTransaction, error) {
	ret := _m.Called(ctx, db, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingWithdrawals")
	}

	var r0 []wallet.WalletTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, int, int) ([]wallet.WalletTransaction, error)); ok {
		return rf(ctx, db, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, int, int) []wallet.WalletTransaction); ok {
		r0 = rf(ctx, db, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]wallet.WalletTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bun.IDB, int, int) error); ok {
		r1 = rf(ctx, db, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSystemBalanceSummary provides a mock function with given fields: ctx
func (_m *Repository) GetSystemBalanceSummary(ctx context.Context) (*wallet.SystemBalanceSummary, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSystemBalanceSummary")
	}

	var r0 *wallet.SystemBalanceSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*wallet.SystemBalanceSummary, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *wallet.SystemBalanceSummary); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*wallet.SystemBalanceSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransactionByID provides a mock function with given fields: ctx, db, id
func (_m *Repository) GetTransactionByID(ctx context.Context, db bun.IDB, id uuid.UUID) (*wallet.WalletTransaction, error) {
	ret := _m.Called(ctx, db, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionByID")
	}

	var r0 *wallet.WalletTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, uuid.UUID) (*wallet.WalletTransaction, error)); ok {
		return rf(ctx, db, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, uuid.UUID) *wallet.WalletTransaction); ok {
		r0 = rf(ctx, db, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*wallet.WalletTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bun.IDB, uuid.UUID) error); ok {
		r1 = rf(ctx, db, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransactionByReference provides a mock function with given fields: ctx, db, reference
func (_m *Repository) GetTransactionByReference(ctx context.Context, db bun.IDB, reference string) (*wallet.WalletTransaction, error) {
	ret := _m.Called(ctx, db, reference)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionByReference")
	}

	var r0 *wallet.WalletTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, string) (*wallet.WalletTransaction, error)); ok {
		return rf(ctx, db, reference)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, string) *wallet.WalletTransaction); ok {
		r0 = rf(ctx, db, reference)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*wallet.WalletTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bun.IDB, string) error); ok {
		r1 = rf(ctx, db, reference)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransactionsByWalletID provides a mock function with given fields: ctx, db, walletID, limit, offset
func (_m *Repository) GetTransactionsByWalletID(ctx context.Context, db bun.IDB, walletID uuid.UUID, limit int, offset int) ([]wallet.WalletTransaction, error) {
	ret := _m.Called(ctx, db, walletID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionsByWalletID")
	}

	var r0 []wallet.WalletTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, uuid.UUID, int, int) ([]wallet.WalletTransaction, error)); ok {
		return rf(ctx, db, walletID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, uuid.UUID, int, int) []wallet.WalletTransaction); ok {
		r0 = rf(ctx, db, walletID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]wallet.WalletTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bun.IDB, uuid.UUID, int, int) error); ok {
		r1 = rf(ctx, db, walletID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWalletByUserID provides a mock function with given fields: ctx, db, userID
func (_m *Repository) GetWalletByUserID(ctx context.Context, db bun.IDB, userID uuid.UUID) (*wallet.Wallet, error) {
	ret := _m.Called(ctx, db, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetWalletByUserID")
	}

	var r0 *wallet.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, uuid.UUID) (*wallet.Wallet, error)); ok {
		return rf(ctx, db, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, uuid.UUID) *wallet.Wallet); ok {
		r0 = rf(ctx, db, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*wallet.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bun.IDB, uuid.UUID) error); ok {
		r1 = rf(ctx, db, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWithdrawalChannelByID provides a mock function with given fields: ctx, db, id
func (_m *Repository) GetWithdrawalChannelByID(ctx context.Context, db bun.IDB, id uuid.UUID) (*wallet.WithdrawalChannel, error) {
	ret := _m.Called(ctx, db, id)

	if len(ret) == 0 {
		panic("no return value specified for GetWithdrawalChannelByID")
	}

	var r0 *wallet.WithdrawalChannel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, uuid.UUID) (*wallet.WithdrawalChannel, error)); ok {
		return rf(ctx, db, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, uuid.UUID) *wallet.WithdrawalChannel); ok {
		r0 = rf(ctx, db, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*wallet.WithdrawalChannel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bun.IDB, uuid.UUID) error); ok {
		r1 = rf(ctx, db, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RunInTx provides a mock function with given fields: ctx, fn
func (_m *Repository) RunInTx(ctx context.Context, fn func(context.Context, bun.Tx) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for RunInTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context, bun.Tx) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SumTodayWithdrawals provides a mock function with given fields: ctx, db, walletID
func (_m *Repository) SumTodayWithdrawals(ctx context.Context, db bun.IDB, walletID uuid.UUID) (float64, error) {
	ret := _m.Called(ctx, db, walletID)

	if len(ret) == 0 {
		panic("no return value specified for SumTodayWithdrawals")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, uuid.UUID) (float64, error)); ok {
		return rf(ctx, db, walletID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, uuid.UUID) float64); ok {
		r0 = rf(ctx, db, walletID)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, bun.IDB, uuid.UUID) error); ok {
		r1 = rf(ctx, db, walletID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTransactionStatus provides a mock function with given fields: ctx, db, id, status
func (_m *Repository) UpdateTransactionStatus(ctx context.Context, db bun.IDB, id uuid.UUID, status wallet.TransactionStatus) error {
	ret := _m.Called(ctx, db, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTransactionStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, uuid.UUID, wallet.TransactionStatus) error); ok {
		r0 = rf(ctx, db, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateWalletBalance provides a mock function with given fields: ctx, db, walletID, amount
func (_m *Repository) UpdateWalletBalance(ctx context.Context, db bun.IDB, walletID uuid.UUID, amount float64) error {
	ret := _m.Called(ctx, db, walletID, amount)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWalletBalance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, uuid.UUID, float64) error); ok {
		r0 = rf(ctx, db, walletID, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
