// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mocks/repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	wallet "github.com/codecoffy/nitip-core/internal/domain/wallet"
	uuid "github.com/google/uuid"
	bun "github.com/uptrace/bun"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateTransaction mocks base method.
func (m *MockRepository) CreateTransaction(ctx context.Context, db bun.IDB, wtx *wallet.WalletTransaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransaction", ctx, db, wtx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTransaction indicates an expected call of CreateTransaction.
func (mr *MockRepositoryMockRecorder) CreateTransaction(ctx, db, wtx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransaction", reflect.TypeOf((*MockRepository)(nil).CreateTransaction), ctx, db, wtx)
}

// CreateWallet mocks base method.
func (m *MockRepository) CreateWallet(ctx context.Context, db bun.IDB, arg2 *wallet.Wallet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWallet", ctx, db, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWallet indicates an expected call of CreateWallet.
func (mr *MockRepositoryMockRecorder) CreateWallet(ctx, db, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWallet", reflect.TypeOf((*MockRepository)(nil).CreateWallet), ctx, db, arg2)
}

// GetActiveWithdrawalChannels mocks base method.
func (m *MockRepository) GetActiveWithdrawalChannels(ctx context.Context, db bun.IDB) ([]wallet.WithdrawalChannel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveWithdrawalChannels", ctx, db)
	ret0, _ := ret[0].([]wallet.WithdrawalChannel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveWithdrawalChannels indicates an expected call of GetActiveWithdrawalChannels.
func (mr *MockRepositoryMockRecorder) GetActiveWithdrawalChannels(ctx, db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveWithdrawalChannels", reflect.TypeOf((*MockRepository)(nil).GetActiveWithdrawalChannels), ctx, db)
}

// GetOrCreateWallet mocks base method.
func (m *MockRepository) GetOrCreateWallet(ctx context.Context, db bun.IDB, userID uuid.UUID) (*wallet.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreateWallet", ctx, db, userID)
	ret0, _ := ret[0].(*wallet.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreateWallet indicates an expected call of GetOrCreateWallet.
func (mr *MockRepositoryMockRecorder) GetOrCreateWallet(ctx, db, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreateWallet", reflect.TypeOf((*MockRepository)(nil).GetOrCreateWallet), ctx, db, userID)
}

// GetPendingWithdrawals mocks base method.
func (m *MockRepository) GetPendingWithdrawals(ctx context.Context, db bun.IDB, limit, offset int) ([]wallet.WalletTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingWithdrawals", ctx, db, limit, offset)
	ret0, _ := ret[0].([]wallet.WalletTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingWithdrawals indicates an expected call of GetPendingWithdrawals.
func (mr *MockRepositoryMockRecorder) GetPendingWithdrawals(ctx, db, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingWithdrawals", reflect.TypeOf((*MockRepository)(nil).GetPendingWithdrawals), ctx, db, limit, offset)
}

// GetSystemBalanceSummary mocks base method.
func (m *MockRepository) GetSystemBalanceSummary(ctx context.Context) (*wallet.SystemBalanceSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSystemBalanceSummary", ctx)
	ret0, _ := ret[0].(*wallet.SystemBalanceSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSystemBalanceSummary indicates an expected call of GetSystemBalanceSummary.
func (mr *MockRepositoryMockRecorder) GetSystemBalanceSummary(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSystemBalanceSummary", reflect.TypeOf((*MockRepository)(nil).GetSystemBalanceSummary), ctx)
}

// GetTransactionByID mocks base method.
func (m *MockRepository) GetTransactionByID(ctx context.Context, db bun.IDB, id uuid.UUID) (*wallet.WalletTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionByID", ctx, db, id)
	ret0, _ := ret[0].(*wallet.WalletTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionByID indicates an expected call of GetTransactionByID.
func (mr *MockRepositoryMockRecorder) GetTransactionByID(ctx, db, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionByID", reflect.TypeOf((*MockRepository)(nil).GetTransactionByID), ctx, db, id)
}

// GetTransactionByReference mocks base method.
func (m *MockRepository) GetTransactionByReference(ctx context.Context, db bun.IDB, reference string) (*wallet.WalletTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionByReference", ctx, db, reference)
	ret0, _ := ret[0].(*wallet.WalletTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionByReference indicates an expected call of GetTransactionByReference.
func (mr *MockRepositoryMockRecorder) GetTransactionByReference(ctx, db, reference any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionByReference", reflect.TypeOf((*MockRepository)(nil).GetTransactionByReference), ctx, db, reference)
}

// GetTransactionsByWalletID mocks base method.
func (m *MockRepository) GetTransactionsByWalletID(ctx context.Context, db bun.IDB, walletID uuid.UUID, limit, offset int) ([]wallet.WalletTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionsByWalletID", ctx, db, walletID, limit, offset)
	ret0, _ := ret[0].([]wallet.WalletTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionsByWalletID indicates an expected call of GetTransactionsByWalletID.
func (mr *MockRepositoryMockRecorder) GetTransactionsByWalletID(ctx, db, walletID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionsByWalletID", reflect.TypeOf((*MockRepository)(nil).GetTransactionsByWalletID), ctx, db, walletID, limit, offset)
}

// GetWalletByUserID mocks base method.
func (m *MockRepository) GetWalletByUserID(ctx context.Context, db bun.IDB, userID uuid.UUID) (*wallet.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWalletByUserID", ctx, db, userID)
	ret0, _ := ret[0].(*wallet.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWalletByUserID indicates an expected call of GetWalletByUserID.
func (mr *MockRepositoryMockRecorder) GetWalletByUserID(ctx, db, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWalletByUserID", reflect.TypeOf((*MockRepository)(nil).GetWalletByUserID), ctx, db, userID)
}

// GetWithdrawalChannelByID mocks base method.
func (m *MockRepository) GetWithdrawalChannelByID(ctx context.Context, db bun.IDB, id uuid.UUID) (*wallet.WithdrawalChannel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithdrawalChannelByID", ctx, db, id)
	ret0, _ := ret[0].(*wallet.WithdrawalChannel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithdrawalChannelByID indicates an expected call of GetWithdrawalChannelByID.
func (mr *MockRepositoryMockRecorder) GetWithdrawalChannelByID(ctx, db, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithdrawalChannelByID", reflect.TypeOf((*MockRepository)(nil).GetWithdrawalChannelByID), ctx, db, id)
}

// RunInTx mocks base method.
func (m *MockRepository) RunInTx(ctx context.Context, fn func(context.Context, bun.Tx) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunInTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunInTx indicates an expected call of RunInTx.
func (mr *MockRepositoryMockRecorder) RunInTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunInTx", reflect.TypeOf((*MockRepository)(nil).RunInTx), ctx, fn)
}

// SumTodayWithdrawals mocks base method.
func (m *MockRepository) SumTodayWithdrawals(ctx context.Context, db bun.IDB, walletID uuid.UUID) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SumTodayWithdrawals", ctx, db, walletID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SumTodayWithdrawals indicates an expected call of SumTodayWithdrawals.
func (mr *MockRepositoryMockRecorder) SumTodayWithdrawals(ctx, db, walletID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SumTodayWithdrawals", reflect.TypeOf((*MockRepository)(nil).SumTodayWithdrawals), ctx, db, walletID)
}

// UpdateTransactionStatus mocks base method.
func (m *MockRepository) UpdateTransactionStatus(ctx context.Context, db bun.IDB, id uuid.UUID, status wallet.TransactionStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTransactionStatus", ctx, db, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTransactionStatus indicates an expected call of UpdateTransactionStatus.
func (mr *MockRepositoryMockRecorder) UpdateTransactionStatus(ctx, db, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTransactionStatus", reflect.TypeOf((*MockRepository)(nil).UpdateTransactionStatus), ctx, db, id, status)
}

// UpdateWalletBalance mocks base method.
func (m *MockRepository) UpdateWalletBalance(ctx context.Context, db bun.IDB, walletID uuid.UUID, amount float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWalletBalance", ctx, db, walletID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWalletBalance indicates an expected call of UpdateWalletBalance.
func (mr *MockRepositoryMockRecorder) UpdateWalletBalance(ctx, db, walletID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWalletBalance", reflect.TypeOf((*MockRepository)(nil).UpdateWalletBalance), ctx, db, walletID, amount)
}
