// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	bun "github.com/uptrace/bun"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"

	wallet "github.com/codecoffy/nitip-core/internal/domain/wallet"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// ApproveWithdrawal provides a mock function with given fields: ctx, txID, actorID
func (_m *Service) ApproveWithdrawal(ctx context.Context, txID uuid.UUID, actorID uuid.UUID) error {
	ret := _m.Called(ctx, txID, actorID)

	if len(ret) == 0 {
		panic("no return value specified for ApproveWithdrawal")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, txID, actorID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeductCODPlatformFee provides a mock function with given fields: ctx, db, runnerID, orderID, platformFee
func (_m *Service) DeductCODPlatformFee(ctx context.Context, db bun.IDB, runnerID uuid.UUID, orderID uuid.UUID, platformFee float64) error {
	ret := _m.Called(ctx, db, runnerID, orderID, platformFee)

	if len(ret) == 0 {
		panic("no return value specified for DeductCODPlatformFee")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, uuid.UUID, uuid.UUID, float64) error); ok {
		r0 = rf(ctx, db, runnerID, orderID, platformFee)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FinalizeTopUp provides a mock function with given fields: ctx, reference, notificationID
func (_m *Service) FinalizeTopUp(ctx context.Context, reference string, notificationID string) (*wallet.WalletTransaction, error) {
	ret := _m.Called(ctx, reference, notificationID)

	if len(ret) == 0 {
		panic("no return value specified for FinalizeTopUp")
	}

	var r0 *wallet.WalletTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*wallet.WalletTransaction, error)); ok {
		return rf(ctx, reference, notificationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *wallet.WalletTransaction); ok {
		r0 = rf(ctx, reference, notificationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*wallet.WalletTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, reference, notificationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FinalizeWithdrawal provides a mock function with given fields: ctx, txID, status
func (_m *Service) FinalizeWithdrawal(ctx context.Context, txID uuid.UUID, status wallet.TransactionStatus) error {
	ret := _m.Called(ctx, txID, status)

	if len(ret) == 0 {
		panic("no return value specified for FinalizeWithdrawal")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, wallet.TransactionStatus) error); ok {
		r0 = rf(ctx, txID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBalance provides a mock function with given fields: ctx, userID
func (_m *Service) GetBalance(ctx context.Context, userID uuid.UUID) (*wallet.Wallet, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 *wallet.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*wallet.Wallet, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *wallet.Wallet); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*wallet.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPendingWithdrawals provides a mock function with given fields: ctx, limit, offset
func (_m *Service) GetPendingWithdrawals(ctx context.Context, limit int, offset int) ([]wallet.WalletTransaction, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingWithdrawals")
	}

	var r0 []wallet.WalletTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]wallet.WalletTransaction, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []wallet.WalletTransaction); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]wallet.WalletTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSystemBalanceSummary provides a mock function with given fields: ctx
func (_m *Service) GetSystemBalanceSummary(ctx context.Context) (*wallet.SystemBalanceSummary, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSystemBalanceSummary")
	}

	var r0 *wallet.SystemBalanceSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*wallet.SystemBalanceSummary, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *wallet.SystemBalanceSummary); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*wallet.SystemBalanceSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransactionStatus provides a mock function with given fields: ctx, reference
func (_m *Service) GetTransactionStatus(ctx context.Context, reference string) (*wallet.WalletTransaction, error) {
	ret := _m.Called(ctx, reference)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionStatus")
	}

	var r0 *wallet.WalletTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*wallet.WalletTransaction, error)); ok {
		return rf(ctx, reference)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *wallet.WalletTransaction); ok {
		r0 = rf(ctx, reference)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*wallet.WalletTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, reference)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransactionByID provides a mock function with given fields: ctx, id
func (_m *Service) GetTransactionByID(ctx context.Context, id uuid.UUID) (*wallet.WalletTransaction, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionByID")
	}

	var r0 *wallet.WalletTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*wallet.WalletTransaction, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *wallet.WalletTransaction); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*wallet.WalletTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransactions provides a mock function with given fields: ctx, userID, limit, offset
func (_m *Service) GetTransactions(ctx context.Context, userID uuid.UUID, limit int, offset int) ([]wallet.WalletTransaction, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactions")
	}

	var r0 []wallet.WalletTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]wallet.WalletTransaction, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []wallet.WalletTransaction); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]wallet.WalletTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) error); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWithdrawalChannels provides a mock function with given fields: ctx
func (_m *Service) GetWithdrawalChannels(ctx context.Context) ([]wallet.WithdrawalChannel, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetWithdrawalChannels")
	}

	var r0 []wallet.WithdrawalChannel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]wallet.WithdrawalChannel, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []wallet.WithdrawalChannel); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]wallet.WithdrawalChannel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HoldEscrow provides a mock function with given fields: ctx, db, userID, orderID, amount
func (_m *Service) HoldEscrow(ctx context.Context, db bun.IDB, userID uuid.UUID, orderID uuid.UUID, amount float64) error {
	ret := _m.Called(ctx, db, userID, orderID, amount)

	if len(ret) == 0 {
		panic("no return value specified for HoldEscrow")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, uuid.UUID, uuid.UUID, float64) error); ok {
		r0 = rf(ctx, db, userID, orderID, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InitiateTopUp provides a mock function with given fields: ctx, userID, amount
func (_m *Service) InitiateTopUp(ctx context.Context, userID uuid.UUID, amount float64) (*wallet.WalletTransaction, error) {
	ret := _m.Called(ctx, userID, amount)

	if len(ret) == 0 {
		panic("no return value specified for InitiateTopUp")
	}

	var r0 *wallet.WalletTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, float64) (*wallet.WalletTransaction, error)); ok {
		return rf(ctx, userID, amount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, float64) *wallet.WalletTransaction); ok {
		r0 = rf(ctx, userID, amount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*wallet.WalletTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, float64) error); ok {
		r1 = rf(ctx, userID, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InquiryAccount provides a mock function with given fields: ctx, req
func (_m *Service) InquiryAccount(ctx context.Context, req wallet.InquiryAccountRequest) (*wallet.InquiryAccountResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for InquiryAccount")
	}

	var r0 *wallet.InquiryAccountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, wallet.InquiryAccountRequest) (*wallet.InquiryAccountResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, wallet.InquiryAccountRequest) *wallet.InquiryAccountResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*wallet.InquiryAccountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, wallet.InquiryAccountRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PartialReleaseEscrow provides a mock function with given fields: ctx, db, runnerID, requesterID, orderID, runnerAmount, refundAmount
func (_m *Service) PartialReleaseEscrow(ctx context.Context, db bun.IDB, runnerID uuid.UUID, requesterID uuid.UUID, orderID uuid.UUID, runnerAmount float64, refundAmount float64) error {
	ret := _m.Called(ctx, db, runnerID, requesterID, orderID, runnerAmount, refundAmount)

	if len(ret) == 0 {
		panic("no return value specified for PartialReleaseEscrow")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, uuid.UUID, uuid.UUID, uuid.UUID, float64, float64) error); ok {
		r0 = rf(ctx, db, runnerID, requesterID, orderID, runnerAmount, refundAmount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RecoverPendingWithdrawals provides a mock function with given fields: ctx
func (_m *Service) RecoverPendingWithdrawals(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RecoverPendingWithdrawals")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RefundEscrow provides a mock function with given fields: ctx, db, requesterID, orderID, amount
func (_m *Service) RefundEscrow(ctx context.Context, db bun.IDB, requesterID uuid.UUID, orderID uuid.UUID, amount float64) error {
	ret := _m.Called(ctx, db, requesterID, orderID, amount)

	if len(ret) == 0 {
		panic("no return value specified for RefundEscrow")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, uuid.UUID, uuid.UUID, float64) error); ok {
		r0 = rf(ctx, db, requesterID, orderID, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReleaseEscrow provides a mock function with given fields: ctx, db, runnerID, orderID, amount, platformFee
func (_m *Service) ReleaseEscrow(ctx context.Context, db bun.IDB, runnerID uuid.UUID, orderID uuid.UUID, amount float64, platformFee float64) error {
	ret := _m.Called(ctx, db, runnerID, orderID, amount, platformFee)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseEscrow")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, uuid.UUID, uuid.UUID, float64, float64) error); ok {
		r0 = rf(ctx, db, runnerID, orderID, amount, platformFee)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReleaseEscrowWithRefund provides a mock function with given fields: ctx, db, runnerID, requesterID, orderID, runnerAmount, platformFee, refundAmount
func (_m *Service) ReleaseEscrowWithRefund(ctx context.Context, db bun.IDB, runnerID uuid.UUID, requesterID uuid.UUID, orderID uuid.UUID, runnerAmount float64, platformFee float64, refundAmount float64) error {
	ret := _m.Called(ctx, db, runnerID, requesterID, orderID, runnerAmount, platformFee, refundAmount)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseEscrowWithRefund")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, uuid.UUID, uuid.UUID, uuid.UUID, float64, float64, float64) error); ok {
		r0 = rf(ctx, db, runnerID, requesterID, orderID, runnerAmount, platformFee, refundAmount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReleaseMerchantEscrow provides a mock function with given fields: ctx, db, runnerID, requesterID, merchantOwnerID, orderID, foodAmount, runnerAmount, platformFee, refundAmount
func (_m *Service) ReleaseMerchantEscrow(ctx context.Context, db bun.IDB, runnerID uuid.UUID, requesterID uuid.UUID, merchantOwnerID uuid.UUID, orderID uuid.UUID, foodAmount float64, runnerAmount float64, platformFee float64, refundAmount float64) error {
	ret := _m.Called(ctx, db, runnerID, requesterID, merchantOwnerID, orderID, foodAmount, runnerAmount, platformFee, refundAmount)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseMerchantEscrow")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, uuid.UUID, uuid.UUID, uuid.UUID, uuid.UUID, float64, float64, float64, float64) error); ok {
		r0 = rf(ctx, db, runnerID, requesterID, merchantOwnerID, orderID, foodAmount, runnerAmount, platformFee, refundAmount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RequestWithdrawal provides a mock function with given fields: ctx, userID, amount, channelID, pin, destMetadata
func (_m *Service) RequestWithdrawal(ctx context.Context, userID uuid.UUID, amount float64, channelID *uuid.UUID, pin string, destMetadata map[string]interface{}) (*wallet.WalletTransaction, error) {
	ret := _m.Called(ctx, userID, amount, channelID, pin, destMetadata)

	if len(ret) == 0 {
		panic("no return value specified for RequestWithdrawal")
	}

	var r0 *wallet.WalletTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, float64, *uuid.UUID, string, map[string]interface{}) (*wallet.WalletTransaction, error)); ok {
		return rf(ctx, userID, amount, channelID, pin, destMetadata)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, float64, *uuid.UUID, string, map[string]interface{}) *wallet.WalletTransaction); ok {
		r0 = rf(ctx, userID, amount, channelID, pin, destMetadata)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*wallet.WalletTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, float64, *uuid.UUID, string, map[string]interface{}) error); ok {
		r1 = rf(ctx, userID, amount, channelID, pin, destMetadata)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TopUp provides a mock function with given fields: ctx, userID, amount, reference
func (_m *Service) TopUp(ctx context.Context, userID uuid.UUID, amount float64, reference string) (*wallet.WalletTransaction, error) {
	ret := _m.Called(ctx, userID, amount, reference)

	if len(ret) == 0 {
		panic("no return value specified for TopUp")
	}

	var r0 *wallet.WalletTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, float64, string) (*wallet.WalletTransaction, error)); ok {
		return rf(ctx, userID, amount, reference)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, float64, string) *wallet.WalletTransaction); ok {
		r0 = rf(ctx, userID, amount, reference)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*wallet.WalletTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, float64, string) error); ok {
		r1 = rf(ctx, userID, amount, reference)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
