// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	wallet "github.com/codecoffy/nitip-core/internal/domain/wallet"
	notification "github.com/codecoffy/nitip-core/internal/notification"
	uuid "github.com/google/uuid"
	bun "github.com/uptrace/bun"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// ApproveWithdrawal mocks base method.
func (m *MockService) ApproveWithdrawal(ctx context.Context, txID, actorID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveWithdrawal", ctx, txID, actorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApproveWithdrawal indicates an expected call of ApproveWithdrawal.
func (mr *MockServiceMockRecorder) ApproveWithdrawal(ctx, txID, actorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveWithdrawal", reflect.TypeOf((*MockService)(nil).ApproveWithdrawal), ctx, txID, actorID)
}

// DeductCODPlatformFee mocks base method.
func (m *MockService) DeductCODPlatformFee(ctx context.Context, db bun.IDB, runnerID, orderID uuid.UUID, platformFee float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeductCODPlatformFee", ctx, db, runnerID, orderID, platformFee)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeductCODPlatformFee indicates an expected call of DeductCODPlatformFee.
func (mr *MockServiceMockRecorder) DeductCODPlatformFee(ctx, db, runnerID, orderID, platformFee any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeductCODPlatformFee", reflect.TypeOf((*MockService)(nil).DeductCODPlatformFee), ctx, db, runnerID, orderID, platformFee)
}

// FinalizeTopUp mocks base method.
func (m *MockService) FinalizeTopUp(ctx context.Context, reference, notificationID string) (*wallet.WalletTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinalizeTopUp", ctx, reference, notificationID)
	ret0, _ := ret[0].(*wallet.WalletTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FinalizeTopUp indicates an expected call of FinalizeTopUp.
func (mr *MockServiceMockRecorder) FinalizeTopUp(ctx, reference, notificationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinalizeTopUp", reflect.TypeOf((*MockService)(nil).FinalizeTopUp), ctx, reference, notificationID)
}

// FinalizeWithdrawal mocks base method.
func (m *MockService) FinalizeWithdrawal(ctx context.Context, txID uuid.UUID, status wallet.TransactionStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinalizeWithdrawal", ctx, txID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// FinalizeWithdrawal indicates an expected call of FinalizeWithdrawal.
func (mr *MockServiceMockRecorder) FinalizeWithdrawal(ctx, txID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinalizeWithdrawal", reflect.TypeOf((*MockService)(nil).FinalizeWithdrawal), ctx, txID, status)
}

// GetBalance mocks base method.
func (m *MockService) GetBalance(ctx context.Context, userID uuid.UUID) (*wallet.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, userID)
	ret0, _ := ret[0].(*wallet.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockServiceMockRecorder) GetBalance(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockService)(nil).GetBalance), ctx, userID)
}

// GetPendingWithdrawals mocks base method.
func (m *MockService) GetPendingWithdrawals(ctx context.Context, limit, offset int) ([]wallet.WalletTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingWithdrawals", ctx, limit, offset)
	ret0, _ := ret[0].([]wallet.WalletTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingWithdrawals indicates an expected call of GetPendingWithdrawals.
func (mr *MockServiceMockRecorder) GetPendingWithdrawals(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingWithdrawals", reflect.TypeOf((*MockService)(nil).GetPendingWithdrawals), ctx, limit, offset)
}

// GetSystemBalanceSummary mocks base method.
func (m *MockService) GetSystemBalanceSummary(ctx context.Context) (*wallet.SystemBalanceSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSystemBalanceSummary", ctx)
	ret0, _ := ret[0].(*wallet.SystemBalanceSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSystemBalanceSummary indicates an expected call of GetSystemBalanceSummary.
func (mr *MockServiceMockRecorder) GetSystemBalanceSummary(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSystemBalanceSummary", reflect.TypeOf((*MockService)(nil).GetSystemBalanceSummary), ctx)
}

// GetTransactionByID mocks base method.
func (m *MockService) GetTransactionByID(ctx context.Context, id uuid.UUID) (*wallet.WalletTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionByID", ctx, id)
	ret0, _ := ret[0].(*wallet.WalletTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionByID indicates an expected call of GetTransactionByID.
func (mr *MockServiceMockRecorder) GetTransactionByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionByID", reflect.TypeOf((*MockService)(nil).GetTransactionByID), ctx, id)
}

// GetTransactionStatus mocks base method.
func (m *MockService) GetTransactionStatus(ctx context.Context, reference string) (*wallet.WalletTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionStatus", ctx, reference)
	ret0, _ := ret[0].(*wallet.WalletTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionStatus indicates an expected call of GetTransactionStatus.
func (mr *MockServiceMockRecorder) GetTransactionStatus(ctx, reference any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionStatus", reflect.TypeOf((*MockService)(nil).GetTransactionStatus), ctx, reference)
}

// GetTransactions mocks base method.
func (m *MockService) GetTransactions(ctx context.Context, userID uuid.UUID, limit, offset int) ([]wallet.WalletTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactions", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]wallet.WalletTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactions indicates an expected call of GetTransactions.
func (mr *MockServiceMockRecorder) GetTransactions(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactions", reflect.TypeOf((*MockService)(nil).GetTransactions), ctx, userID, limit, offset)
}

// GetWithdrawalChannels mocks base method.
func (m *MockService) GetWithdrawalChannels(ctx context.Context) ([]wallet.WithdrawalChannel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithdrawalChannels", ctx)
	ret0, _ := ret[0].([]wallet.WithdrawalChannel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithdrawalChannels indicates an expected call of GetWithdrawalChannels.
func (mr *MockServiceMockRecorder) GetWithdrawalChannels(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithdrawalChannels", reflect.TypeOf((*MockService)(nil).GetWithdrawalChannels), ctx)
}

// HoldEscrow mocks base method.
func (m *MockService) HoldEscrow(ctx context.Context, db bun.IDB, userID, orderID uuid.UUID, amount float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HoldEscrow", ctx, db, userID, orderID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// HoldEscrow indicates an expected call of HoldEscrow.
func (mr *MockServiceMockRecorder) HoldEscrow(ctx, db, userID, orderID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HoldEscrow", reflect.TypeOf((*MockService)(nil).HoldEscrow), ctx, db, userID, orderID, amount)
}

// HoldLiability mocks base method.
func (m *MockService) HoldLiability(ctx context.Context, db bun.IDB, runnerID, orderID uuid.UUID, amount float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HoldLiability", ctx, db, runnerID, orderID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// HoldLiability indicates an expected call of HoldLiability.
func (mr *MockServiceMockRecorder) HoldLiability(ctx, db, runnerID, orderID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HoldLiability", reflect.TypeOf((*MockService)(nil).HoldLiability), ctx, db, runnerID, orderID, amount)
}

// InitiateTopUp mocks base method.
func (m *MockService) InitiateTopUp(ctx context.Context, userID uuid.UUID, amount float64) (*wallet.WalletTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitiateTopUp", ctx, userID, amount)
	ret0, _ := ret[0].(*wallet.WalletTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitiateTopUp indicates an expected call of InitiateTopUp.
func (mr *MockServiceMockRecorder) InitiateTopUp(ctx, userID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitiateTopUp", reflect.TypeOf((*MockService)(nil).InitiateTopUp), ctx, userID, amount)
}

// InquiryAccount mocks base method.
func (m *MockService) InquiryAccount(ctx context.Context, req wallet.InquiryAccountRequest) (*wallet.InquiryAccountResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InquiryAccount", ctx, req)
	ret0, _ := ret[0].(*wallet.InquiryAccountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InquiryAccount indicates an expected call of InquiryAccount.
func (mr *MockServiceMockRecorder) InquiryAccount(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InquiryAccount", reflect.TypeOf((*MockService)(nil).InquiryAccount), ctx, req)
}

// PartialReleaseEscrow mocks base method.
func (m *MockService) PartialReleaseEscrow(ctx context.Context, db bun.IDB, runnerID, requesterID, orderID uuid.UUID, runnerAmount, refundAmount float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PartialReleaseEscrow", ctx, db, runnerID, requesterID, orderID, runnerAmount, refundAmount)
	ret0, _ := ret[0].(error)
	return ret0
}

// PartialReleaseEscrow indicates an expected call of PartialReleaseEscrow.
func (mr *MockServiceMockRecorder) PartialReleaseEscrow(ctx, db, runnerID, requesterID, orderID, runnerAmount, refundAmount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PartialReleaseEscrow", reflect.TypeOf((*MockService)(nil).PartialReleaseEscrow), ctx, db, runnerID, requesterID, orderID, runnerAmount, refundAmount)
}

// RecoverPendingWithdrawals mocks base method.
func (m *MockService) RecoverPendingWithdrawals(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecoverPendingWithdrawals", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecoverPendingWithdrawals indicates an expected call of RecoverPendingWithdrawals.
func (mr *MockServiceMockRecorder) RecoverPendingWithdrawals(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecoverPendingWithdrawals", reflect.TypeOf((*MockService)(nil).RecoverPendingWithdrawals), ctx)
}

// RefundEscrow mocks base method.
func (m *MockService) RefundEscrow(ctx context.Context, db bun.IDB, requesterID, orderID uuid.UUID, amount float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefundEscrow", ctx, db, requesterID, orderID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefundEscrow indicates an expected call of RefundEscrow.
func (mr *MockServiceMockRecorder) RefundEscrow(ctx, db, requesterID, orderID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefundEscrow", reflect.TypeOf((*MockService)(nil).RefundEscrow), ctx, db, requesterID, orderID, amount)
}

// ReleaseEscrow mocks base method.
func (m *MockService) ReleaseEscrow(ctx context.Context, db bun.IDB, runnerID, orderID uuid.UUID, amount, platformFee float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseEscrow", ctx, db, runnerID, orderID, amount, platformFee)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseEscrow indicates an expected call of ReleaseEscrow.
func (mr *MockServiceMockRecorder) ReleaseEscrow(ctx, db, runnerID, orderID, amount, platformFee any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseEscrow", reflect.TypeOf((*MockService)(nil).ReleaseEscrow), ctx, db, runnerID, orderID, amount, platformFee)
}

// ReleaseEscrowWithRefund mocks base method.
func (m *MockService) ReleaseEscrowWithRefund(ctx context.Context, db bun.IDB, runnerID, requesterID, orderID uuid.UUID, runnerAmount, platformFee, refundAmount float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseEscrowWithRefund", ctx, db, runnerID, requesterID, orderID, runnerAmount, platformFee, refundAmount)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseEscrowWithRefund indicates an expected call of ReleaseEscrowWithRefund.
func (mr *MockServiceMockRecorder) ReleaseEscrowWithRefund(ctx, db, runnerID, requesterID, orderID, runnerAmount, platformFee, refundAmount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseEscrowWithRefund", reflect.TypeOf((*MockService)(nil).ReleaseEscrowWithRefund), ctx, db, runnerID, requesterID, orderID, runnerAmount, platformFee, refundAmount)
}

// ReleaseLiability mocks base method.
func (m *MockService) ReleaseLiability(ctx context.Context, db bun.IDB, runnerID, orderID uuid.UUID, amount float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseLiability", ctx, db, runnerID, orderID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseLiability indicates an expected call of ReleaseLiability.
func (mr *MockServiceMockRecorder) ReleaseLiability(ctx, db, runnerID, orderID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseLiability", reflect.TypeOf((*MockService)(nil).ReleaseLiability), ctx, db, runnerID, orderID, amount)
}

// ReleaseMerchantEscrow mocks base method.
func (m *MockService) ReleaseMerchantEscrow(ctx context.Context, db bun.IDB, runnerID, requesterID, merchantOwnerID, orderID uuid.UUID, foodAmount, runnerAmount, platformFee, refundAmount float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseMerchantEscrow", ctx, db, runnerID, requesterID, merchantOwnerID, orderID, foodAmount, runnerAmount, platformFee, refundAmount)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseMerchantEscrow indicates an expected call of ReleaseMerchantEscrow.
func (mr *MockServiceMockRecorder) ReleaseMerchantEscrow(ctx, db, runnerID, requesterID, merchantOwnerID, orderID, foodAmount, runnerAmount, platformFee, refundAmount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseMerchantEscrow", reflect.TypeOf((*MockService)(nil).ReleaseMerchantEscrow), ctx, db, runnerID, requesterID, merchantOwnerID, orderID, foodAmount, runnerAmount, platformFee, refundAmount)
}

// RequestWithdrawal mocks base method.
func (m *MockService) RequestWithdrawal(ctx context.Context, userID uuid.UUID, amount float64, channelID *uuid.UUID, pin string, destMetadata map[string]any) (*wallet.WalletTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestWithdrawal", ctx, userID, amount, channelID, pin, destMetadata)
	ret0, _ := ret[0].(*wallet.WalletTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestWithdrawal indicates an expected call of RequestWithdrawal.
func (mr *MockServiceMockRecorder) RequestWithdrawal(ctx, userID, amount, channelID, pin, destMetadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestWithdrawal", reflect.TypeOf((*MockService)(nil).RequestWithdrawal), ctx, userID, amount, channelID, pin, destMetadata)
}

// TopUp mocks base method.
func (m *MockService) TopUp(ctx context.Context, userID uuid.UUID, amount float64, reference string) (*wallet.WalletTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TopUp", ctx, userID, amount, reference)
	ret0, _ := ret[0].(*wallet.WalletTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TopUp indicates an expected call of TopUp.
func (mr *MockServiceMockRecorder) TopUp(ctx, userID, amount, reference any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TopUp", reflect.TypeOf((*MockService)(nil).TopUp), ctx, userID, amount, reference)
}

// MockdispatcherIface is a mock of dispatcherIface interface.
type MockdispatcherIface struct {
	ctrl     *gomock.Controller
	recorder *MockdispatcherIfaceMockRecorder
	isgomock struct{}
}

// MockdispatcherIfaceMockRecorder is the mock recorder for MockdispatcherIface.
type MockdispatcherIfaceMockRecorder struct {
	mock *MockdispatcherIface
}

// NewMockdispatcherIface creates a new mock instance.
func NewMockdispatcherIface(ctrl *gomock.Controller) *MockdispatcherIface {
	mock := &MockdispatcherIface{ctrl: ctrl}
	mock.recorder = &MockdispatcherIfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdispatcherIface) EXPECT() *MockdispatcherIfaceMockRecorder {
	return m.recorder
}

// Enqueue mocks base method.
func (m *MockdispatcherIface) Enqueue(ctx context.Context, job notification.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enqueue", ctx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockdispatcherIfaceMockRecorder) Enqueue(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockdispatcherIface)(nil).Enqueue), ctx, job)
}
