// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mocks/repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	user "github.com/codecoffy/nitip-core/internal/domain/user"
	uuid "github.com/google/uuid"
	bun "github.com/uptrace/bun"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// ClearDeviceSessions mocks base method.
func (m *MockRepository) ClearDeviceSessions(ctx context.Context, deviceID string, excludeUserID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearDeviceSessions", ctx, deviceID, excludeUserID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearDeviceSessions indicates an expected call of ClearDeviceSessions.
func (mr *MockRepositoryMockRecorder) ClearDeviceSessions(ctx, deviceID, excludeUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearDeviceSessions", reflect.TypeOf((*MockRepository)(nil).ClearDeviceSessions), ctx, deviceID, excludeUserID)
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, arg1 *user.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, arg1)
}

// CreateInvitation mocks base method.
func (m *MockRepository) CreateInvitation(ctx context.Context, invite *user.RegistrationInvitation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvitation", ctx, invite)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateInvitation indicates an expected call of CreateInvitation.
func (mr *MockRepositoryMockRecorder) CreateInvitation(ctx, invite any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvitation", reflect.TypeOf((*MockRepository)(nil).CreateInvitation), ctx, invite)
}

// CreateWebAuthnCredential mocks base method.
func (m *MockRepository) CreateWebAuthnCredential(ctx context.Context, cred *user.WebauthnCredential) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWebAuthnCredential", ctx, cred)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWebAuthnCredential indicates an expected call of CreateWebAuthnCredential.
func (mr *MockRepositoryMockRecorder) CreateWebAuthnCredential(ctx, cred any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWebAuthnCredential", reflect.TypeOf((*MockRepository)(nil).CreateWebAuthnCredential), ctx, cred)
}

// Delete mocks base method.
func (m *MockRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), ctx, id)
}

// FindAll mocks base method.
func (m *MockRepository) FindAll(ctx context.Context) ([]user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockRepositoryMockRecorder) FindAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockRepository)(nil).FindAll), ctx)
}

// FindAllWithFilters mocks base method.
func (m *MockRepository) FindAllWithFilters(ctx context.Context, role string, isVerified, isSuspended *bool) ([]user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllWithFilters", ctx, role, isVerified, isSuspended)
	ret0, _ := ret[0].([]user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllWithFilters indicates an expected call of FindAllWithFilters.
func (mr *MockRepositoryMockRecorder) FindAllWithFilters(ctx, role, isVerified, isSuspended any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllWithFilters", reflect.TypeOf((*MockRepository)(nil).FindAllWithFilters), ctx, role, isVerified, isSuspended)
}

// FindBankAccountByUserID mocks base method.
func (m *MockRepository) FindBankAccountByUserID(ctx context.Context, userID uuid.UUID) (*user.UserBankAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBankAccountByUserID", ctx, userID)
	ret0, _ := ret[0].(*user.UserBankAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBankAccountByUserID indicates an expected call of FindBankAccountByUserID.
func (mr *MockRepositoryMockRecorder) FindBankAccountByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBankAccountByUserID", reflect.TypeOf((*MockRepository)(nil).FindBankAccountByUserID), ctx, userID)
}

// FindByEmail mocks base method.
func (m *MockRepository) FindByEmail(ctx context.Context, email string) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmail", ctx, email)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmail indicates an expected call of FindByEmail.
func (mr *MockRepositoryMockRecorder) FindByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmail", reflect.TypeOf((*MockRepository)(nil).FindByEmail), ctx, email)
}

// FindByID mocks base method.
func (m *MockRepository) FindByID(ctx context.Context, id uuid.UUID) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRepository)(nil).FindByID), ctx, id)
}

// FindByIDs mocks base method.
func (m *MockRepository) FindByIDs(ctx context.Context, ids []uuid.UUID) ([]user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIDs", ctx, ids)
	ret0, _ := ret[0].([]user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIDs indicates an expected call of FindByIDs.
func (mr *MockRepositoryMockRecorder) FindByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIDs", reflect.TypeOf((*MockRepository)(nil).FindByIDs), ctx, ids)
}

// FindByWhatsappNumber mocks base method.
func (m *MockRepository) FindByWhatsappNumber(ctx context.Context, whatsappNumber string) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByWhatsappNumber", ctx, whatsappNumber)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByWhatsappNumber indicates an expected call of FindByWhatsappNumber.
func (mr *MockRepositoryMockRecorder) FindByWhatsappNumber(ctx, whatsappNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByWhatsappNumber", reflect.TypeOf((*MockRepository)(nil).FindByWhatsappNumber), ctx, whatsappNumber)
}

// FindInvitationByToken mocks base method.
func (m *MockRepository) FindInvitationByToken(ctx context.Context, token string) (*user.RegistrationInvitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindInvitationByToken", ctx, token)
	ret0, _ := ret[0].(*user.RegistrationInvitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindInvitationByToken indicates an expected call of FindInvitationByToken.
func (mr *MockRepositoryMockRecorder) FindInvitationByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindInvitationByToken", reflect.TypeOf((*MockRepository)(nil).FindInvitationByToken), ctx, token)
}

// FindNearbyRunners mocks base method.
func (m *MockRepository) FindNearbyRunners(ctx context.Context, lat, lng, radiusKm float64) ([]user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindNearbyRunners", ctx, lat, lng, radiusKm)
	ret0, _ := ret[0].([]user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindNearbyRunners indicates an expected call of FindNearbyRunners.
func (mr *MockRepositoryMockRecorder) FindNearbyRunners(ctx, lat, lng, radiusKm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindNearbyRunners", reflect.TypeOf((*MockRepository)(nil).FindNearbyRunners), ctx, lat, lng, radiusKm)
}

// FindWebAuthnCredentialsByUserID mocks base method.
func (m *MockRepository) FindWebAuthnCredentialsByUserID(ctx context.Context, userID uuid.UUID) ([]user.WebauthnCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWebAuthnCredentialsByUserID", ctx, userID)
	ret0, _ := ret[0].([]user.WebauthnCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindWebAuthnCredentialsByUserID indicates an expected call of FindWebAuthnCredentialsByUserID.
func (mr *MockRepositoryMockRecorder) FindWebAuthnCredentialsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWebAuthnCredentialsByUserID", reflect.TypeOf((*MockRepository)(nil).FindWebAuthnCredentialsByUserID), ctx, userID)
}

// GetDB mocks base method.
func (m *MockRepository) GetDB() *bun.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDB")
	ret0, _ := ret[0].(*bun.DB)
	return ret0
}

// GetDB indicates an expected call of GetDB.
func (mr *MockRepositoryMockRecorder) GetDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDB", reflect.TypeOf((*MockRepository)(nil).GetDB))
}

// ListInvitations mocks base method.
func (m *MockRepository) ListInvitations(ctx context.Context) ([]user.RegistrationInvitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInvitations", ctx)
	ret0, _ := ret[0].([]user.RegistrationInvitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInvitations indicates an expected call of ListInvitations.
func (mr *MockRepositoryMockRecorder) ListInvitations(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInvitations", reflect.TypeOf((*MockRepository)(nil).ListInvitations), ctx)
}

// Update mocks base method.
func (m *MockRepository) Update(ctx context.Context, arg1 *user.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder) Update(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), ctx, arg1)
}

// UpdateAcceptingOrders mocks base method.
func (m *MockRepository) UpdateAcceptingOrders(ctx context.Context, id uuid.UUID, isAccepting bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAcceptingOrders", ctx, id, isAccepting)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAcceptingOrders indicates an expected call of UpdateAcceptingOrders.
func (mr *MockRepositoryMockRecorder) UpdateAcceptingOrders(ctx, id, isAccepting any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAcceptingOrders", reflect.TypeOf((*MockRepository)(nil).UpdateAcceptingOrders), ctx, id, isAccepting)
}

// UpdateInvitation mocks base method.
func (m *MockRepository) UpdateInvitation(ctx context.Context, invite *user.RegistrationInvitation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInvitation", ctx, invite)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateInvitation indicates an expected call of UpdateInvitation.
func (mr *MockRepositoryMockRecorder) UpdateInvitation(ctx, invite any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInvitation", reflect.TypeOf((*MockRepository)(nil).UpdateInvitation), ctx, invite)
}

// UpdateLocation mocks base method.
func (m *MockRepository) UpdateLocation(ctx context.Context, id uuid.UUID, lat, lng float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLocation", ctx, id, lat, lng)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLocation indicates an expected call of UpdateLocation.
func (mr *MockRepositoryMockRecorder) UpdateLocation(ctx, id, lat, lng any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLocation", reflect.TypeOf((*MockRepository)(nil).UpdateLocation), ctx, id, lat, lng)
}

// UpdateWebAuthnCredential mocks base method.
func (m *MockRepository) UpdateWebAuthnCredential(ctx context.Context, cred *user.WebauthnCredential) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWebAuthnCredential", ctx, cred)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWebAuthnCredential indicates an expected call of UpdateWebAuthnCredential.
func (mr *MockRepositoryMockRecorder) UpdateWebAuthnCredential(ctx, cred any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWebAuthnCredential", reflect.TypeOf((*MockRepository)(nil).UpdateWebAuthnCredential), ctx, cred)
}

// UpsertBankAccount mocks base method.
func (m *MockRepository) UpsertBankAccount(ctx context.Context, bankAccount *user.UserBankAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertBankAccount", ctx, bankAccount)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertBankAccount indicates an expected call of UpsertBankAccount.
func (mr *MockRepositoryMockRecorder) UpsertBankAccount(ctx, bankAccount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertBankAccount", reflect.TypeOf((*MockRepository)(nil).UpsertBankAccount), ctx, bankAccount)
}
