// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	cache "github.com/codecoffy/nitip-core/internal/cache"
	user "github.com/codecoffy/nitip-core/internal/domain/user"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AdminCreate mocks base method.
func (m *MockService) AdminCreate(ctx context.Context, req user.AdminCreateUserRequest) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminCreate", ctx, req)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminCreate indicates an expected call of AdminCreate.
func (mr *MockServiceMockRecorder) AdminCreate(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminCreate", reflect.TypeOf((*MockService)(nil).AdminCreate), ctx, req)
}

// AdminDisableTOTP mocks base method.
func (m *MockService) AdminDisableTOTP(ctx context.Context, id, adminID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminDisableTOTP", ctx, id, adminID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AdminDisableTOTP indicates an expected call of AdminDisableTOTP.
func (mr *MockServiceMockRecorder) AdminDisableTOTP(ctx, id, adminID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminDisableTOTP", reflect.TypeOf((*MockService)(nil).AdminDisableTOTP), ctx, id, adminID)
}

// AdminRegisterBankAccount mocks base method.
func (m *MockService) AdminRegisterBankAccount(ctx context.Context, userID uuid.UUID, bankName, accountNo, accountName, adminPassword, totpCode string, adminID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminRegisterBankAccount", ctx, userID, bankName, accountNo, accountName, adminPassword, totpCode, adminID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AdminRegisterBankAccount indicates an expected call of AdminRegisterBankAccount.
func (mr *MockServiceMockRecorder) AdminRegisterBankAccount(ctx, userID, bankName, accountNo, accountName, adminPassword, totpCode, adminID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminRegisterBankAccount", reflect.TypeOf((*MockService)(nil).AdminRegisterBankAccount), ctx, userID, bankName, accountNo, accountName, adminPassword, totpCode, adminID)
}

// AdminResetPassword mocks base method.
func (m *MockService) AdminResetPassword(ctx context.Context, targetUserID uuid.UUID, newPassword, adminPassword, totpCode string, adminID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminResetPassword", ctx, targetUserID, newPassword, adminPassword, totpCode, adminID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AdminResetPassword indicates an expected call of AdminResetPassword.
func (mr *MockServiceMockRecorder) AdminResetPassword(ctx, targetUserID, newPassword, adminPassword, totpCode, adminID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminResetPassword", reflect.TypeOf((*MockService)(nil).AdminResetPassword), ctx, targetUserID, newPassword, adminPassword, totpCode, adminID)
}

// ChangePin mocks base method.
func (m *MockService) ChangePin(ctx context.Context, id uuid.UUID, req user.ChangePinRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePin", ctx, id, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangePin indicates an expected call of ChangePin.
func (mr *MockServiceMockRecorder) ChangePin(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePin", reflect.TypeOf((*MockService)(nil).ChangePin), ctx, id, req)
}

// Create mocks base method.
func (m *MockService) Create(ctx context.Context, req user.CreateUserRequest) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockServiceMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockService)(nil).Create), ctx, req)
}

// CreateInvitation mocks base method.
func (m *MockService) CreateInvitation(ctx context.Context, actorID uuid.UUID, phoneNumber, role string) (*user.RegistrationInvitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvitation", ctx, actorID, phoneNumber, role)
	ret0, _ := ret[0].(*user.RegistrationInvitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInvitation indicates an expected call of CreateInvitation.
func (mr *MockServiceMockRecorder) CreateInvitation(ctx, actorID, phoneNumber, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvitation", reflect.TypeOf((*MockService)(nil).CreateInvitation), ctx, actorID, phoneNumber, role)
}

// Delete mocks base method.
func (m *MockService) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockService)(nil).Delete), ctx, id)
}

// DisableTOTP mocks base method.
func (m *MockService) DisableTOTP(ctx context.Context, id uuid.UUID, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableTOTP", ctx, id, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisableTOTP indicates an expected call of DisableTOTP.
func (mr *MockServiceMockRecorder) DisableTOTP(ctx, id, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableTOTP", reflect.TypeOf((*MockService)(nil).DisableTOTP), ctx, id, code)
}

// GetAll mocks base method.
func (m *MockService) GetAll(ctx context.Context) ([]user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockServiceMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockService)(nil).GetAll), ctx)
}

// GetAllWithFilters mocks base method.
func (m *MockService) GetAllWithFilters(ctx context.Context, role string, isVerified, isSuspended *bool) ([]user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllWithFilters", ctx, role, isVerified, isSuspended)
	ret0, _ := ret[0].([]user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllWithFilters indicates an expected call of GetAllWithFilters.
func (mr *MockServiceMockRecorder) GetAllWithFilters(ctx, role, isVerified, isSuspended any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllWithFilters", reflect.TypeOf((*MockService)(nil).GetAllWithFilters), ctx, role, isVerified, isSuspended)
}

// GetBankAccount mocks base method.
func (m *MockService) GetBankAccount(ctx context.Context, userID uuid.UUID) (*user.UserBankAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBankAccount", ctx, userID)
	ret0, _ := ret[0].(*user.UserBankAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBankAccount indicates an expected call of GetBankAccount.
func (mr *MockServiceMockRecorder) GetBankAccount(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBankAccount", reflect.TypeOf((*MockService)(nil).GetBankAccount), ctx, userID)
}

// GetByID mocks base method.
func (m *MockService) GetByID(ctx context.Context, id, requestorID uuid.UUID) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id, requestorID)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockServiceMockRecorder) GetByID(ctx, id, requestorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockService)(nil).GetByID), ctx, id, requestorID)
}

// GetByIDs mocks base method.
func (m *MockService) GetByIDs(ctx context.Context, ids []uuid.UUID) ([]user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDs", ctx, ids)
	ret0, _ := ret[0].([]user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDs indicates an expected call of GetByIDs.
func (mr *MockServiceMockRecorder) GetByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDs", reflect.TypeOf((*MockService)(nil).GetByIDs), ctx, ids)
}

// GetRedis mocks base method.
func (m *MockService) GetRedis() *cache.Redis {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRedis")
	ret0, _ := ret[0].(*cache.Redis)
	return ret0
}

// GetRedis indicates an expected call of GetRedis.
func (mr *MockServiceMockRecorder) GetRedis() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRedis", reflect.TypeOf((*MockService)(nil).GetRedis))
}

// ListInvitations mocks base method.
func (m *MockService) ListInvitations(ctx context.Context) ([]user.RegistrationInvitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInvitations", ctx)
	ret0, _ := ret[0].([]user.RegistrationInvitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInvitations indicates an expected call of ListInvitations.
func (mr *MockServiceMockRecorder) ListInvitations(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInvitations", reflect.TypeOf((*MockService)(nil).ListInvitations), ctx)
}

// Login mocks base method.
func (m *MockService) Login(ctx context.Context, req user.LoginRequest, platform string) (*user.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, req, platform)
	ret0, _ := ret[0].(*user.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockServiceMockRecorder) Login(ctx, req, platform any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockService)(nil).Login), ctx, req, platform)
}

// OnboardMerchant mocks base method.
func (m *MockService) OnboardMerchant(ctx context.Context, req user.OnboardMerchantRequest) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnboardMerchant", ctx, req)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OnboardMerchant indicates an expected call of OnboardMerchant.
func (mr *MockServiceMockRecorder) OnboardMerchant(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnboardMerchant", reflect.TypeOf((*MockService)(nil).OnboardMerchant), ctx, req)
}

// OnboardRunner mocks base method.
func (m *MockService) OnboardRunner(ctx context.Context, req user.OnboardRunnerRequest) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnboardRunner", ctx, req)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OnboardRunner indicates an expected call of OnboardRunner.
func (mr *MockServiceMockRecorder) OnboardRunner(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnboardRunner", reflect.TypeOf((*MockService)(nil).OnboardRunner), ctx, req)
}

// Refresh mocks base method.
func (m *MockService) Refresh(ctx context.Context, refreshToken string) (*user.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx, refreshToken)
	ret0, _ := ret[0].(*user.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Refresh indicates an expected call of Refresh.
func (mr *MockServiceMockRecorder) Refresh(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockService)(nil).Refresh), ctx, refreshToken)
}

// RegisterBankAccount mocks base method.
func (m *MockService) RegisterBankAccount(ctx context.Context, userID uuid.UUID, bankName, accountNo, accountName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterBankAccount", ctx, userID, bankName, accountNo, accountName)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterBankAccount indicates an expected call of RegisterBankAccount.
func (mr *MockServiceMockRecorder) RegisterBankAccount(ctx, userID, bankName, accountNo, accountName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterBankAccount", reflect.TypeOf((*MockService)(nil).RegisterBankAccount), ctx, userID, bankName, accountNo, accountName)
}

// SetupPin mocks base method.
func (m *MockService) SetupPin(ctx context.Context, id uuid.UUID, req user.SetupPinRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetupPin", ctx, id, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetupPin indicates an expected call of SetupPin.
func (mr *MockServiceMockRecorder) SetupPin(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupPin", reflect.TypeOf((*MockService)(nil).SetupPin), ctx, id, req)
}

// SetupTOTP mocks base method.
func (m *MockService) SetupTOTP(ctx context.Context, id uuid.UUID) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetupTOTP", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SetupTOTP indicates an expected call of SetupTOTP.
func (mr *MockServiceMockRecorder) SetupTOTP(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupTOTP", reflect.TypeOf((*MockService)(nil).SetupTOTP), ctx, id)
}

// UnlockPin mocks base method.
func (m *MockService) UnlockPin(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlockPin", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlockPin indicates an expected call of UnlockPin.
func (mr *MockServiceMockRecorder) UnlockPin(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlockPin", reflect.TypeOf((*MockService)(nil).UnlockPin), ctx, id)
}

// UpdateAcceptingOrders mocks base method.
func (m *MockService) UpdateAcceptingOrders(ctx context.Context, id uuid.UUID, isAccepting bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAcceptingOrders", ctx, id, isAccepting)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAcceptingOrders indicates an expected call of UpdateAcceptingOrders.
func (mr *MockServiceMockRecorder) UpdateAcceptingOrders(ctx, id, isAccepting any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAcceptingOrders", reflect.TypeOf((*MockService)(nil).UpdateAcceptingOrders), ctx, id, isAccepting)
}

// UpdateHeartbeat mocks base method.
func (m *MockService) UpdateHeartbeat(ctx context.Context, id uuid.UUID, req user.HeartbeatRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateHeartbeat", ctx, id, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateHeartbeat indicates an expected call of UpdateHeartbeat.
func (mr *MockServiceMockRecorder) UpdateHeartbeat(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateHeartbeat", reflect.TypeOf((*MockService)(nil).UpdateHeartbeat), ctx, id, req)
}

// UpdateHome mocks base method.
func (m *MockService) UpdateHome(ctx context.Context, id uuid.UUID, req user.UpdateHomeRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateHome", ctx, id, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateHome indicates an expected call of UpdateHome.
func (mr *MockServiceMockRecorder) UpdateHome(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateHome", reflect.TypeOf((*MockService)(nil).UpdateHome), ctx, id, req)
}

// UpdateLocation mocks base method.
func (m *MockService) UpdateLocation(ctx context.Context, id uuid.UUID, lat, lng float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLocation", ctx, id, lat, lng)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLocation indicates an expected call of UpdateLocation.
func (mr *MockServiceMockRecorder) UpdateLocation(ctx, id, lat, lng any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLocation", reflect.TypeOf((*MockService)(nil).UpdateLocation), ctx, id, lat, lng)
}

// UpdateProfile mocks base method.
func (m *MockService) UpdateProfile(ctx context.Context, id uuid.UUID, req user.UpdateProfileRequest, avatarFile io.Reader, avatarFilename string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", ctx, id, req, avatarFile, avatarFilename)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockServiceMockRecorder) UpdateProfile(ctx, id, req, avatarFile, avatarFilename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockService)(nil).UpdateProfile), ctx, id, req, avatarFile, avatarFilename)
}

// UpdateSuspendStatus mocks base method.
func (m *MockService) UpdateSuspendStatus(ctx context.Context, id, actorID uuid.UUID, isSuspended bool, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSuspendStatus", ctx, id, actorID, isSuspended, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSuspendStatus indicates an expected call of UpdateSuspendStatus.
func (mr *MockServiceMockRecorder) UpdateSuspendStatus(ctx, id, actorID, isSuspended, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSuspendStatus", reflect.TypeOf((*MockService)(nil).UpdateSuspendStatus), ctx, id, actorID, isSuspended, reason)
}

// UpdateTrustScore mocks base method.
func (m *MockService) UpdateTrustScore(ctx context.Context, id, actorID uuid.UUID, score int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTrustScore", ctx, id, actorID, score)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTrustScore indicates an expected call of UpdateTrustScore.
func (mr *MockServiceMockRecorder) UpdateTrustScore(ctx, id, actorID, score any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTrustScore", reflect.TypeOf((*MockService)(nil).UpdateTrustScore), ctx, id, actorID, score)
}

// UpdateVerification mocks base method.
func (m *MockService) UpdateVerification(ctx context.Context, id, actorID uuid.UUID, isVerified bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVerification", ctx, id, actorID, isVerified)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateVerification indicates an expected call of UpdateVerification.
func (mr *MockServiceMockRecorder) UpdateVerification(ctx, id, actorID, isVerified any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVerification", reflect.TypeOf((*MockService)(nil).UpdateVerification), ctx, id, actorID, isVerified)
}

// ValidateInvitation mocks base method.
func (m *MockService) ValidateInvitation(ctx context.Context, token string) (*user.RegistrationInvitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateInvitation", ctx, token)
	ret0, _ := ret[0].(*user.RegistrationInvitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateInvitation indicates an expected call of ValidateInvitation.
func (mr *MockServiceMockRecorder) ValidateInvitation(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateInvitation", reflect.TypeOf((*MockService)(nil).ValidateInvitation), ctx, token)
}

// VerifyAndEnableTOTP mocks base method.
func (m *MockService) VerifyAndEnableTOTP(ctx context.Context, id uuid.UUID, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyAndEnableTOTP", ctx, id, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyAndEnableTOTP indicates an expected call of VerifyAndEnableTOTP.
func (mr *MockServiceMockRecorder) VerifyAndEnableTOTP(ctx, id, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyAndEnableTOTP", reflect.TypeOf((*MockService)(nil).VerifyAndEnableTOTP), ctx, id, code)
}

// VerifyPin mocks base method.
func (m *MockService) VerifyPin(ctx context.Context, id uuid.UUID, pin string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyPin", ctx, id, pin)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyPin indicates an expected call of VerifyPin.
func (mr *MockServiceMockRecorder) VerifyPin(ctx, id, pin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyPin", reflect.TypeOf((*MockService)(nil).VerifyPin), ctx, id, pin)
}

// WebAuthnLoginBegin mocks base method.
func (m *MockService) WebAuthnLoginBegin(ctx context.Context, email string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WebAuthnLoginBegin", ctx, email)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WebAuthnLoginBegin indicates an expected call of WebAuthnLoginBegin.
func (mr *MockServiceMockRecorder) WebAuthnLoginBegin(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WebAuthnLoginBegin", reflect.TypeOf((*MockService)(nil).WebAuthnLoginBegin), ctx, email)
}

// WebAuthnLoginFinish mocks base method.
func (m *MockService) WebAuthnLoginFinish(ctx context.Context, email string, parsedResponse any, platform string) (*user.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WebAuthnLoginFinish", ctx, email, parsedResponse, platform)
	ret0, _ := ret[0].(*user.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WebAuthnLoginFinish indicates an expected call of WebAuthnLoginFinish.
func (mr *MockServiceMockRecorder) WebAuthnLoginFinish(ctx, email, parsedResponse, platform any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WebAuthnLoginFinish", reflect.TypeOf((*MockService)(nil).WebAuthnLoginFinish), ctx, email, parsedResponse, platform)
}

// WebAuthnRegisterBegin mocks base method.
func (m *MockService) WebAuthnRegisterBegin(ctx context.Context, userID uuid.UUID) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WebAuthnRegisterBegin", ctx, userID)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WebAuthnRegisterBegin indicates an expected call of WebAuthnRegisterBegin.
func (mr *MockServiceMockRecorder) WebAuthnRegisterBegin(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WebAuthnRegisterBegin", reflect.TypeOf((*MockService)(nil).WebAuthnRegisterBegin), ctx, userID)
}

// WebAuthnRegisterFinish mocks base method.
func (m *MockService) WebAuthnRegisterFinish(ctx context.Context, userID uuid.UUID, parsedResponse any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WebAuthnRegisterFinish", ctx, userID, parsedResponse)
	ret0, _ := ret[0].(error)
	return ret0
}

// WebAuthnRegisterFinish indicates an expected call of WebAuthnRegisterFinish.
func (mr *MockServiceMockRecorder) WebAuthnRegisterFinish(ctx, userID, parsedResponse any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WebAuthnRegisterFinish", reflect.TypeOf((*MockService)(nil).WebAuthnRegisterFinish), ctx, userID, parsedResponse)
}
