// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mocks/repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	merchant "github.com/codecoffy/nitip-core/internal/domain/merchant"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateAddonMaster mocks base method.
func (m_2 *MockRepository) CreateAddonMaster(ctx context.Context, m *merchant.AddonMaster) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "CreateAddonMaster", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAddonMaster indicates an expected call of CreateAddonMaster.
func (mr *MockRepositoryMockRecorder) CreateAddonMaster(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAddonMaster", reflect.TypeOf((*MockRepository)(nil).CreateAddonMaster), ctx, m)
}

// CreateAddonOption mocks base method.
func (m *MockRepository) CreateAddonOption(ctx context.Context, o *merchant.AddonOption) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAddonOption", ctx, o)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAddonOption indicates an expected call of CreateAddonOption.
func (mr *MockRepositoryMockRecorder) CreateAddonOption(ctx, o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAddonOption", reflect.TypeOf((*MockRepository)(nil).CreateAddonOption), ctx, o)
}

// CreateCategory mocks base method.
func (m *MockRepository) CreateCategory(ctx context.Context, c *merchant.MenuCategory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCategory", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCategory indicates an expected call of CreateCategory.
func (mr *MockRepositoryMockRecorder) CreateCategory(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCategory", reflect.TypeOf((*MockRepository)(nil).CreateCategory), ctx, c)
}

// CreateMenu mocks base method.
func (m *MockRepository) CreateMenu(ctx context.Context, menu *merchant.Menu) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMenu", ctx, menu)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMenu indicates an expected call of CreateMenu.
func (mr *MockRepositoryMockRecorder) CreateMenu(ctx, menu any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMenu", reflect.TypeOf((*MockRepository)(nil).CreateMenu), ctx, menu)
}

// CreateMerchant mocks base method.
func (m_2 *MockRepository) CreateMerchant(ctx context.Context, m *merchant.Merchant) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "CreateMerchant", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMerchant indicates an expected call of CreateMerchant.
func (mr *MockRepositoryMockRecorder) CreateMerchant(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMerchant", reflect.TypeOf((*MockRepository)(nil).CreateMerchant), ctx, m)
}

// CreateOrderItems mocks base method.
func (m *MockRepository) CreateOrderItems(ctx context.Context, items []merchant.OrderItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrderItems", ctx, items)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrderItems indicates an expected call of CreateOrderItems.
func (mr *MockRepositoryMockRecorder) CreateOrderItems(ctx, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrderItems", reflect.TypeOf((*MockRepository)(nil).CreateOrderItems), ctx, items)
}

// CreateSurvey mocks base method.
func (m *MockRepository) CreateSurvey(ctx context.Context, s *merchant.MerchantSurvey) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSurvey", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSurvey indicates an expected call of CreateSurvey.
func (mr *MockRepositoryMockRecorder) CreateSurvey(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSurvey", reflect.TypeOf((*MockRepository)(nil).CreateSurvey), ctx, s)
}

// CreateToppingGroup mocks base method.
func (m *MockRepository) CreateToppingGroup(ctx context.Context, g *merchant.MenuToppingGroup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateToppingGroup", ctx, g)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateToppingGroup indicates an expected call of CreateToppingGroup.
func (mr *MockRepositoryMockRecorder) CreateToppingGroup(ctx, g any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateToppingGroup", reflect.TypeOf((*MockRepository)(nil).CreateToppingGroup), ctx, g)
}

// CreateToppingOption mocks base method.
func (m *MockRepository) CreateToppingOption(ctx context.Context, o *merchant.MenuToppingOption) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateToppingOption", ctx, o)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateToppingOption indicates an expected call of CreateToppingOption.
func (mr *MockRepositoryMockRecorder) CreateToppingOption(ctx, o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateToppingOption", reflect.TypeOf((*MockRepository)(nil).CreateToppingOption), ctx, o)
}

// CreateVariantGroup mocks base method.
func (m *MockRepository) CreateVariantGroup(ctx context.Context, g *merchant.MenuVariantGroup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVariantGroup", ctx, g)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateVariantGroup indicates an expected call of CreateVariantGroup.
func (mr *MockRepositoryMockRecorder) CreateVariantGroup(ctx, g any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVariantGroup", reflect.TypeOf((*MockRepository)(nil).CreateVariantGroup), ctx, g)
}

// CreateVariantOption mocks base method.
func (m *MockRepository) CreateVariantOption(ctx context.Context, o *merchant.MenuVariantOption) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVariantOption", ctx, o)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateVariantOption indicates an expected call of CreateVariantOption.
func (mr *MockRepositoryMockRecorder) CreateVariantOption(ctx, o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVariantOption", reflect.TypeOf((*MockRepository)(nil).CreateVariantOption), ctx, o)
}

// DeleteAddonMaster mocks base method.
func (m *MockRepository) DeleteAddonMaster(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAddonMaster", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAddonMaster indicates an expected call of DeleteAddonMaster.
func (mr *MockRepositoryMockRecorder) DeleteAddonMaster(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAddonMaster", reflect.TypeOf((*MockRepository)(nil).DeleteAddonMaster), ctx, id)
}

// DeleteAddonOption mocks base method.
func (m *MockRepository) DeleteAddonOption(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAddonOption", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAddonOption indicates an expected call of DeleteAddonOption.
func (mr *MockRepositoryMockRecorder) DeleteAddonOption(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAddonOption", reflect.TypeOf((*MockRepository)(nil).DeleteAddonOption), ctx, id)
}

// DeleteCategory mocks base method.
func (m *MockRepository) DeleteCategory(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCategory", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCategory indicates an expected call of DeleteCategory.
func (mr *MockRepositoryMockRecorder) DeleteCategory(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCategory", reflect.TypeOf((*MockRepository)(nil).DeleteCategory), ctx, id)
}

// DeleteMenu mocks base method.
func (m *MockRepository) DeleteMenu(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMenu", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMenu indicates an expected call of DeleteMenu.
func (mr *MockRepositoryMockRecorder) DeleteMenu(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMenu", reflect.TypeOf((*MockRepository)(nil).DeleteMenu), ctx, id)
}

// DeleteMerchant mocks base method.
func (m *MockRepository) DeleteMerchant(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMerchant", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMerchant indicates an expected call of DeleteMerchant.
func (mr *MockRepositoryMockRecorder) DeleteMerchant(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMerchant", reflect.TypeOf((*MockRepository)(nil).DeleteMerchant), ctx, id)
}

// DeleteToppingGroup mocks base method.
func (m *MockRepository) DeleteToppingGroup(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteToppingGroup", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteToppingGroup indicates an expected call of DeleteToppingGroup.
func (mr *MockRepositoryMockRecorder) DeleteToppingGroup(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteToppingGroup", reflect.TypeOf((*MockRepository)(nil).DeleteToppingGroup), ctx, id)
}

// DeleteToppingOption mocks base method.
func (m *MockRepository) DeleteToppingOption(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteToppingOption", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteToppingOption indicates an expected call of DeleteToppingOption.
func (mr *MockRepositoryMockRecorder) DeleteToppingOption(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteToppingOption", reflect.TypeOf((*MockRepository)(nil).DeleteToppingOption), ctx, id)
}

// DeleteVariantGroup mocks base method.
func (m *MockRepository) DeleteVariantGroup(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVariantGroup", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVariantGroup indicates an expected call of DeleteVariantGroup.
func (mr *MockRepositoryMockRecorder) DeleteVariantGroup(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVariantGroup", reflect.TypeOf((*MockRepository)(nil).DeleteVariantGroup), ctx, id)
}

// DeleteVariantOption mocks base method.
func (m *MockRepository) DeleteVariantOption(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVariantOption", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVariantOption indicates an expected call of DeleteVariantOption.
func (mr *MockRepositoryMockRecorder) DeleteVariantOption(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVariantOption", reflect.TypeOf((*MockRepository)(nil).DeleteVariantOption), ctx, id)
}

// GetAddonMasterByID mocks base method.
func (m *MockRepository) GetAddonMasterByID(ctx context.Context, id uuid.UUID) (*merchant.AddonMaster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAddonMasterByID", ctx, id)
	ret0, _ := ret[0].(*merchant.AddonMaster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAddonMasterByID indicates an expected call of GetAddonMasterByID.
func (mr *MockRepositoryMockRecorder) GetAddonMasterByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAddonMasterByID", reflect.TypeOf((*MockRepository)(nil).GetAddonMasterByID), ctx, id)
}

// GetAddonOptionByID mocks base method.
func (m *MockRepository) GetAddonOptionByID(ctx context.Context, id uuid.UUID) (*merchant.AddonOption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAddonOptionByID", ctx, id)
	ret0, _ := ret[0].(*merchant.AddonOption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAddonOptionByID indicates an expected call of GetAddonOptionByID.
func (mr *MockRepositoryMockRecorder) GetAddonOptionByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAddonOptionByID", reflect.TypeOf((*MockRepository)(nil).GetAddonOptionByID), ctx, id)
}

// GetCategoryByID mocks base method.
func (m *MockRepository) GetCategoryByID(ctx context.Context, id uuid.UUID) (*merchant.MenuCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryByID", ctx, id)
	ret0, _ := ret[0].(*merchant.MenuCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoryByID indicates an expected call of GetCategoryByID.
func (mr *MockRepositoryMockRecorder) GetCategoryByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryByID", reflect.TypeOf((*MockRepository)(nil).GetCategoryByID), ctx, id)
}

// GetMenuByID mocks base method.
func (m *MockRepository) GetMenuByID(ctx context.Context, id uuid.UUID) (*merchant.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMenuByID", ctx, id)
	ret0, _ := ret[0].(*merchant.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMenuByID indicates an expected call of GetMenuByID.
func (mr *MockRepositoryMockRecorder) GetMenuByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMenuByID", reflect.TypeOf((*MockRepository)(nil).GetMenuByID), ctx, id)
}

// GetMerchantByID mocks base method.
func (m *MockRepository) GetMerchantByID(ctx context.Context, id uuid.UUID) (*merchant.Merchant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMerchantByID", ctx, id)
	ret0, _ := ret[0].(*merchant.Merchant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMerchantByID indicates an expected call of GetMerchantByID.
func (mr *MockRepositoryMockRecorder) GetMerchantByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMerchantByID", reflect.TypeOf((*MockRepository)(nil).GetMerchantByID), ctx, id)
}

// GetMerchantByOwnerID mocks base method.
func (m *MockRepository) GetMerchantByOwnerID(ctx context.Context, ownerID uuid.UUID) (*merchant.Merchant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMerchantByOwnerID", ctx, ownerID)
	ret0, _ := ret[0].(*merchant.Merchant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMerchantByOwnerID indicates an expected call of GetMerchantByOwnerID.
func (mr *MockRepositoryMockRecorder) GetMerchantByOwnerID(ctx, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMerchantByOwnerID", reflect.TypeOf((*MockRepository)(nil).GetMerchantByOwnerID), ctx, ownerID)
}

// GetToppingGroupByID mocks base method.
func (m *MockRepository) GetToppingGroupByID(ctx context.Context, id uuid.UUID) (*merchant.MenuToppingGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetToppingGroupByID", ctx, id)
	ret0, _ := ret[0].(*merchant.MenuToppingGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetToppingGroupByID indicates an expected call of GetToppingGroupByID.
func (mr *MockRepositoryMockRecorder) GetToppingGroupByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetToppingGroupByID", reflect.TypeOf((*MockRepository)(nil).GetToppingGroupByID), ctx, id)
}

// GetToppingOptionByID mocks base method.
func (m *MockRepository) GetToppingOptionByID(ctx context.Context, id uuid.UUID) (*merchant.MenuToppingOption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetToppingOptionByID", ctx, id)
	ret0, _ := ret[0].(*merchant.MenuToppingOption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetToppingOptionByID indicates an expected call of GetToppingOptionByID.
func (mr *MockRepositoryMockRecorder) GetToppingOptionByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetToppingOptionByID", reflect.TypeOf((*MockRepository)(nil).GetToppingOptionByID), ctx, id)
}

// GetVariantGroupByID mocks base method.
func (m *MockRepository) GetVariantGroupByID(ctx context.Context, id uuid.UUID) (*merchant.MenuVariantGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVariantGroupByID", ctx, id)
	ret0, _ := ret[0].(*merchant.MenuVariantGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVariantGroupByID indicates an expected call of GetVariantGroupByID.
func (mr *MockRepositoryMockRecorder) GetVariantGroupByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVariantGroupByID", reflect.TypeOf((*MockRepository)(nil).GetVariantGroupByID), ctx, id)
}

// GetVariantOptionByID mocks base method.
func (m *MockRepository) GetVariantOptionByID(ctx context.Context, id uuid.UUID) (*merchant.MenuVariantOption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVariantOptionByID", ctx, id)
	ret0, _ := ret[0].(*merchant.MenuVariantOption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVariantOptionByID indicates an expected call of GetVariantOptionByID.
func (mr *MockRepositoryMockRecorder) GetVariantOptionByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVariantOptionByID", reflect.TypeOf((*MockRepository)(nil).GetVariantOptionByID), ctx, id)
}

// ListAddonMastersByMerchantID mocks base method.
func (m *MockRepository) ListAddonMastersByMerchantID(ctx context.Context, merchantID uuid.UUID) ([]merchant.AddonMaster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAddonMastersByMerchantID", ctx, merchantID)
	ret0, _ := ret[0].([]merchant.AddonMaster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAddonMastersByMerchantID indicates an expected call of ListAddonMastersByMerchantID.
func (mr *MockRepositoryMockRecorder) ListAddonMastersByMerchantID(ctx, merchantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAddonMastersByMerchantID", reflect.TypeOf((*MockRepository)(nil).ListAddonMastersByMerchantID), ctx, merchantID)
}

// ListAddonOptionsByMasterID mocks base method.
func (m *MockRepository) ListAddonOptionsByMasterID(ctx context.Context, masterID uuid.UUID) ([]merchant.AddonOption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAddonOptionsByMasterID", ctx, masterID)
	ret0, _ := ret[0].([]merchant.AddonOption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAddonOptionsByMasterID indicates an expected call of ListAddonOptionsByMasterID.
func (mr *MockRepositoryMockRecorder) ListAddonOptionsByMasterID(ctx, masterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAddonOptionsByMasterID", reflect.TypeOf((*MockRepository)(nil).ListAddonOptionsByMasterID), ctx, masterID)
}

// ListAllImagesByMerchantID mocks base method.
func (m *MockRepository) ListAllImagesByMerchantID(ctx context.Context, merchantID uuid.UUID) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllImagesByMerchantID", ctx, merchantID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllImagesByMerchantID indicates an expected call of ListAllImagesByMerchantID.
func (mr *MockRepositoryMockRecorder) ListAllImagesByMerchantID(ctx, merchantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllImagesByMerchantID", reflect.TypeOf((*MockRepository)(nil).ListAllImagesByMerchantID), ctx, merchantID)
}

// ListAllMerchants mocks base method.
func (m *MockRepository) ListAllMerchants(ctx context.Context) ([]merchant.Merchant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllMerchants", ctx)
	ret0, _ := ret[0].([]merchant.Merchant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllMerchants indicates an expected call of ListAllMerchants.
func (mr *MockRepositoryMockRecorder) ListAllMerchants(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllMerchants", reflect.TypeOf((*MockRepository)(nil).ListAllMerchants), ctx)
}

// ListCategoriesByMerchantID mocks base method.
func (m *MockRepository) ListCategoriesByMerchantID(ctx context.Context, merchantID uuid.UUID) ([]merchant.MenuCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCategoriesByMerchantID", ctx, merchantID)
	ret0, _ := ret[0].([]merchant.MenuCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCategoriesByMerchantID indicates an expected call of ListCategoriesByMerchantID.
func (mr *MockRepositoryMockRecorder) ListCategoriesByMerchantID(ctx, merchantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCategoriesByMerchantID", reflect.TypeOf((*MockRepository)(nil).ListCategoriesByMerchantID), ctx, merchantID)
}

// ListImagesByMenuID mocks base method.
func (m *MockRepository) ListImagesByMenuID(ctx context.Context, menuID uuid.UUID) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListImagesByMenuID", ctx, menuID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListImagesByMenuID indicates an expected call of ListImagesByMenuID.
func (mr *MockRepositoryMockRecorder) ListImagesByMenuID(ctx, menuID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListImagesByMenuID", reflect.TypeOf((*MockRepository)(nil).ListImagesByMenuID), ctx, menuID)
}

// ListMenusByMerchantID mocks base method.
func (m *MockRepository) ListMenusByMerchantID(ctx context.Context, merchantID uuid.UUID, onlyAvailable bool) ([]merchant.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMenusByMerchantID", ctx, merchantID, onlyAvailable)
	ret0, _ := ret[0].([]merchant.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMenusByMerchantID indicates an expected call of ListMenusByMerchantID.
func (mr *MockRepositoryMockRecorder) ListMenusByMerchantID(ctx, merchantID, onlyAvailable any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMenusByMerchantID", reflect.TypeOf((*MockRepository)(nil).ListMenusByMerchantID), ctx, merchantID, onlyAvailable)
}

// ListMenusByMerchantIDWithVariants mocks base method.
func (m *MockRepository) ListMenusByMerchantIDWithVariants(ctx context.Context, merchantID uuid.UUID, onlyAvailable bool) ([]merchant.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMenusByMerchantIDWithVariants", ctx, merchantID, onlyAvailable)
	ret0, _ := ret[0].([]merchant.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMenusByMerchantIDWithVariants indicates an expected call of ListMenusByMerchantIDWithVariants.
func (mr *MockRepositoryMockRecorder) ListMenusByMerchantIDWithVariants(ctx, merchantID, onlyAvailable any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMenusByMerchantIDWithVariants", reflect.TypeOf((*MockRepository)(nil).ListMenusByMerchantIDWithVariants), ctx, merchantID, onlyAvailable)
}

// ListNearbyMerchants mocks base method.
func (m *MockRepository) ListNearbyMerchants(ctx context.Context, lat, lng, radiusKm float64) ([]merchant.Merchant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNearbyMerchants", ctx, lat, lng, radiusKm)
	ret0, _ := ret[0].([]merchant.Merchant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNearbyMerchants indicates an expected call of ListNearbyMerchants.
func (mr *MockRepositoryMockRecorder) ListNearbyMerchants(ctx, lat, lng, radiusKm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNearbyMerchants", reflect.TypeOf((*MockRepository)(nil).ListNearbyMerchants), ctx, lat, lng, radiusKm)
}

// ListNearbyMerchantsWithDistance mocks base method.
func (m *MockRepository) ListNearbyMerchantsWithDistance(ctx context.Context, lat, lng, radiusKm float64) ([]merchant.Merchant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNearbyMerchantsWithDistance", ctx, lat, lng, radiusKm)
	ret0, _ := ret[0].([]merchant.Merchant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNearbyMerchantsWithDistance indicates an expected call of ListNearbyMerchantsWithDistance.
func (mr *MockRepositoryMockRecorder) ListNearbyMerchantsWithDistance(ctx, lat, lng, radiusKm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNearbyMerchantsWithDistance", reflect.TypeOf((*MockRepository)(nil).ListNearbyMerchantsWithDistance), ctx, lat, lng, radiusKm)
}

// ListOrderItemsByOrderID mocks base method.
func (m *MockRepository) ListOrderItemsByOrderID(ctx context.Context, orderID uuid.UUID) ([]merchant.OrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrderItemsByOrderID", ctx, orderID)
	ret0, _ := ret[0].([]merchant.OrderItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrderItemsByOrderID indicates an expected call of ListOrderItemsByOrderID.
func (mr *MockRepositoryMockRecorder) ListOrderItemsByOrderID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrderItemsByOrderID", reflect.TypeOf((*MockRepository)(nil).ListOrderItemsByOrderID), ctx, orderID)
}

// ListToppingGroupsByMenuID mocks base method.
func (m *MockRepository) ListToppingGroupsByMenuID(ctx context.Context, menuID uuid.UUID) ([]merchant.MenuToppingGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListToppingGroupsByMenuID", ctx, menuID)
	ret0, _ := ret[0].([]merchant.MenuToppingGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListToppingGroupsByMenuID indicates an expected call of ListToppingGroupsByMenuID.
func (mr *MockRepositoryMockRecorder) ListToppingGroupsByMenuID(ctx, menuID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListToppingGroupsByMenuID", reflect.TypeOf((*MockRepository)(nil).ListToppingGroupsByMenuID), ctx, menuID)
}

// ListToppingOptionsByGroupID mocks base method.
func (m *MockRepository) ListToppingOptionsByGroupID(ctx context.Context, groupID uuid.UUID) ([]merchant.MenuToppingOption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListToppingOptionsByGroupID", ctx, groupID)
	ret0, _ := ret[0].([]merchant.MenuToppingOption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListToppingOptionsByGroupID indicates an expected call of ListToppingOptionsByGroupID.
func (mr *MockRepositoryMockRecorder) ListToppingOptionsByGroupID(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListToppingOptionsByGroupID", reflect.TypeOf((*MockRepository)(nil).ListToppingOptionsByGroupID), ctx, groupID)
}

// ListVariantGroupsByMenuID mocks base method.
func (m *MockRepository) ListVariantGroupsByMenuID(ctx context.Context, menuID uuid.UUID) ([]merchant.MenuVariantGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVariantGroupsByMenuID", ctx, menuID)
	ret0, _ := ret[0].([]merchant.MenuVariantGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVariantGroupsByMenuID indicates an expected call of ListVariantGroupsByMenuID.
func (mr *MockRepositoryMockRecorder) ListVariantGroupsByMenuID(ctx, menuID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVariantGroupsByMenuID", reflect.TypeOf((*MockRepository)(nil).ListVariantGroupsByMenuID), ctx, menuID)
}

// ListVariantOptionsByGroupID mocks base method.
func (m *MockRepository) ListVariantOptionsByGroupID(ctx context.Context, groupID uuid.UUID) ([]merchant.MenuVariantOption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVariantOptionsByGroupID", ctx, groupID)
	ret0, _ := ret[0].([]merchant.MenuVariantOption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVariantOptionsByGroupID indicates an expected call of ListVariantOptionsByGroupID.
func (mr *MockRepositoryMockRecorder) ListVariantOptionsByGroupID(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVariantOptionsByGroupID", reflect.TypeOf((*MockRepository)(nil).ListVariantOptionsByGroupID), ctx, groupID)
}

// UpdateAddonMaster mocks base method.
func (m_2 *MockRepository) UpdateAddonMaster(ctx context.Context, m *merchant.AddonMaster) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "UpdateAddonMaster", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAddonMaster indicates an expected call of UpdateAddonMaster.
func (mr *MockRepositoryMockRecorder) UpdateAddonMaster(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAddonMaster", reflect.TypeOf((*MockRepository)(nil).UpdateAddonMaster), ctx, m)
}

// UpdateAddonOption mocks base method.
func (m *MockRepository) UpdateAddonOption(ctx context.Context, o *merchant.AddonOption) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAddonOption", ctx, o)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAddonOption indicates an expected call of UpdateAddonOption.
func (mr *MockRepositoryMockRecorder) UpdateAddonOption(ctx, o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAddonOption", reflect.TypeOf((*MockRepository)(nil).UpdateAddonOption), ctx, o)
}

// UpdateCategory mocks base method.
func (m *MockRepository) UpdateCategory(ctx context.Context, c *merchant.MenuCategory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCategory", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCategory indicates an expected call of UpdateCategory.
func (mr *MockRepositoryMockRecorder) UpdateCategory(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCategory", reflect.TypeOf((*MockRepository)(nil).UpdateCategory), ctx, c)
}

// UpdateMenu mocks base method.
func (m *MockRepository) UpdateMenu(ctx context.Context, menu *merchant.Menu) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMenu", ctx, menu)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMenu indicates an expected call of UpdateMenu.
func (mr *MockRepositoryMockRecorder) UpdateMenu(ctx, menu any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMenu", reflect.TypeOf((*MockRepository)(nil).UpdateMenu), ctx, menu)
}

// UpdateMerchant mocks base method.
func (m_2 *MockRepository) UpdateMerchant(ctx context.Context, m *merchant.Merchant) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "UpdateMerchant", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMerchant indicates an expected call of UpdateMerchant.
func (mr *MockRepositoryMockRecorder) UpdateMerchant(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMerchant", reflect.TypeOf((*MockRepository)(nil).UpdateMerchant), ctx, m)
}

// UpdateToppingGroup mocks base method.
func (m *MockRepository) UpdateToppingGroup(ctx context.Context, g *merchant.MenuToppingGroup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateToppingGroup", ctx, g)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateToppingGroup indicates an expected call of UpdateToppingGroup.
func (mr *MockRepositoryMockRecorder) UpdateToppingGroup(ctx, g any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateToppingGroup", reflect.TypeOf((*MockRepository)(nil).UpdateToppingGroup), ctx, g)
}

// UpdateToppingOption mocks base method.
func (m *MockRepository) UpdateToppingOption(ctx context.Context, o *merchant.MenuToppingOption) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateToppingOption", ctx, o)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateToppingOption indicates an expected call of UpdateToppingOption.
func (mr *MockRepositoryMockRecorder) UpdateToppingOption(ctx, o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateToppingOption", reflect.TypeOf((*MockRepository)(nil).UpdateToppingOption), ctx, o)
}

// UpdateVariantGroup mocks base method.
func (m *MockRepository) UpdateVariantGroup(ctx context.Context, g *merchant.MenuVariantGroup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVariantGroup", ctx, g)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateVariantGroup indicates an expected call of UpdateVariantGroup.
func (mr *MockRepositoryMockRecorder) UpdateVariantGroup(ctx, g any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVariantGroup", reflect.TypeOf((*MockRepository)(nil).UpdateVariantGroup), ctx, g)
}

// UpdateVariantOption mocks base method.
func (m *MockRepository) UpdateVariantOption(ctx context.Context, o *merchant.MenuVariantOption) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVariantOption", ctx, o)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateVariantOption indicates an expected call of UpdateVariantOption.
func (mr *MockRepositoryMockRecorder) UpdateVariantOption(ctx, o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVariantOption", reflect.TypeOf((*MockRepository)(nil).UpdateVariantOption), ctx, o)
}
