// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	merchant "github.com/codecoffy/nitip-core/internal/domain/merchant"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreateAddonMaster mocks base method.
func (m *MockService) CreateAddonMaster(ctx context.Context, merchantID uuid.UUID, name, imageURL string, sortOrder int) (*merchant.AddonMaster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAddonMaster", ctx, merchantID, name, imageURL, sortOrder)
	ret0, _ := ret[0].(*merchant.AddonMaster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAddonMaster indicates an expected call of CreateAddonMaster.
func (mr *MockServiceMockRecorder) CreateAddonMaster(ctx, merchantID, name, imageURL, sortOrder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAddonMaster", reflect.TypeOf((*MockService)(nil).CreateAddonMaster), ctx, merchantID, name, imageURL, sortOrder)
}

// CreateAddonOption mocks base method.
func (m *MockService) CreateAddonOption(ctx context.Context, masterID uuid.UUID, label string, priceDelta float64, imageURL string, isAvailable bool, sortOrder int) (*merchant.AddonOption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAddonOption", ctx, masterID, label, priceDelta, imageURL, isAvailable, sortOrder)
	ret0, _ := ret[0].(*merchant.AddonOption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAddonOption indicates an expected call of CreateAddonOption.
func (mr *MockServiceMockRecorder) CreateAddonOption(ctx, masterID, label, priceDelta, imageURL, isAvailable, sortOrder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAddonOption", reflect.TypeOf((*MockService)(nil).CreateAddonOption), ctx, masterID, label, priceDelta, imageURL, isAvailable, sortOrder)
}

// CreateCategory mocks base method.
func (m *MockService) CreateCategory(ctx context.Context, merchantID uuid.UUID, name, imageURL string, sortOrder int) (*merchant.MenuCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCategory", ctx, merchantID, name, imageURL, sortOrder)
	ret0, _ := ret[0].(*merchant.MenuCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCategory indicates an expected call of CreateCategory.
func (mr *MockServiceMockRecorder) CreateCategory(ctx, merchantID, name, imageURL, sortOrder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCategory", reflect.TypeOf((*MockService)(nil).CreateCategory), ctx, merchantID, name, imageURL, sortOrder)
}

// CreateMenu mocks base method.
func (m *MockService) CreateMenu(ctx context.Context, merchantID uuid.UUID, name, description string, price float64, imageURL string, isAvailable bool) (*merchant.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMenu", ctx, merchantID, name, description, price, imageURL, isAvailable)
	ret0, _ := ret[0].(*merchant.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMenu indicates an expected call of CreateMenu.
func (mr *MockServiceMockRecorder) CreateMenu(ctx, merchantID, name, description, price, imageURL, isAvailable any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMenu", reflect.TypeOf((*MockService)(nil).CreateMenu), ctx, merchantID, name, description, price, imageURL, isAvailable)
}

// CreateMerchant mocks base method.
func (m *MockService) CreateMerchant(ctx context.Context, ownerID uuid.UUID, name, description, address string, lat, lng float64, category string, autoConfirm bool, maxActiveOrders int) (*merchant.Merchant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMerchant", ctx, ownerID, name, description, address, lat, lng, category, autoConfirm, maxActiveOrders)
	ret0, _ := ret[0].(*merchant.Merchant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMerchant indicates an expected call of CreateMerchant.
func (mr *MockServiceMockRecorder) CreateMerchant(ctx, ownerID, name, description, address, lat, lng, category, autoConfirm, maxActiveOrders any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMerchant", reflect.TypeOf((*MockService)(nil).CreateMerchant), ctx, ownerID, name, description, address, lat, lng, category, autoConfirm, maxActiveOrders)
}

// CreateOrderItems mocks base method.
func (m *MockService) CreateOrderItems(ctx context.Context, items []merchant.OrderItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrderItems", ctx, items)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrderItems indicates an expected call of CreateOrderItems.
func (mr *MockServiceMockRecorder) CreateOrderItems(ctx, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrderItems", reflect.TypeOf((*MockService)(nil).CreateOrderItems), ctx, items)
}

// CreateSurvey mocks base method.
func (m *MockService) CreateSurvey(ctx context.Context, merchantID uuid.UUID, monthlySalesRange string, averageItemPrice float64) (*merchant.MerchantSurvey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSurvey", ctx, merchantID, monthlySalesRange, averageItemPrice)
	ret0, _ := ret[0].(*merchant.MerchantSurvey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSurvey indicates an expected call of CreateSurvey.
func (mr *MockServiceMockRecorder) CreateSurvey(ctx, merchantID, monthlySalesRange, averageItemPrice any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSurvey", reflect.TypeOf((*MockService)(nil).CreateSurvey), ctx, merchantID, monthlySalesRange, averageItemPrice)
}

// CreateToppingGroup mocks base method.
func (m *MockService) CreateToppingGroup(ctx context.Context, menuID uuid.UUID, variantOptionID *uuid.UUID, name, gtype string, isRequired bool, minSelect int, maxSelect *int, sortOrder int) (*merchant.MenuToppingGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateToppingGroup", ctx, menuID, variantOptionID, name, gtype, isRequired, minSelect, maxSelect, sortOrder)
	ret0, _ := ret[0].(*merchant.MenuToppingGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateToppingGroup indicates an expected call of CreateToppingGroup.
func (mr *MockServiceMockRecorder) CreateToppingGroup(ctx, menuID, variantOptionID, name, gtype, isRequired, minSelect, maxSelect, sortOrder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateToppingGroup", reflect.TypeOf((*MockService)(nil).CreateToppingGroup), ctx, menuID, variantOptionID, name, gtype, isRequired, minSelect, maxSelect, sortOrder)
}

// CreateToppingOption mocks base method.
func (m *MockService) CreateToppingOption(ctx context.Context, groupID uuid.UUID, label string, priceDelta float64, imageURL string, isAvailable bool, sortOrder int) (*merchant.MenuToppingOption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateToppingOption", ctx, groupID, label, priceDelta, imageURL, isAvailable, sortOrder)
	ret0, _ := ret[0].(*merchant.MenuToppingOption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateToppingOption indicates an expected call of CreateToppingOption.
func (mr *MockServiceMockRecorder) CreateToppingOption(ctx, groupID, label, priceDelta, imageURL, isAvailable, sortOrder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateToppingOption", reflect.TypeOf((*MockService)(nil).CreateToppingOption), ctx, groupID, label, priceDelta, imageURL, isAvailable, sortOrder)
}

// CreateVariantGroup mocks base method.
func (m *MockService) CreateVariantGroup(ctx context.Context, menuID uuid.UUID, name, gtype string, isRequired bool, minSelect int, maxSelect *int, sortOrder int) (*merchant.MenuVariantGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVariantGroup", ctx, menuID, name, gtype, isRequired, minSelect, maxSelect, sortOrder)
	ret0, _ := ret[0].(*merchant.MenuVariantGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVariantGroup indicates an expected call of CreateVariantGroup.
func (mr *MockServiceMockRecorder) CreateVariantGroup(ctx, menuID, name, gtype, isRequired, minSelect, maxSelect, sortOrder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVariantGroup", reflect.TypeOf((*MockService)(nil).CreateVariantGroup), ctx, menuID, name, gtype, isRequired, minSelect, maxSelect, sortOrder)
}

// CreateVariantOption mocks base method.
func (m *MockService) CreateVariantOption(ctx context.Context, groupID uuid.UUID, label string, priceDelta float64, imageURL string, isDefault, isAvailable bool, sortOrder int) (*merchant.MenuVariantOption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVariantOption", ctx, groupID, label, priceDelta, imageURL, isDefault, isAvailable, sortOrder)
	ret0, _ := ret[0].(*merchant.MenuVariantOption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVariantOption indicates an expected call of CreateVariantOption.
func (mr *MockServiceMockRecorder) CreateVariantOption(ctx, groupID, label, priceDelta, imageURL, isDefault, isAvailable, sortOrder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVariantOption", reflect.TypeOf((*MockService)(nil).CreateVariantOption), ctx, groupID, label, priceDelta, imageURL, isDefault, isAvailable, sortOrder)
}

// DeleteAddonMaster mocks base method.
func (m *MockService) DeleteAddonMaster(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAddonMaster", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAddonMaster indicates an expected call of DeleteAddonMaster.
func (mr *MockServiceMockRecorder) DeleteAddonMaster(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAddonMaster", reflect.TypeOf((*MockService)(nil).DeleteAddonMaster), ctx, id)
}

// DeleteAddonOption mocks base method.
func (m *MockService) DeleteAddonOption(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAddonOption", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAddonOption indicates an expected call of DeleteAddonOption.
func (mr *MockServiceMockRecorder) DeleteAddonOption(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAddonOption", reflect.TypeOf((*MockService)(nil).DeleteAddonOption), ctx, id)
}

// DeleteCategory mocks base method.
func (m *MockService) DeleteCategory(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCategory", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCategory indicates an expected call of DeleteCategory.
func (mr *MockServiceMockRecorder) DeleteCategory(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCategory", reflect.TypeOf((*MockService)(nil).DeleteCategory), ctx, id)
}

// DeleteMenu mocks base method.
func (m *MockService) DeleteMenu(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMenu", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMenu indicates an expected call of DeleteMenu.
func (mr *MockServiceMockRecorder) DeleteMenu(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMenu", reflect.TypeOf((*MockService)(nil).DeleteMenu), ctx, id)
}

// DeleteMerchant mocks base method.
func (m *MockService) DeleteMerchant(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMerchant", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMerchant indicates an expected call of DeleteMerchant.
func (mr *MockServiceMockRecorder) DeleteMerchant(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMerchant", reflect.TypeOf((*MockService)(nil).DeleteMerchant), ctx, id)
}

// DeleteToppingGroup mocks base method.
func (m *MockService) DeleteToppingGroup(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteToppingGroup", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteToppingGroup indicates an expected call of DeleteToppingGroup.
func (mr *MockServiceMockRecorder) DeleteToppingGroup(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteToppingGroup", reflect.TypeOf((*MockService)(nil).DeleteToppingGroup), ctx, id)
}

// DeleteToppingOption mocks base method.
func (m *MockService) DeleteToppingOption(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteToppingOption", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteToppingOption indicates an expected call of DeleteToppingOption.
func (mr *MockServiceMockRecorder) DeleteToppingOption(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteToppingOption", reflect.TypeOf((*MockService)(nil).DeleteToppingOption), ctx, id)
}

// DeleteVariantGroup mocks base method.
func (m *MockService) DeleteVariantGroup(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVariantGroup", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVariantGroup indicates an expected call of DeleteVariantGroup.
func (mr *MockServiceMockRecorder) DeleteVariantGroup(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVariantGroup", reflect.TypeOf((*MockService)(nil).DeleteVariantGroup), ctx, id)
}

// DeleteVariantOption mocks base method.
func (m *MockService) DeleteVariantOption(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVariantOption", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVariantOption indicates an expected call of DeleteVariantOption.
func (mr *MockServiceMockRecorder) DeleteVariantOption(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVariantOption", reflect.TypeOf((*MockService)(nil).DeleteVariantOption), ctx, id)
}

// GetAddonMasterByID mocks base method.
func (m *MockService) GetAddonMasterByID(ctx context.Context, id uuid.UUID) (*merchant.AddonMaster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAddonMasterByID", ctx, id)
	ret0, _ := ret[0].(*merchant.AddonMaster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAddonMasterByID indicates an expected call of GetAddonMasterByID.
func (mr *MockServiceMockRecorder) GetAddonMasterByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAddonMasterByID", reflect.TypeOf((*MockService)(nil).GetAddonMasterByID), ctx, id)
}

// GetMenuByID mocks base method.
func (m *MockService) GetMenuByID(ctx context.Context, id uuid.UUID) (*merchant.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMenuByID", ctx, id)
	ret0, _ := ret[0].(*merchant.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMenuByID indicates an expected call of GetMenuByID.
func (mr *MockServiceMockRecorder) GetMenuByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMenuByID", reflect.TypeOf((*MockService)(nil).GetMenuByID), ctx, id)
}

// GetMerchantByID mocks base method.
func (m *MockService) GetMerchantByID(ctx context.Context, id uuid.UUID) (*merchant.Merchant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMerchantByID", ctx, id)
	ret0, _ := ret[0].(*merchant.Merchant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMerchantByID indicates an expected call of GetMerchantByID.
func (mr *MockServiceMockRecorder) GetMerchantByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMerchantByID", reflect.TypeOf((*MockService)(nil).GetMerchantByID), ctx, id)
}

// GetMerchantByOwnerID mocks base method.
func (m *MockService) GetMerchantByOwnerID(ctx context.Context, ownerID uuid.UUID) (*merchant.Merchant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMerchantByOwnerID", ctx, ownerID)
	ret0, _ := ret[0].(*merchant.Merchant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMerchantByOwnerID indicates an expected call of GetMerchantByOwnerID.
func (mr *MockServiceMockRecorder) GetMerchantByOwnerID(ctx, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMerchantByOwnerID", reflect.TypeOf((*MockService)(nil).GetMerchantByOwnerID), ctx, ownerID)
}

// ListAddonMastersByMerchantID mocks base method.
func (m *MockService) ListAddonMastersByMerchantID(ctx context.Context, merchantID uuid.UUID) ([]merchant.AddonMaster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAddonMastersByMerchantID", ctx, merchantID)
	ret0, _ := ret[0].([]merchant.AddonMaster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAddonMastersByMerchantID indicates an expected call of ListAddonMastersByMerchantID.
func (mr *MockServiceMockRecorder) ListAddonMastersByMerchantID(ctx, merchantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAddonMastersByMerchantID", reflect.TypeOf((*MockService)(nil).ListAddonMastersByMerchantID), ctx, merchantID)
}

// ListAllMerchants mocks base method.
func (m *MockService) ListAllMerchants(ctx context.Context) ([]merchant.Merchant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllMerchants", ctx)
	ret0, _ := ret[0].([]merchant.Merchant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllMerchants indicates an expected call of ListAllMerchants.
func (mr *MockServiceMockRecorder) ListAllMerchants(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllMerchants", reflect.TypeOf((*MockService)(nil).ListAllMerchants), ctx)
}

// ListCategoriesByMerchantID mocks base method.
func (m *MockService) ListCategoriesByMerchantID(ctx context.Context, merchantID uuid.UUID) ([]merchant.MenuCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCategoriesByMerchantID", ctx, merchantID)
	ret0, _ := ret[0].([]merchant.MenuCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCategoriesByMerchantID indicates an expected call of ListCategoriesByMerchantID.
func (mr *MockServiceMockRecorder) ListCategoriesByMerchantID(ctx, merchantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCategoriesByMerchantID", reflect.TypeOf((*MockService)(nil).ListCategoriesByMerchantID), ctx, merchantID)
}

// ListMenusByMerchantID mocks base method.
func (m *MockService) ListMenusByMerchantID(ctx context.Context, merchantID uuid.UUID, onlyAvailable bool) ([]merchant.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMenusByMerchantID", ctx, merchantID, onlyAvailable)
	ret0, _ := ret[0].([]merchant.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMenusByMerchantID indicates an expected call of ListMenusByMerchantID.
func (mr *MockServiceMockRecorder) ListMenusByMerchantID(ctx, merchantID, onlyAvailable any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMenusByMerchantID", reflect.TypeOf((*MockService)(nil).ListMenusByMerchantID), ctx, merchantID, onlyAvailable)
}

// ListMenusByMerchantIDWithVariants mocks base method.
func (m *MockService) ListMenusByMerchantIDWithVariants(ctx context.Context, merchantID uuid.UUID, onlyAvailable bool) ([]merchant.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMenusByMerchantIDWithVariants", ctx, merchantID, onlyAvailable)
	ret0, _ := ret[0].([]merchant.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMenusByMerchantIDWithVariants indicates an expected call of ListMenusByMerchantIDWithVariants.
func (mr *MockServiceMockRecorder) ListMenusByMerchantIDWithVariants(ctx, merchantID, onlyAvailable any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMenusByMerchantIDWithVariants", reflect.TypeOf((*MockService)(nil).ListMenusByMerchantIDWithVariants), ctx, merchantID, onlyAvailable)
}

// ListNearbyMerchants mocks base method.
func (m *MockService) ListNearbyMerchants(ctx context.Context, lat, lng, radiusKm float64) ([]merchant.Merchant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNearbyMerchants", ctx, lat, lng, radiusKm)
	ret0, _ := ret[0].([]merchant.Merchant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNearbyMerchants indicates an expected call of ListNearbyMerchants.
func (mr *MockServiceMockRecorder) ListNearbyMerchants(ctx, lat, lng, radiusKm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNearbyMerchants", reflect.TypeOf((*MockService)(nil).ListNearbyMerchants), ctx, lat, lng, radiusKm)
}

// ListOrderItemsByOrderID mocks base method.
func (m *MockService) ListOrderItemsByOrderID(ctx context.Context, orderID uuid.UUID) ([]merchant.OrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrderItemsByOrderID", ctx, orderID)
	ret0, _ := ret[0].([]merchant.OrderItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrderItemsByOrderID indicates an expected call of ListOrderItemsByOrderID.
func (mr *MockServiceMockRecorder) ListOrderItemsByOrderID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrderItemsByOrderID", reflect.TypeOf((*MockService)(nil).ListOrderItemsByOrderID), ctx, orderID)
}

// ListToppingGroupsByMenuID mocks base method.
func (m *MockService) ListToppingGroupsByMenuID(ctx context.Context, menuID uuid.UUID) ([]merchant.MenuToppingGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListToppingGroupsByMenuID", ctx, menuID)
	ret0, _ := ret[0].([]merchant.MenuToppingGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListToppingGroupsByMenuID indicates an expected call of ListToppingGroupsByMenuID.
func (mr *MockServiceMockRecorder) ListToppingGroupsByMenuID(ctx, menuID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListToppingGroupsByMenuID", reflect.TypeOf((*MockService)(nil).ListToppingGroupsByMenuID), ctx, menuID)
}

// ListVariantGroupsByMenuID mocks base method.
func (m *MockService) ListVariantGroupsByMenuID(ctx context.Context, menuID uuid.UUID) ([]merchant.MenuVariantGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVariantGroupsByMenuID", ctx, menuID)
	ret0, _ := ret[0].([]merchant.MenuVariantGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVariantGroupsByMenuID indicates an expected call of ListVariantGroupsByMenuID.
func (mr *MockServiceMockRecorder) ListVariantGroupsByMenuID(ctx, menuID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVariantGroupsByMenuID", reflect.TypeOf((*MockService)(nil).ListVariantGroupsByMenuID), ctx, menuID)
}

// ToggleAutoConfirm mocks base method.
func (m *MockService) ToggleAutoConfirm(ctx context.Context, id uuid.UUID, autoConfirm bool) (*merchant.Merchant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToggleAutoConfirm", ctx, id, autoConfirm)
	ret0, _ := ret[0].(*merchant.Merchant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToggleAutoConfirm indicates an expected call of ToggleAutoConfirm.
func (mr *MockServiceMockRecorder) ToggleAutoConfirm(ctx, id, autoConfirm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleAutoConfirm", reflect.TypeOf((*MockService)(nil).ToggleAutoConfirm), ctx, id, autoConfirm)
}

// ToggleMenuAvailability mocks base method.
func (m *MockService) ToggleMenuAvailability(ctx context.Context, id uuid.UUID, isAvailable bool) (*merchant.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToggleMenuAvailability", ctx, id, isAvailable)
	ret0, _ := ret[0].(*merchant.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToggleMenuAvailability indicates an expected call of ToggleMenuAvailability.
func (mr *MockServiceMockRecorder) ToggleMenuAvailability(ctx, id, isAvailable any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleMenuAvailability", reflect.TypeOf((*MockService)(nil).ToggleMenuAvailability), ctx, id, isAvailable)
}

// ToggleOpenStatus mocks base method.
func (m *MockService) ToggleOpenStatus(ctx context.Context, id uuid.UUID, isOpen bool) (*merchant.Merchant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToggleOpenStatus", ctx, id, isOpen)
	ret0, _ := ret[0].(*merchant.Merchant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToggleOpenStatus indicates an expected call of ToggleOpenStatus.
func (mr *MockServiceMockRecorder) ToggleOpenStatus(ctx, id, isOpen any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleOpenStatus", reflect.TypeOf((*MockService)(nil).ToggleOpenStatus), ctx, id, isOpen)
}

// UpdateAddonMaster mocks base method.
func (m *MockService) UpdateAddonMaster(ctx context.Context, id uuid.UUID, name, imageURL string, sortOrder int, isActive bool) (*merchant.AddonMaster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAddonMaster", ctx, id, name, imageURL, sortOrder, isActive)
	ret0, _ := ret[0].(*merchant.AddonMaster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAddonMaster indicates an expected call of UpdateAddonMaster.
func (mr *MockServiceMockRecorder) UpdateAddonMaster(ctx, id, name, imageURL, sortOrder, isActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAddonMaster", reflect.TypeOf((*MockService)(nil).UpdateAddonMaster), ctx, id, name, imageURL, sortOrder, isActive)
}

// UpdateAddonOption mocks base method.
func (m *MockService) UpdateAddonOption(ctx context.Context, id uuid.UUID, label string, priceDelta float64, imageURL string, isAvailable bool, sortOrder int) (*merchant.AddonOption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAddonOption", ctx, id, label, priceDelta, imageURL, isAvailable, sortOrder)
	ret0, _ := ret[0].(*merchant.AddonOption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAddonOption indicates an expected call of UpdateAddonOption.
func (mr *MockServiceMockRecorder) UpdateAddonOption(ctx, id, label, priceDelta, imageURL, isAvailable, sortOrder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAddonOption", reflect.TypeOf((*MockService)(nil).UpdateAddonOption), ctx, id, label, priceDelta, imageURL, isAvailable, sortOrder)
}

// UpdateCategory mocks base method.
func (m *MockService) UpdateCategory(ctx context.Context, id uuid.UUID, name, imageURL string, sortOrder int, isActive bool) (*merchant.MenuCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCategory", ctx, id, name, imageURL, sortOrder, isActive)
	ret0, _ := ret[0].(*merchant.MenuCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCategory indicates an expected call of UpdateCategory.
func (mr *MockServiceMockRecorder) UpdateCategory(ctx, id, name, imageURL, sortOrder, isActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCategory", reflect.TypeOf((*MockService)(nil).UpdateCategory), ctx, id, name, imageURL, sortOrder, isActive)
}

// UpdateMenu mocks base method.
func (m *MockService) UpdateMenu(ctx context.Context, id uuid.UUID, name, description string, price float64, imageURL string, isAvailable bool) (*merchant.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMenu", ctx, id, name, description, price, imageURL, isAvailable)
	ret0, _ := ret[0].(*merchant.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMenu indicates an expected call of UpdateMenu.
func (mr *MockServiceMockRecorder) UpdateMenu(ctx, id, name, description, price, imageURL, isAvailable any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMenu", reflect.TypeOf((*MockService)(nil).UpdateMenu), ctx, id, name, description, price, imageURL, isAvailable)
}

// UpdateMenuFull mocks base method.
func (m *MockService) UpdateMenuFull(ctx context.Context, id uuid.UUID, name, description string, price float64, imageURL string, categoryID *uuid.UUID, isAvailable bool) (*merchant.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMenuFull", ctx, id, name, description, price, imageURL, categoryID, isAvailable)
	ret0, _ := ret[0].(*merchant.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMenuFull indicates an expected call of UpdateMenuFull.
func (mr *MockServiceMockRecorder) UpdateMenuFull(ctx, id, name, description, price, imageURL, categoryID, isAvailable any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMenuFull", reflect.TypeOf((*MockService)(nil).UpdateMenuFull), ctx, id, name, description, price, imageURL, categoryID, isAvailable)
}

// UpdateMerchant mocks base method.
func (m *MockService) UpdateMerchant(ctx context.Context, id uuid.UUID, name, description, address string, lat, lng float64, category string, maxActiveOrders int) (*merchant.Merchant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMerchant", ctx, id, name, description, address, lat, lng, category, maxActiveOrders)
	ret0, _ := ret[0].(*merchant.Merchant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMerchant indicates an expected call of UpdateMerchant.
func (mr *MockServiceMockRecorder) UpdateMerchant(ctx, id, name, description, address, lat, lng, category, maxActiveOrders any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMerchant", reflect.TypeOf((*MockService)(nil).UpdateMerchant), ctx, id, name, description, address, lat, lng, category, maxActiveOrders)
}

// UpdateMerchantFull mocks base method.
func (m *MockService) UpdateMerchantFull(ctx context.Context, id uuid.UUID, name, description, address string, lat, lng float64, category string, maxActiveOrders int, openingHours *merchant.OpeningHours, imageURL, coverURL *string) (*merchant.Merchant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMerchantFull", ctx, id, name, description, address, lat, lng, category, maxActiveOrders, openingHours, imageURL, coverURL)
	ret0, _ := ret[0].(*merchant.Merchant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMerchantFull indicates an expected call of UpdateMerchantFull.
func (mr *MockServiceMockRecorder) UpdateMerchantFull(ctx, id, name, description, address, lat, lng, category, maxActiveOrders, openingHours, imageURL, coverURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMerchantFull", reflect.TypeOf((*MockService)(nil).UpdateMerchantFull), ctx, id, name, description, address, lat, lng, category, maxActiveOrders, openingHours, imageURL, coverURL)
}

// UpdateToppingGroup mocks base method.
func (m *MockService) UpdateToppingGroup(ctx context.Context, id uuid.UUID, name, gtype string, isRequired bool, minSelect int, maxSelect *int, sortOrder int) (*merchant.MenuToppingGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateToppingGroup", ctx, id, name, gtype, isRequired, minSelect, maxSelect, sortOrder)
	ret0, _ := ret[0].(*merchant.MenuToppingGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateToppingGroup indicates an expected call of UpdateToppingGroup.
func (mr *MockServiceMockRecorder) UpdateToppingGroup(ctx, id, name, gtype, isRequired, minSelect, maxSelect, sortOrder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateToppingGroup", reflect.TypeOf((*MockService)(nil).UpdateToppingGroup), ctx, id, name, gtype, isRequired, minSelect, maxSelect, sortOrder)
}

// UpdateToppingOption mocks base method.
func (m *MockService) UpdateToppingOption(ctx context.Context, id uuid.UUID, label string, priceDelta float64, imageURL string, isAvailable bool, sortOrder int) (*merchant.MenuToppingOption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateToppingOption", ctx, id, label, priceDelta, imageURL, isAvailable, sortOrder)
	ret0, _ := ret[0].(*merchant.MenuToppingOption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateToppingOption indicates an expected call of UpdateToppingOption.
func (mr *MockServiceMockRecorder) UpdateToppingOption(ctx, id, label, priceDelta, imageURL, isAvailable, sortOrder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateToppingOption", reflect.TypeOf((*MockService)(nil).UpdateToppingOption), ctx, id, label, priceDelta, imageURL, isAvailable, sortOrder)
}

// UpdateVariantGroup mocks base method.
func (m *MockService) UpdateVariantGroup(ctx context.Context, id uuid.UUID, name, gtype string, isRequired bool, minSelect int, maxSelect *int, sortOrder int) (*merchant.MenuVariantGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVariantGroup", ctx, id, name, gtype, isRequired, minSelect, maxSelect, sortOrder)
	ret0, _ := ret[0].(*merchant.MenuVariantGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateVariantGroup indicates an expected call of UpdateVariantGroup.
func (mr *MockServiceMockRecorder) UpdateVariantGroup(ctx, id, name, gtype, isRequired, minSelect, maxSelect, sortOrder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVariantGroup", reflect.TypeOf((*MockService)(nil).UpdateVariantGroup), ctx, id, name, gtype, isRequired, minSelect, maxSelect, sortOrder)
}

// UpdateVariantOption mocks base method.
func (m *MockService) UpdateVariantOption(ctx context.Context, id uuid.UUID, label string, priceDelta float64, imageURL string, isDefault, isAvailable bool, sortOrder int) (*merchant.MenuVariantOption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVariantOption", ctx, id, label, priceDelta, imageURL, isDefault, isAvailable, sortOrder)
	ret0, _ := ret[0].(*merchant.MenuVariantOption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateVariantOption indicates an expected call of UpdateVariantOption.
func (mr *MockServiceMockRecorder) UpdateVariantOption(ctx, id, label, priceDelta, imageURL, isDefault, isAvailable, sortOrder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVariantOption", reflect.TypeOf((*MockService)(nil).UpdateVariantOption), ctx, id, label, priceDelta, imageURL, isDefault, isAvailable, sortOrder)
}

// UploadMenuImage mocks base method.
func (m *MockService) UploadMenuImage(ctx context.Context, filename string, content io.Reader, size int64, contentType string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadMenuImage", ctx, filename, content, size, contentType)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadMenuImage indicates an expected call of UploadMenuImage.
func (mr *MockServiceMockRecorder) UploadMenuImage(ctx, filename, content, size, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadMenuImage", reflect.TypeOf((*MockService)(nil).UploadMenuImage), ctx, filename, content, size, contentType)
}
