// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mocks/repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	trip "github.com/codecoffy/nitip-core/internal/domain/trip"
	uuid "github.com/google/uuid"
	bun "github.com/uptrace/bun"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, arg1 *trip.Trip) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, arg1)
}

// FindActiveByLocation mocks base method.
func (m *MockRepository) FindActiveByLocation(ctx context.Context, lat, lng, radiusKm float64) ([]trip.Trip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActiveByLocation", ctx, lat, lng, radiusKm)
	ret0, _ := ret[0].([]trip.Trip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActiveByLocation indicates an expected call of FindActiveByLocation.
func (mr *MockRepositoryMockRecorder) FindActiveByLocation(ctx, lat, lng, radiusKm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActiveByLocation", reflect.TypeOf((*MockRepository)(nil).FindActiveByLocation), ctx, lat, lng, radiusKm)
}

// FindAllActive mocks base method.
func (m *MockRepository) FindAllActive(ctx context.Context) ([]trip.Trip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllActive", ctx)
	ret0, _ := ret[0].([]trip.Trip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllActive indicates an expected call of FindAllActive.
func (mr *MockRepositoryMockRecorder) FindAllActive(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllActive", reflect.TypeOf((*MockRepository)(nil).FindAllActive), ctx)
}

// FindByID mocks base method.
func (m *MockRepository) FindByID(ctx context.Context, id uuid.UUID) (*trip.Trip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*trip.Trip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRepository)(nil).FindByID), ctx, id)
}

// FindByRunnerID mocks base method.
func (m *MockRepository) FindByRunnerID(ctx context.Context, runnerID uuid.UUID) ([]trip.Trip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByRunnerID", ctx, runnerID)
	ret0, _ := ret[0].([]trip.Trip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByRunnerID indicates an expected call of FindByRunnerID.
func (mr *MockRepositoryMockRecorder) FindByRunnerID(ctx, runnerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByRunnerID", reflect.TypeOf((*MockRepository)(nil).FindByRunnerID), ctx, runnerID)
}

// RestoreCapacity mocks base method.
func (m *MockRepository) RestoreCapacity(ctx context.Context, db bun.IDB, id uuid.UUID, weight, volume float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreCapacity", ctx, db, id, weight, volume)
	ret0, _ := ret[0].(error)
	return ret0
}

// RestoreCapacity indicates an expected call of RestoreCapacity.
func (mr *MockRepositoryMockRecorder) RestoreCapacity(ctx, db, id, weight, volume any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreCapacity", reflect.TypeOf((*MockRepository)(nil).RestoreCapacity), ctx, db, id, weight, volume)
}

// Update mocks base method.
func (m *MockRepository) Update(ctx context.Context, arg1 *trip.Trip) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder) Update(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), ctx, arg1)
}

// UpdateCapacity mocks base method.
func (m *MockRepository) UpdateCapacity(ctx context.Context, db bun.IDB, id uuid.UUID, weight, volume float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCapacity", ctx, db, id, weight, volume)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCapacity indicates an expected call of UpdateCapacity.
func (mr *MockRepositoryMockRecorder) UpdateCapacity(ctx, db, id, weight, volume any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCapacity", reflect.TypeOf((*MockRepository)(nil).UpdateCapacity), ctx, db, id, weight, volume)
}
