// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	trip "github.com/codecoffy/nitip-core/internal/domain/trip"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockService) Cancel(ctx context.Context, tripID, runnerID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", ctx, tripID, runnerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cancel indicates an expected call of Cancel.
func (mr *MockServiceMockRecorder) Cancel(ctx, tripID, runnerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockService)(nil).Cancel), ctx, tripID, runnerID)
}

// Complete mocks base method.
func (m *MockService) Complete(ctx context.Context, tripID, runnerID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Complete", ctx, tripID, runnerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Complete indicates an expected call of Complete.
func (mr *MockServiceMockRecorder) Complete(ctx, tripID, runnerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Complete", reflect.TypeOf((*MockService)(nil).Complete), ctx, tripID, runnerID)
}

// Create mocks base method.
func (m *MockService) Create(ctx context.Context, runnerID uuid.UUID, req trip.CreateTripRequest) (*trip.Trip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, runnerID, req)
	ret0, _ := ret[0].(*trip.Trip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockServiceMockRecorder) Create(ctx, runnerID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockService)(nil).Create), ctx, runnerID, req)
}

// GetByRunner mocks base method.
func (m *MockService) GetByRunner(ctx context.Context, runnerID uuid.UUID) ([]trip.Trip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByRunner", ctx, runnerID)
	ret0, _ := ret[0].([]trip.Trip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByRunner indicates an expected call of GetByRunner.
func (mr *MockServiceMockRecorder) GetByRunner(ctx, runnerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByRunner", reflect.TypeOf((*MockService)(nil).GetByRunner), ctx, runnerID)
}

// ListActive mocks base method.
func (m *MockService) ListActive(ctx context.Context) ([]trip.Trip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActive", ctx)
	ret0, _ := ret[0].([]trip.Trip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActive indicates an expected call of ListActive.
func (mr *MockServiceMockRecorder) ListActive(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActive", reflect.TypeOf((*MockService)(nil).ListActive), ctx)
}

// Start mocks base method.
func (m *MockService) Start(ctx context.Context, tripID, runnerID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, tripID, runnerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockServiceMockRecorder) Start(ctx, tripID, runnerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockService)(nil).Start), ctx, tripID, runnerID)
}
