// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	audit "github.com/codecoffy/nitip-core/internal/domain/audit"
	uuid "github.com/google/uuid"
	bun "github.com/uptrace/bun"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockService) List(ctx context.Context, offset, limit int, action string) ([]audit.AuditLog, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, offset, limit, action)
	ret0, _ := ret[0].([]audit.AuditLog)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockServiceMockRecorder) List(ctx, offset, limit, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockService)(nil).List), ctx, offset, limit, action)
}

// Log mocks base method.
func (m *MockService) Log(ctx context.Context, userID *uuid.UUID, action, resource, resourceID string, oldValues, newValues any, ip, ua string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Log", ctx, userID, action, resource, resourceID, oldValues, newValues, ip, ua)
}

// Log indicates an expected call of Log.
func (mr *MockServiceMockRecorder) Log(ctx, userID, action, resource, resourceID, oldValues, newValues, ip, ua any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockService)(nil).Log), ctx, userID, action, resource, resourceID, oldValues, newValues, ip, ua)
}

// LogWithDB mocks base method.
func (m *MockService) LogWithDB(ctx context.Context, db bun.IDB, userID *uuid.UUID, action, resource, resourceID string, oldValues, newValues any, ip, ua string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogWithDB", ctx, db, userID, action, resource, resourceID, oldValues, newValues, ip, ua)
}

// LogWithDB indicates an expected call of LogWithDB.
func (mr *MockServiceMockRecorder) LogWithDB(ctx, db, userID, action, resource, resourceID, oldValues, newValues, ip, ua any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogWithDB", reflect.TypeOf((*MockService)(nil).LogWithDB), ctx, db, userID, action, resource, resourceID, oldValues, newValues, ip, ua)
}
