// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mocks/repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	review "github.com/codecoffy/nitip-core/internal/domain/review"
	uuid "github.com/google/uuid"
	bun "github.com/uptrace/bun"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, db bun.IDB, arg2 *review.Review) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, db, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, db, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, db, arg2)
}

// GetAverageRatingByMerchant mocks base method.
func (m *MockRepository) GetAverageRatingByMerchant(ctx context.Context, db bun.IDB, merchantID uuid.UUID) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAverageRatingByMerchant", ctx, db, merchantID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAverageRatingByMerchant indicates an expected call of GetAverageRatingByMerchant.
func (mr *MockRepositoryMockRecorder) GetAverageRatingByMerchant(ctx, db, merchantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAverageRatingByMerchant", reflect.TypeOf((*MockRepository)(nil).GetAverageRatingByMerchant), ctx, db, merchantID)
}

// GetAverageRatingByRequester mocks base method.
func (m *MockRepository) GetAverageRatingByRequester(ctx context.Context, db bun.IDB, requesterID uuid.UUID) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAverageRatingByRequester", ctx, db, requesterID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAverageRatingByRequester indicates an expected call of GetAverageRatingByRequester.
func (mr *MockRepositoryMockRecorder) GetAverageRatingByRequester(ctx, db, requesterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAverageRatingByRequester", reflect.TypeOf((*MockRepository)(nil).GetAverageRatingByRequester), ctx, db, requesterID)
}

// GetAverageRatingByReviewee mocks base method.
func (m *MockRepository) GetAverageRatingByReviewee(ctx context.Context, db bun.IDB, revieweeID uuid.UUID) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAverageRatingByReviewee", ctx, db, revieweeID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAverageRatingByReviewee indicates an expected call of GetAverageRatingByReviewee.
func (mr *MockRepositoryMockRecorder) GetAverageRatingByReviewee(ctx, db, revieweeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAverageRatingByReviewee", reflect.TypeOf((*MockRepository)(nil).GetAverageRatingByReviewee), ctx, db, revieweeID)
}

// GetByOrderIDAndReviewerID mocks base method.
func (m *MockRepository) GetByOrderIDAndReviewerID(ctx context.Context, db bun.IDB, orderID, reviewerID uuid.UUID) (*review.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOrderIDAndReviewerID", ctx, db, orderID, reviewerID)
	ret0, _ := ret[0].(*review.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOrderIDAndReviewerID indicates an expected call of GetByOrderIDAndReviewerID.
func (mr *MockRepositoryMockRecorder) GetByOrderIDAndReviewerID(ctx, db, orderID, reviewerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOrderIDAndReviewerID", reflect.TypeOf((*MockRepository)(nil).GetByOrderIDAndReviewerID), ctx, db, orderID, reviewerID)
}

// RunInTx mocks base method.
func (m *MockRepository) RunInTx(ctx context.Context, fn func(context.Context, bun.Tx) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunInTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunInTx indicates an expected call of RunInTx.
func (mr *MockRepositoryMockRecorder) RunInTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunInTx", reflect.TypeOf((*MockRepository)(nil).RunInTx), ctx, fn)
}

// UpdateMerchantRating mocks base method.
func (m *MockRepository) UpdateMerchantRating(ctx context.Context, db bun.IDB, merchantID uuid.UUID, newRating float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMerchantRating", ctx, db, merchantID, newRating)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMerchantRating indicates an expected call of UpdateMerchantRating.
func (mr *MockRepositoryMockRecorder) UpdateMerchantRating(ctx, db, merchantID, newRating any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMerchantRating", reflect.TypeOf((*MockRepository)(nil).UpdateMerchantRating), ctx, db, merchantID, newRating)
}

// UpdateUserTrustScore mocks base method.
func (m *MockRepository) UpdateUserTrustScore(ctx context.Context, db bun.IDB, userID uuid.UUID, newScore float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserTrustScore", ctx, db, userID, newScore)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserTrustScore indicates an expected call of UpdateUserTrustScore.
func (mr *MockRepositoryMockRecorder) UpdateUserTrustScore(ctx, db, userID, newScore any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserTrustScore", reflect.TypeOf((*MockRepository)(nil).UpdateUserTrustScore), ctx, db, userID, newScore)
}
