// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	review "github.com/codecoffy/nitip-core/internal/domain/review"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetReviewByOrder mocks base method.
func (m *MockService) GetReviewByOrder(ctx context.Context, orderID, reviewerID uuid.UUID) (*review.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReviewByOrder", ctx, orderID, reviewerID)
	ret0, _ := ret[0].(*review.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReviewByOrder indicates an expected call of GetReviewByOrder.
func (mr *MockServiceMockRecorder) GetReviewByOrder(ctx, orderID, reviewerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReviewByOrder", reflect.TypeOf((*MockService)(nil).GetReviewByOrder), ctx, orderID, reviewerID)
}

// SubmitReview mocks base method.
func (m *MockService) SubmitReview(ctx context.Context, orderID, reviewerID uuid.UUID, runnerRating int, runnerComment string, merchantRating *int, merchantComment string) (*review.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitReview", ctx, orderID, reviewerID, runnerRating, runnerComment, merchantRating, merchantComment)
	ret0, _ := ret[0].(*review.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitReview indicates an expected call of SubmitReview.
func (mr *MockServiceMockRecorder) SubmitReview(ctx, orderID, reviewerID, runnerRating, runnerComment, merchantRating, merchantComment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitReview", reflect.TypeOf((*MockService)(nil).SubmitReview), ctx, orderID, reviewerID, runnerRating, runnerComment, merchantRating, merchantComment)
}

// SubmitRunnerReview mocks base method.
func (m *MockService) SubmitRunnerReview(ctx context.Context, orderID, runnerID uuid.UUID, requesterRating int, requesterComment string) (*review.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitRunnerReview", ctx, orderID, runnerID, requesterRating, requesterComment)
	ret0, _ := ret[0].(*review.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitRunnerReview indicates an expected call of SubmitRunnerReview.
func (mr *MockServiceMockRecorder) SubmitRunnerReview(ctx, orderID, runnerID, requesterRating, requesterComment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitRunnerReview", reflect.TypeOf((*MockService)(nil).SubmitRunnerReview), ctx, orderID, runnerID, requesterRating, requesterComment)
}
